### ISSUE TITLE
group id for files built by build-server and transferred to spot do not have consistent group IDs

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#10]
Note: Since this is a public repo, I'm going to avoid using specific group ID and user ID names in this ticket.

While checking the permissions and ownership of the build for the 1.0.0-rc.2 version of Neuron, I found that the files are owned by a different group from other repositories that I've deployed in the past.  It looks like this is tied to the way in which the original directory was created.  We developers had a discussion about it on Skype, but weren't clear on exactly what if anything needs to be done.  At the end of the discussion, @pixelzoom said:

> Looks like it's exclusively a group id problem with directories created  by @samreid .

and

> If it's causing problems, see 'chgrp -R'.

We will discuss in developer meeting a figure out next steps.

**Comment by pixelzoom** [comment]
To be a little more specific... 

(1) This is an issue in spot:dev.

(2) When setgid permission is applied to a directory, files that were created in this directory belong to the group to which the directory belongs, not the group to which the creating process belongs. Any user who has write and execute permissions in the directory can create a file there, and the file belongs to the group that owns the directory, not to the user's group ownership.  If the group id is *not* set (which is the case for directories created by @samreid), then files in such a directory will be created using the user's group ownership (which is what @jbphet is seeing in neuron).   

(3) This is likely a umask problem, either on spot or on the host that's being used to do an scp.

**Comment by jbphet** [comment]
My account is used to do the file transfer from figaro to spot, and the umask is 0002 on both, so I'm clear on why it's a umask problem.  To clean this up, it seems like we should make sure that all developer accounts on spot have the same umask and group, and the directories with the problem should have their group id set to physphet.  Is that correct and is there anything else to be done?

**Comment by pixelzoom** [comment]
Your account doesn't have anything to do with it. It's the account that created the directory (@samreid in all cases) that isn't creating the directory with setgid permissions.

**Comment by pixelzoom** [comment]
Btw... The title of this issue is "group id for files built by build-server and transferred to spot do not have consistent group IDs".  I believe that his has nothing to do with build-server.  There are directories that have this problem that pre-date build-server, and the directories with this problem (with 1 exception) are owned by @samreid.  To see the dev/html/ directories on spot with this problem:

```
% ls -l | grep -v drwxrws | grep -v drwxr-s
drwxrwxr-x   4 reids    physphet      58 Feb 18  2015 blackbody-spectrum/
drwxrwxr-x   8 reids    physphet     130 Jun 24  2014 build-a-fraction/
drwxrwxr-x  20 reids    physphet    4096 Aug 28 08:39 color-vision/
drwxrwxr-x  10 reids    physphet    4096 Nov 21  2013 energy-skate-park/
drwxrwxr-x  93 reids    physphet    4096 Nov 20  2014 energy-skate-park-basics/
drwxrwxr-x  13 reids    physphet    4096 Apr 29  2015 fraction-comparison/
drwxrwxr-x  28 reids    physphet    4096 Jul 18  2014 fraction-matcher/
drwxrwxr-x  11 reids    physphet    4096 Jun 24  2014 fractions-intro/
drwxrwxr-x  29 reids    physphet    4096 Oct 27 14:03 gravity-and-orbits/
drwxr-xr-x   2 jblanco  physphet    4096 Sep  1 14:28 jb-tests/
drwxrwxr-x   4 reids    physphet      58 Jun 24  2014 lightbulb/
drwxrwxr-x  17 reids    physphet    4096 Jan 25 10:29 neuron/
drwxrwxr-x  11 reids    physphet    4096 Aug  3 13:17 optics-lab/
drwxrwxr-x   9 reids    physphet     132 Oct 28  2014 protein-synthesis/
drwxrwxr-x  12 reids    physphet    4096 Jun 26  2014 seasons/
drwxrwxr-x   3 reids    physphet      40 Oct 29  2014 sugar-and-salt-solutions/
-rw-rw-r--   1 jblanco  physphet    4632 Feb 23  2015 temp.txt
drwxrwxr-x   5 reids    physphet      98 Aug 14 08:21 together/
drwxrwxr-x   3 reids    physphet      40 Jun 24  2014 vegas/
```

**Comment by samreid** [comment]
How do I resolve this problem?

**Comment by pixelzoom** [comment]
Start by looking at your unmask on spot and on your local machine.

**Comment by samreid** [comment]
Like this?

**Local Machine***
```
~/github/concentration$ umask
0022
~/github/concentration$ umask -S
u=rwx,g=rx,o=rx
```
**Spot**
```
-bash-3.2$ pwd
/home/reids
-bash-3.2$ umask
0002
-bash-3.2$ umask -S
u=rwx,g=rwx,o=rx


-bash-3.2$ cd /htdocs/physics/phet/dev/html/
-bash-3.2$ umask
0002
-bash-3.2$ umask -S
u=rwx,g=rwx,o=rx
```

**Comment by samreid** [comment]
I'm still unclear on what the problem is or how to address it.

**Comment by samreid** [comment]
@pixelzoom surmises that my Windows SCP client was causing these issues.  I can try creating directories a few different ways and see what the groups and permissions are.

**Comment by samreid** [comment]
We also noted that these group permissions seem inconsistent, there may not be an actual problem that needs to be solved.

Meeting consensus: leave the issue open and wait until a practical problem arises.

@pixelzoom suggests to change the group id of the top-level directories so that subsequent directories get created with the correct parent groupid "physphet" instead of "facstaff".  They need the set group id in the permissions so that items created under the directories will get the same ownership.

**Comment by pixelzoom** [comment]
> @pixelzoom suggests to change the group id of the top-level directories

Not quite.  The group id of the directories should be the same (physphet).  The *setgrpid* bit on the directories permissions mask needs to be set.

**Comment by samreid** [comment]
Searching `setgrpid` on Google only yields 920 results, and Google suggests I may have meant `setgpid` which only has 365 results and looks like a C/C++ process priority value.  I feel like I'm going to need help on this issue.  I'm putting this issue on hold and will wait for help from someone that understands unix folder permissions such as @jonathanolson or @pixelzoom.

**Comment by pixelzoom** [comment]
If you haven't already, start by reading the `chmod` man page (`man chmod`) for an overview of file modes, mode bits, etc.

`setuid` and `setgid` are file permissions, not commands, and they correspond to specific mode bits.  See:
• https://docs.oracle.com/cd/E19683-01/816-4883/secfile-69/index.html
• http://www.techrepublic.com/blog/it-security/understand-the-setuid-and-setgid-permissions-to-improve-security/

**Comment by samreid** [comment]
According to: https://en.wikipedia.org/wiki/Setuid

> Setting the setgid bit on existing subdirectories must be done manually, with a command such as the following:

`root@foo# find /path/to/directory -type d -exec chmod g+s '{}' \;`

Since it seems desirable that we have the gid set on all directories under phet/dev/html, I'll try running this command there.  (Perhaps I should check first that each directory has the right group set).

**Comment by samreid** [comment]
I confirmed that all files and folders under physics/phet/dev/html have the correct group `physphet`.

**Comment by samreid** [comment]
When I typed `id` on spot, I found my gid = facstaff, this should not be a problem if all group id bits are set and the folders have physphet owners.

**Comment by samreid** [comment]
By running this command:

`ls -l | grep -v drwxrws | grep -v drwxr-s`

I see the output @pixelzoom described above in https://github.com/phetsims/perennial/issues/10#issuecomment-176304486

According to http://www.toptip.ca/2010/03/linux-setgid-on-directory.html

> We can use the command chmod to set the group ID bit for a directory.

   `chmod g+s mydir`

This makes sense, because we want to change the group execute from x to s.  I will try this command and report back.

**Comment by samreid** [comment]
Before:
```
drwxrwxr-x   4 reids    physphet      58 Feb 18  2015 blackbody-spectrum
```

After
```
drwxrwsr-x   4 reids    physphet      58 Feb 18  2015 blackbody-spectrum
```

The `x` changed to an `s` with no other changes, so this command looks correct.  I'll run the chmod g+s on *

**Comment by samreid** [comment]
There were two that I could not fix with this command:

```
drwxr-xr-x   2 jblanco  physphet    4096 Sep  1 14:28 jb-tests
-rw-rw-r--   1 jblanco  physphet    4632 Feb 23  2015 temp.txt
```

They seem specific to @jbphet and like they do not need group permissions.  However, it would be nice to have a clean report when running

`ls -l | grep -v drwxrws | grep -v drwxr-s`

So I will reassign this issue to @jbphet to finish up.

**Comment by mattpen** [comment]
This does not appear to be relevant to Chipper 2.0.  Commenting to bump the issue. (@jbphet)

**Comment by jbphet** [comment]
The hosting of dev versions has been transferred from spot to bayes, and I just did a quick looks that the ownership and groups for files there, and it looks reasonable.  Nothing left to do here, closing.
