### ISSUE TITLE
Refining the latest links for phet-io

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#100]
@jonathanolson, @zepumph, and I discussed the possibility of changing the `/latest` links for phet-io to instead be `/latest/{{major.minor}}`.  The reasoning is this will allow clients to automatically pick up non-breaking maintenance releases, but avoid potentially api-breaking minor/major releases.

Here is an example of how the redirect structure would look in the .htaccess file:
```
RewriteEngine on
RewriteBase /sims/chains/
RewriteRule latest/1.17(.*) 1.17.0$1
RewriteRule latest/1.16(.*) 1.16.4$1
```
Here, the link `/sims/chains/latest/1.17` redirects to `/sims/chains/1.17.0` and `/sims/chains/latest/1.16` redirects to `/sims/chains/1.16.4`.

This will be difficult to manage using our current process, where the .htaccess file is recreated on every production deploy based on the current version being deployed.  We discussed three possible solutions.

1. The build-server scans the directory structure on every production deploy, determines all of the latest maintenance releases based on a parsing of the file system, and writes a new .htaccess file.
2. The build server edits the .htaccess file in place, using string parsing to determine if a line needs to be changed or a new line added.
3. We add a database backend to the build server which maintains a record of all phet-io deploys.  On a production deploy, the build-server queries the database of all latest minor versions and rewrites the .htaccess from scratch.

(3) is probably the most robust and scalable solution, but would require some time to figure out how to integrate a db.

**Comment by zepumph** [comment]
Well documented @mattpen, thanks! I would like to add that option (3) above, the database, could be used in other places and its robustness extends to future tasks we may need to accomplish. For example, an api call to this database would replace @jonathanolson's manually maintained maintenance release json in perennial. I definitely think it would be time well spent, (coming from the guy that wouldn't probably work on it).

No matter what approach we take. Adding this "latest" link system will be very valuable to the robustness of phet-io longterm. I look forward to when we can deliver a link to a client that will automatically "update" as we make maintenance releases. 

We think it is important to get @samreid's opinion on this topic, as well as have @ariel-phet and @kathy-phet in on the conversation and to provide guidance on the priority of such work.

**Comment by zepumph** [comment]
@mattpen perhaps it would be helpful to give a time estimate on how much work it would be to create the database as apposed to the other, more specified, solutions.

**Comment by ariel-phet** [comment]
Marking for developer meeting as I would like to make sure I fully understand the issue

**Comment by samreid** [comment]
I agree we should implement a latest minor version, not sure the best way to do so.

**Comment by mattpen** [comment]
@dev-meeting we decided (3) is probably the best way to go.  I'll create a new issue to discuss requirements for a phet-io sim information database.

**Comment by samreid** [comment]
Maybe other possibilities?

/sims/chains/latest/1.17
/sims/chains/1.17/latest
/sims/chains/1.17

**Comment by samreid** [comment]
@kathy-phet said `/sims/chains/1.17` seems reasonable. @samreid pointed out that the landing page will be at the root (moved from /wrappers/index/index.html to /index.html).  @jonathanolson pointed out that the maintenance release process would need to know that new relative path.

**Comment by samreid** [comment]
@mattpen said `/sims/chains/1.17` will not be more technically difficult than the other paths with `latest`.

**Comment by samreid** [comment]
@mattpen got the go-ahead to add phet-io info to the database.

**Comment by mattpen** [comment]
I'll track the database work in phetsims/phet-io#1344.  When that is complete I'll use this issue to track changes to the htaccess rules.

**Comment by mattpen** [comment]
@zepumph @samreid - I believe this should be ready for primetime.  I just redeployed chains in production and the minor redirects seem to be working as designed. (I only deployed 1.17 and the links were generated for all major/minor versions).

See:
https://phet-io.colorado.edu/sims/chains/1.16/chains_all_phet-io.html?phetioStandalone
https://phet-io.colorado.edu/sims/chains/1.17/chains_all_phet-io.html?phetioStandalone
https://phet-io.colorado.edu/sims/chains/1.16/wrappers/index/index.html
https://phet-io.colorado.edu/sims/chains/1.17/wrappers/index/index.html

The links will be generated for the remaining sims the next time they have production deploys.  Do we need to generate the links sooner?

**Comment by zepumph** [comment]
>The links will be generated for the remaining sims the next time they have production deploys. Do we need to generate the links sooner?

My vote is "no, but we will let you know if that changes"

Am I right in assuming that if we published any maintenance release for phet-io without changing content (just updating the maintenance number), this would update all latest links for that simulation.

**Comment by mattpen** [comment]
@zepumph said 
> Am I right in assuming that if we published any maintenance release for phet-io without changing content (just updating the maintenance number), this would update all latest links for that simulation.

In theory yes.  This will allow all links to be set on the next maintenance deploy.  After that the only link that should change will the the version being deployed.

**Comment by samreid** [comment]
> My vote is "no, but we will let you know if that changes"

That sounds good to me.  

In testing this, I observed that:
https://phet-io.colorado.edu/sims/chains/1.17/wrappers/index/index.html
links to
https://phet-io.colorado.edu/sims/chains/1.17.11/chains_all_phet-io.html?phetioStandalone

Is that as desired?  Or should that latter link be 1.17 instead of 1.17.11?  If we agree that the latter link should be 1.17, then how can we achieve that?

**Comment by zepumph** [comment]
That sounds messy, but I agree there is a problem here, how can we assure that clients are manually editing that link, or the link to the lib file. Perhaps we need to update the index page on production build to only point to the major/minor version. But doesn't that lock you into always getting the most recent maintenance release. I guess we probably do want to lock clients into that.

**Comment by samreid** [comment]
We would like clients by default to use the MAJOR.MINOR link, but would we allow them to use the MAJOR.MINOR.MAINTENANCE link if they need to?  That may change how we approach this.

**Comment by zepumph** [comment]
I feel like ideally clients wouldn't know anything about the maintenance release version. That would make maintainability and maintenance release client update accountability much easier. 

For the codebase, it could be potentially straightfoward to update this, although lots of testing would be needed. Marking for stable release of FL and unassigning @mattpen. Thanks for getting this off the ground. We will let you know if this touches server stuff anymore.

@samreid for example, we may just have to change this ROOT_URL:
```
      var runningOnDevSite = window.location.href.indexOf( 'https://phet-dev.colorado.edu/' ) >= 0;
      if ( isDevOrRC || ( !isDevOrRC && runningOnDevSite ) ) {
        ROOT_URL = 'https://phet-dev.colorado.edu/html/' + SIMULATION_NAME + '/' + SIMULATION_VERSION + '/phet-io/';
      }
      else {
        ROOT_URL = 'https://phet-io.colorado.edu/sims/' + SIMULATION_NAME + '/' + SIMULATION_MINOR_VERSION + '/';
      }
    }
```

**Comment by zepumph** [comment]
See https://github.com/phetsims/phet-io/issues/1352 in relation to republishing sims to get the latest links working.

**Comment by zepumph** [comment]
@samreid I'm unsure about what direction we should plan for. I see a few options:

Do we assume that whenever a client is importing phet-io.js, they are doing so with the minor release latest link, like: `<script src="https://phet-io.colorado.edu/sims/fardays-law/1.5/lib/phet-io.js"></script>`

Do we need to hard code in assumptions about production builds into Client.js, for example, the client loaded from `https://phet-io.colorado.edu/sims/fardays-law/1.5.5/lib/phet-io.js` would try to load the following sim: `https://phet-io.colorado.edu/sims/fardays-law/1.5/faradays-law_en-phetio.html`

Do we allow clients to use hard coded maintenance released versions of code?

NOTE: whatever we do we will need to make sure the index wrapper adheres to our convention.

**Comment by samreid** [comment]
It seems appealing to have all PhET-iO clients using MAJOR.MINOR in the same way that PhET brand clients just use /latest.  However, I don't know if this will be risky or if we will need clients to be able to sometimes specify MAINTENANCE.  Let's discuss this at developer meeting.

**Comment by samreid** [comment]
Some options:

1. make all URLs use MAJOR.MINOR and drop support for MAINTENANCE somehow.  This shouldn't be done for local build, dev tests, rc tests.  It is unfortunate that we may want a feature that is only testable in production.
2. check in with the developer team at large whether (1) is good before trying to build it.
3. go ahead with step (1) now then run it past the developer team later (in case they have better ideas)

It seems (2) is the safest, and Thursday is imminent.

**Comment by samreid** [comment]
For developer meeting: a summary of the problem at hand:

We would like clients to be using MAJOR.MINOR so that we can update the MAINTENANCE version without requiring them to change their URLs or wrappers.  However, this is a new deployment paradigm for us (somewhat akin to the way we use /latest on phet.colorado.edu for sims), but this would be for MAJOR.MINOR, not just for MAJOR/latest.  We think we can figure out how to do this from a technical standpoint (requires changing some paths in our wrappers and build steps), but wanted to check in with the dev team before trying to implement this.

How do you feel about this added complexity, as a way to enable us to future-proof maintainability for PhET-iO sims?  Please be aware that this feature will be on phet-io.colorado.edu only and will not apply to local build/dev/rc builds (and hence may be more complex and difficult to test).  Do you foresee any other issues with this new deployment paradigm?

**Comment by pixelzoom** [comment]
If I understand correctly, the proposal is to have the client use a URL that points to the latest MAJOR.MINOR version number, and then PhET swap in new maintenance releases as they become available.  

(1) I think that replacing what the client's URL points to is problematic.  The first time that we break something (which will happen), the client will be asking for a MAJOR.MINOR.MAINT URL.

(2) If something is broken in the wrappers, how do you proposed to fix it? 

(3) Is this something that clients have asked for? Or has anyone asked clients how they feel about it?

**Comment by jonathanolson** [comment]
> (1) I think that replacing what the client's URL points to is problematic. The first time that we break something (which will happen), the client will be asking for a MAJOR.MINOR.MAINT URL.

The alternative would presumably be an automated system that notifies all clients when a new version of something is published?

It seems way more likely that clients would not update and use the "broken" old versions (usually maintenance patches fix freshly broken behavior or make important updates). It seems that WE really don't want clients ever using an OLD maintenance release, since it may be broken, may not track correctly for statistics, etc.

It's similar to how the sims work on the website right now for "phet"-brand sims, so I'd advocate heavily for just giving clients major.minor versions (but also being able to specify major.minor.maintenance).

> Or has anyone asked clients how they feel about it?

This sounds super important. Note that the "old" version may not work in some browsers (has happened before) as the type of thing we patch.

**Comment by jonathanolson** [comment]
> Are we typically aware of when a patch drops support for browsers? If so, then we can make the judgment whether to bump that to a new MINOR version.

I haven't been aware of any maintenance patch that has dropped support for browsers, and I'd strongly advocate that we NEVER do a maintenance patch that breaks/changes browser support.

**Comment by samreid** [comment]
Meeting today:

@jonathanolson recommends clients always use latest maintenance version.
@jbphet says it may be best to require clients to use latest maintenance version.
@jonathanolson says if we break something in a maintenance release, we could immediately re-release to fix the breakage.

@jonathanolson asks how this will work for playback.  What if something moves by a pixel in 1.5.1, then playbacks from 1.5.0 wouldn't work at all.
@zepumph says you would be able to use the 1.5.1 playback wrapper to play it back and it would automatically load the 1.5.0 iframe.

@jonathanolson says one category of change doesn't impact recording.  Like changing analytics, or a crashing bug.  If we change something by a pixel, do we need to re-release from master and increment the MINOR number?

**Comment by samreid** [comment]
@zepumph says if we want to re-release, we could use similar SHAs.
@pixelzoom says the whole point of re-release is to go from master.

@jbphet says it is OK to constrain to playback on the same MAINTENANCE version the recording was on.

**Comment by samreid** [comment]
Consensus:

We would like to share MAJOR.MINOR to clients.  For loading prior version for playback, we can put together the URL from sim name + version.  We should expect that newer versions cannot be used to play back prior versions.

**Comment by samreid** [comment]
@zepumph can you please help summarize work that should be done based on this decision? Is there anything other than:

* Add something to the playback wrapper that figures out the URL from sim name + version

If that's all, perhaps that should become a new issue and we can close this issue.  Let me know your thoughts.

**Comment by zepumph** [comment]
please comment on my obnoxious essay above in https://github.com/phetsims/phet-io/issues/1355.

**Comment by zepumph** [comment]
The rest will be covered by the issues created above. @samreid anything else for this issue?

**Comment by samreid** [comment]
Looks great, thanks for organizing this.
