### ISSUE TITLE
Style for automated maintenance commands

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#101]
For automated maintenance releases, does anyone have a preference between doing things in the Node.js REPL:

```
Maintenance.createPatch( ‘vibe’, ’https://github.com/phetsims/vibe/issues/32' );
Maintenance.addPatchSHA( ‘vibe’, ‘3bf8488a8801605887d34506255cfb862cc07f77’ );
Maintenance.addNeededPatchesBefore( ‘vibe’, ‘3bf8488a8801605887d34506255cfb862cc07f77’ );
Maintenance.list();
Maintenance.applyPatches();
Maintenance.updateDependencies();
Maintenance.checkoutBranch( ‘area-builder’, ‘1.1’ );
Maintenance.addPatchSHA( ‘vibe’, ‘814e7a7b71c47ff7b9841618937a0749a16567bd’ );
Maintenance.applyPatches();
Maintenance.checkoutBranch( ‘arithmetic’, ‘1.0’ );
Maintenance.addPatchSHA( ‘vibe’, ‘743fac39ae570f58297c38e7d4c56daf8ea380ef’ );
Maintenance.applyPatches();
Maintenance.updateDependencies();
Maintenance.deployReleaseCandidates();
```

vs adding many grunt tasks:
```
grunt maintenance-create-patch --repo=vibe --message=https://github.com/phetsims/vibe/issues/32
grunt maintenance-add-patch-sha --repo=vibe --sha=3bf8488a8801605887d34506255cfb862cc07f77
grunt maintenance-add-needed-patches-before --repo=vibe --sha=3bf8488a8801605887d34506255cfb862cc07f77
grunt maintenance-list
grunt maintenance-apply-patches
grunt maintenance-update-dependencies
grunt maintenance-checkout-branch --repo=area-builder --branch=1.1
grunt maintenance-add-patch-sha --repo=vibe --sha=814e7a7b71c47ff7b9841618937a0749a16567bd
grunt maintenance-apply-patches
grunt maintenance-checkout-branch --repo=arithmetic --branch=1.0
grunt maintenance-add-patch-sha --repo=vibe --sha=743fac39ae570f58297c38e7d4c56daf8ea380ef
grunt maintenance-apply-patches
grunt maintenance-update-dependencies
grunt maintenance-deploy-release-candidates
```

There is a slight advantage to the Node REPL, as it allows doing more flexible things like this (actual example):
`Maintenance.addNeededPatchesBuildFilter( 'chipper', async ( releaseBranch, builtSim ) => buildSim.includes( 'OG_TITLE' ) );`
whereas we’d need an explosion of grunt tasks to do things precisely like that.

Tagging for dev meeting so I can get a general "recommended" path before finalizing an API before the next maintenance releases & documentation.

**Comment by samreid** [comment]
REPL looks significantly superior.  Easier to read, probably easier to debug.  Won't need to create adapter grunt tasks, etc.

**Comment by jonathanolson** [comment]
The so-far description of the firefox and google-analytics maintenance release is in https://github.com/phetsims/special-ops/blob/master/firefox-google-analytics-maintenance-example.md. It includes the majority of the console output, and it was a process anyways, so it probably won't fit in a comment.

Retagging to see if we'll go over it fully at developer meeting. Maybe block off a whole day? Maybe we can skip over it a lot?

**Comment by ariel-phet** [comment]
@jonathanolson Lets plan to do a "Cliffs notes" version at dev meeting and see where that gets us.

**Comment by jonathanolson** [comment]
The "with big things collapsed by default" version is at: https://gist.github.com/jonathanolson/9539cc6a5a4e3fd874caa405fb8ebc51

**Comment by jonathanolson** [comment]
General consensus is that the approach looks fine. For the next maintenance release, I'll probably pair with someone, and let others watch to go through the full process.

@ariel-phet does that sound good? capacitor-lab-basics (with @Denz1994) is probably next.

**Comment by ariel-phet** [comment]
@jonathanolson sounds good, I will close this issue and make a "round robin" maintenance release issue
