### ISSUE TITLE
Third party license changes for automated maintenance releases?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#106]
Whenever I deploy automated maintenance releases, it looks like it is spamming commits to https://github.com/phetsims/sherpa/commits/master. Can this step be postponed until the end of the deployments, so it is one commit?

Additionally, it looks like whether a version is reported for a sim is inconsistent in the report:

```
This report is for the following simulations:

‪Acid-Base Solutions‬ 1.2.14
‪Area Builder‬ 1.1.9
‪Area Model Algebra‬
‪Area Model Decimals‬
‪Area Model Introduction‬
‪Area Model Multiplication‬
‪Arithmetic‬ 1.0.13
```

**Comment by pixelzoom** [comment]
I recently published RPAL 1.2.0 and Molarity 1.4.0 and 1.4.1 (not automated maintenance releases).   I see a commit to third-party-license.json for for Molarity 1.4.0, but not for the other two.   What performs this commit? What went wrong?

**Comment by jonathanolson** [comment]
Hmm, it should run at the end of every production deploy (after sending the build to the server).

Maybe it errored (was an error printed? do you have console history still of the deploy)? It's also possible to CTRL-C (or equivalent) out of the deploy at this point that would interrupt it.

**Comment by pixelzoom** [comment]
I received a "Build Succeeded" email from the build server. I don't recall seeing any console error, and I no longer have console history.  And I didn't abort the build before it completed -- `grunt production` explicitly warns against that, as I recall.

**Comment by samreid** [comment]
+1 for batching sherpa commits.  Or maybe we can `git squash` them later, if it is too awkward to batch the tasks.  I don't know why some sims have no version noted.

**Comment by pixelzoom** [comment]
@samreid said:
> I don't know why some sims have no version noted.

See https://github.com/phetsims/chipper/issues/593.

**Comment by jonathanolson** [comment]
I'll modify it so it runs once a day on bayes.

**Comment by mattpen** [comment]
@jonathanolson - What is the status on this issue?

I recently had to run this manually for Graphing Quadratics to solve #118.

**Comment by jonathanolson** [comment]
Not yet implemented. Let me or @ariel-phet know if this would be a priority.

**Comment by mattpen** [comment]
Bumping this issue due to phetsims/wave-interference#339.  @ariel-phet - I'v had to run this 3-4 times manually since the chipper 2.0 release. It generally takes me an hour or two.  I could pretty easily put this in a script that runs daily on phet, which would take 3-4 hours to implement and test.

**Comment by jonathanolson** [comment]
This also came up in https://github.com/phetsims/perennial/issues/132.

**Comment by jessegreenberg** [comment]
+1 for this, I didn't run into an error but it adds a substantial amount of time to when running `Maintenance.deployProduction` in the final steps of the maintenance release process.

**Comment by ariel-phet** [comment]
It would be good to either polish off this issue or close it if it is no longer a priority.

**Comment by jonathanolson** [comment]
@zepumph handled this in https://github.com/phetsims/chipper/issues/594, closing.
