### ISSUE TITLE
Maintenance release round robin of developers

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/perennial#110]
This issue is to keep track of which developers have gone through the maintenance release process, and to track anything that comes out of using the current process in terms of suggestions/improvments

- [x] Denzell B
- [x] John B
- [x] Jesse G
- [x] Chris K
- [x] Michael K
- [ ] @pixelzoom 
- [x] Matt P
- [x] Sam R

**Comment by samreid** [comment]
To clarify a note from https://github.com/phetsims/perennial/issues/101#issuecomment-419984698, when preparing for upcoming maintenance releases, check what developers are interested in observing that round and try to schedule a time that works for all involved parties.

**Comment by Denz1994** [comment]
I'll just make the note here, that Capacitor-Lab Basics would be my candidate for testing the maintence release process.

**Comment by jonathanolson** [comment]
Lots of things came up this week on my side, had to bump the handling of the maintenance release to tomorrow (Friday).

**Comment by chrisklus** [comment]
From 9/27/18 dev meeting: @jonathanolson is going to make some improvements before the next maintenance release.

**Comment by samreid** [comment]
After the preceding comment is complete, @jonathanolson and @samreid will schedule a time to work on a maintenance release for https://github.com/phetsims/joist/issues/524

**Comment by jbphet** [comment]
In the 10/4/2018 dev meeting, @jonathanolson said that he is working on the documentation for handling the more subtle and complex issues that can arise.  Once he has that done, he'll work with @samreid on the next maintenance release.

**Comment by samreid** [comment]
@jonathanolson completed documentation and the ball is in my court to schedule an appointment for maintenance release.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery/issues/883 Was recently fixed and requires maintenance releases. There are 5 sims published with keyboard navigation support that could get this in a maintenance release. Does the tool support publishing maintenance releases to a subset of sims? If so, I may be a good next candidate for this.

**Comment by pixelzoom** [comment]
11/29/18 dev meeting:

@zepumph is next up, will pair with @jonathanolson next Thursday.  Pending maintenance release is phetsims/chipper#720 (add phetmarks to shas).

**Comment by pixelzoom** [comment]
11/29/18 dev meeting:

@zepumph is next up, will pair with @jonathanolson next Thursday.  Pending maintenance release is phetsims/chipper#720 (add phetmarks to shas).

@jessegreenberg will talk with @jonathanolson about scheduling an a11y-releated maintenance release.  This is not high priority, just a good time to do it.

@samreid asked if QA will have time for this, based on the January workload identified in today's status meeting.

Deferring maintenance releases until we talk with @ariel-phet.

**Comment by pixelzoom** [comment]
12/13/18 dev meeting: @ariel-phet instructed to defer this until after January deadlines.

**Comment by jbphet** [comment]
No longer on hold, since some of the things that were higher priority have been done.  @jessegreenberg is next up, tentatively schedule for near the end of February.

**Comment by samreid** [comment]
Heads up that https://github.com/phetsims/brand/issues/34 was proposed as an upcoming maintenance release.

**Comment by jessegreenberg** [comment]
@Denz1994 volunteered to pair with @jonathanolson for the https://github.com/phetsims/brand/issues/34 batch of maintenance releases.

**Comment by jessegreenberg** [comment]
There are a few releases that have queued up in this issue. @jonathanolson said it would be good practice to deploy more than one of these at once. So the next time we go through this process, two issues will go together.

The branding issue is higher priority than all the others and should go first. A maintenance release for others will happen later.

**Comment by pixelzoom** [comment]
2/21/19 dev meeting:
Next maintenance release is still [phetsims/brand#34](https://github.com/phetsims/brand/issues/34), @jonathanolson and @Denz1994, pending input from @kathy-phet.

**Comment by zepumph** [comment]
3/7/19

have been running into build failures and issues that have stalled out the process for @Denz1994 and @jonathanolson. They will keep working on it.

**Comment by Denz1994** [comment]
https://github.com/phetsims/brand/issues/34 has been updated with the latest progress. Currently builds not compatible with phetmarks are failing due to the .eslintrc config file.  See the trailing output of https://github.com/phetsims/brand/issues/34#issuecomment-471059848. The current proposal is to patch in the proper .eslintrc files for the failing repos with this maintenance release.

**Comment by Denz1994** [comment]
Bulk maintenance release related to https://github.com/phetsims/brand/issues/34 is now open for QA to test. See https://github.com/phetsims/QA/issues/299. Individual issues will need to be created for testing changes in sims that are in the middle of RC testing.

**Comment by mattpen** [comment]
I'm interested in scheduling a batch maintenance release for phetsims/chipper#746 / phetsims/chipper@8bb209dd4d18381ba887114adba07890595f82aa.  I can give this a try on my own, but I will probably have questions and it would be nice if @jonathanolson was around and available when I'm working on it.

This is needed for the next minor release of the iOS app (1.3).

**Comment by jbphet** [comment]
In today's dev meeting, we discussed having @mattpen lead the next one, @zepumph participate to get his training on this, and @jonathanolson will participate as a consultant.  This can start any time.

**Comment by jessegreenberg** [comment]
@mattpen said that he will proceed with one maintenance release 4/11/19. @jessegreenberg will follow up with the one mentioned in https://github.com/phetsims/perennial/issues/110#issuecomment-434386842. @ariel-phet said that we want to finish up maintenance releases before deployment of the app.

**Comment by mattpen** [comment]
The maintenance release for gzip assets is complete.  Notes from @zepumph and I are in #132.

**Comment by jessegreenberg** [comment]
OK thanks, that means I am next, I will meet with someone who is familiar with this process. I am free to do this starting after 5/1/19.

**Comment by samreid** [comment]
@jonathanolson will update documentation.  We will not track the unpublished release branches quite yet.  Then @mattpen and @jessegreenberg will work together on the next maintenance release.  There is a known issue that windows shells don't all autocomplete.

**Comment by jessegreenberg** [comment]
@jonathanolson is doing some work on the maintenance release process, and is going to test it out on a batch maintenance release for https://github.com/phetsims/chipper/issues/661.

Removing my assignment, @jonathanolson please feel free to reassign when you feel this is ready again.

**Comment by jessegreenberg** [comment]
@mattpen and I completed the batch maintenance release for https://github.com/phetsims/scenery/issues/883. It was a small set of sims but went very smoothly. For a the things we encountered we made issues in perennial.

**Comment by zepumph** [comment]
@jonathanolson mentioned today that there are one or maybe two MRs coming up. @chrisklus will tag along!

**Comment by samreid** [comment]
@chrisklus and I ran a maintenance release process for https://github.com/phetsims/query-string-machine/issues/34 99% on our own, and it went well.  Thanks to @jonathanolson for setting up this process and documenting it nicely.

**Comment by samreid** [comment]
We may have a maintenance release coming up for phetsims/phet-core#64 about iOS Full Screen

@ariel-phet suggests maybe @pixelzoom can assist, if the timing is right.  We would like to make this maintenance release before we publish the app.  But we would like to publish the app right away.  So if the app gets greenlighted, we may have @jonathanolson quickly do this.  If there is time, then @pixelzoom could help.

**Comment by pixelzoom** [comment]
It looks like the maintenance release for phetsims/phet-core#64 is already underway, and I'm not involved. So unassigning.

**Comment by Denz1994** [comment]
Discussed at dev meeting: 09/19/19

Maintenance release with @jbphet  for Tambo and Vibe coming up.

**Comment by pixelzoom** [comment]
10/17/19 dev meeting:  @jbphet and @jonathanolson are in the middle of a maintenance release.

**Comment by Denz1994** [comment]
As discussed in dev meeting on 12/05/19:

We will return to maintenance releases after more high priority tasks are handled (app work, website, etc).

**Comment by pixelzoom** [comment]
12/19/19 dev meeting:

I'm the only one left, so assigning to me.

**Comment by pixelzoom** [comment]
@ariel-phet Now that this issue is assigned to only me, I'm wondering...  How am I going to know when a maintenance release is happening, and how is someone who is doing a maintenance release going to know that it might be time to involve me?   Would it be better to assign this issue to whoever is responsible for schedule maintenance releases?

**Comment by pixelzoom** [comment]
Self unassigning until I get feedback on https://github.com/phetsims/perennial/issues/110#issuecomment-570679436.

**Comment by ariel-phet** [comment]
@pixelzoom I think we will just close this issue. I should generally be in the loop with any maintenance releases, as we are attempting to be judicious about such things with regards to the app. Enough people have been through the process now and there has been enough knowledge sharing that I don't think it is critical for you to participate soon. Basically, we wanted to make sure that if something comes up when someone like JO is unavailable, we are still able to handle it, even if it is a bit slower than normal. When the next main one comes up, I will try to remember it would be good to have you ride alone :).

**Comment by pixelzoom** [comment]
Sounds good, thanks.
