### ISSUE TITLE
Sim Version parsing logic is copied all over the project

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#111]
Currently there are 3 repos taking in a version as a string and parsing it:

* joist's `SimVersion.parse()` with the following regex: 
 `      var matches = versionString.match( /(\d+)\.(\d+)\.(\d+)(-(.+))?/ );`

* perennial's `SimVersion.parse()` with the following regex: 
`       const matches = versionString.match( /^(\d+)\.(\d+)\.(\d+)(-(([^\.-]+)\.(\d+)))?(-([^.-]+))?$/ );`

* in chipper @samreid @chrisklus and @zepumph just copied manually perennial's regex into `CopySupplementalPhETIOFiles` to support https://github.com/phetsims/phet-io-wrappers/issues/163

All three of these repos seem to be incapable of using the other repos' types/code. As a result there is a lot of copying of complicated logic that is likely going to change in the future. 

Note that the phet-io metadata database that @mattpen just wrote also uses the perennial version parsing.

It is also worthy of note that the regex in joist seems outdated, but maybe it's ok for its purposes.

**Comment by samreid** [comment]
Promoting @jonathanolson's comments to top-level so I can upvote it:

> copy-paste might make sense
we should have perennial/chipper be pretty separate
Joist’s SimVersion could be moved to Chipper (so it could be used by browser and node.js code at the same time)

**Comment by pixelzoom** [comment]
See also https://github.com/phetsims/joist/issues/411 (clean up version identifier).

**Comment by mattpen** [comment]
@zepumph will look into merging the joist handling into chipper.  chipper and perennial cannot be combined.  The perennial version is the latest and greatest version as of today.

**Comment by zepumph** [comment]
This will involve using Perennial's parser as the "definition" of the version, as well as creating/updating the chipper version to work in requirejs mode and the build process. Then it will be a preload in sims.

**Comment by samreid** [comment]
Thanks for volunteering to work on this, @zepumph.  I'm wondering if it's possible to have an exact file copy that works in both perennial and chipper?  Maybe that would help us synchronize them in the long run?

**Comment by jonathanolson** [comment]
> I'm wondering if it's possible to have an exact file copy that works in both perennial and chipper?

May be possible, but right now the perennial file uses node.js assert, and how would we keep them from getting out-of-sync?

**Comment by zepumph** [comment]
>how would we keep them from getting out-of-sync?

microprocess that copy pastes perennial into chipper and commit/pushes? Sounds dangerous

**Comment by samreid** [comment]
> microprocess that copy pastes perennial into chipper and commit/pushes? 

Schedule a slack text for every 3 months that reminds us to check if they differ?

**Comment by zepumph** [comment]
I went ahead with trying to consolidate SimVersion logic. Here is a summary of the work done in the above commits:
* Alter PERENNIAL/SimVersion to support running from node or the browser, this involved passing through an assert object that is different for both modes, and supporting `assert && . . .`
* Copying that file directly to Chipper
* Making the chipper one a preload, updating build.json as well as all development html files in the project (note that html files were updated with grunt update, so this should cover test files etc.).
* Make UpdateCheck.js use the preload instead of JOIST's
* Delete JOIST/SimVersion
* Add logic to daily-grunt-work.sh to copy this file to chipper and commit if different. This runs every night. 
* Add documentation to SimVersion to mention that chipper's is auto generated, and that it shouldn't be touched.

@samreid would you please review.

I would recommend looking at changes in the following files:
* perennial/js/common/SimVersion.js
* chipper/js/SimVersion.js
* joist/js/UpdateCheck.js
* chipper/build.json
* perennial/bin/daily-grunt-work.sh
* Spot check a few html files to make sure the SimVersion.js preload is in the right spot.

**Comment by samreid** [comment]
@pixelzoom pointed out that this message prints out even for unpublished sims:

> Update check failure: simulation vector-addition not found

**Comment by pixelzoom** [comment]
`chipper.SimVersion` has no `isSimNotPublished` field.  So this `if` expression in `joist.UpdateCheck` is never true, and all sims are treated as published. 


```js
      // If our sim's version indicates it hasn't been published, don't attempt to send a request for now
      if ( this.ourVersion.isSimNotPublished ) {
        self.stateProperty.value = 'up-to-date';
        return;
      }
```

**Comment by pixelzoom** [comment]
Why are there identical copies of `SimVersion` in chipper and perennial? 

I'm also wondering why the `if` expression in `UpdateCheck` is:

`if ( this.ourVersion.isSimNotPublished ) {`

In joist.SimVersion, `isSimNotPublished` was a method, not a field.  And it's being used as a field in `UpdateCheck`. From https://github.com/phetsims/joist/commit/18e6b6a9dcd86451312f7e57477ca67a03b0e81d#diff-f59e3d86af84cfb04169731a1c2059a4:

```js
    /**
      * @returns {boolean|*}
      * @public
      */
     get isSimNotPublished() {
       return this.major < 1 || // e.g. 0.0.0-dev.1
              ( this.major === 1 && // e.g. 1.0.0-dev.1
                this.minor === 0 &&
                this.maintenance === 0 &&
                this.suffix );
     },
```

**Comment by pixelzoom** [comment]
So `isSimNotPublished` is missing from chipper.SimVersion.  Anything else that got dropped?

**Comment by zepumph** [comment]
@pixelzoom the commits titled "bug fix by adding `SimVersion.isSimNotPublished`" fixed the issue you were describing above.

Honestly I'm quite sorry about the sloppy execution of this issue. I spent more time on the mechanics of having 1 SimVersion file than I did on making sure their APIs were compatible.

I went through all of the usages of `SimVersion` in joist (only used in `updateCheck.js`), and I made sure that isSimNotPublished was the only piece that was missing. All other methods were not used. I also made sure that the `toString` and `parse` methods looked compatible. 

Through my investigation into the update check singleton, I created https://github.com/phetsims/joist/issues/578 to bring it up to better code standards. @pixelzoom please ignore the previous 3 commits, as they apply to refactoring over in https://github.com/phetsims/joist/issues/578.

>Why are there identical copies of SimVersion in chipper and perennial?

This was a solution that was discussed to make sure there is only one editable copy of the file, from the top of the doc:

```
 **************************************************************
 * IMPORTANT NOTE: This file is copied from PERENNIAL to CHIPPER frequently. If this is in CHIPPER, then it is AUTO
 * GENERATED; do not edit, as it will be overwritten. Make sure that any change here is supported by usages of
 * CHIPPER's SimVersion (i.e. in JOIST/updateCheck.js), see https://github.com/phetsims/perennial/issues/111 for more
 **************************************************************
 ```

@pixelzoom I think it is preferable for you to review from here since you asked good questions above.

**Comment by zepumph** [comment]
I won't remove the blocks publication label until it has been looked at.

**Comment by pixelzoom** [comment]
Changes looks good.  But I'm still curious about `isSimNotPublished`.  It's a function, but I don't see it called anywhere in PhET code.  In `updateCheck`, it's not being called, it's testing to see if it exists:

`if ( this.ourVersion.isSimNotPublished ) {`

Doesn't that seem incorrect?

**Comment by zepumph** [comment]
It is a getter, would you rather me change it to a function so that it makes more sense?

**Comment by pixelzoom** [comment]
Oh duh, I see.  No, fine to leave as is.   

Removing 'block publication' label.

**Comment by zepumph** [comment]
@pixelzoom I'm not totally clear on if you reviewed the bug fix, or the entire changeset for this issue. 

If you have reviewed everything and feel like all is good, I think we can close.

If you only reviewed the bug fix. Can you review the whole issue? If that is too much, please assign over to @jonathanolson for the review (for the same reason as mentioned in https://github.com/phetsims/joist/issues/578#issuecomment-536723207)

**Comment by zepumph** [comment]
Oops, assigning over to @pixelzoom, sorry for the delay.

**Comment by pixelzoom** [comment]
I don't see any other problems. But I also wasn't involved in implementation of SimVersion, and I'm not familiar with all of the places that it's used.  So @zepumph I'll leave it up to you -- if you think there's a reason for @jonathanolson to have a look, assign to him. Otherwise feel free to close.

**Comment by zepumph** [comment]
@jonathanolson could you give this change set a spot check before close. Here are the main changes/takeaways:

* SimVersion rewritten to be use UMD
* One writeable SimVersion in Perennial (`PERENNIAL/SimVersion`)
* Copied to chipper automatically every night (`daily-grunt-work.sh` and `CHIPPER/SimVersion`)
* `CHIPPER/SimVersion` is a preload for all sims (`build.json`)
* Perennial's `SimVersion` updated to support `UpdateCheck` usages.

Anything sound problematic about that algorithm? Do you see anything strange poking around?

**Comment by zepumph** [comment]
@jonathanolson noticed that daily-grunt-work was fighting against itself here. The SimVersion being copied from perennial each night had an incorrect copyright date. I updated the SimVersion section of the script to also update copyright dates. @jonathanolson please add the above commit to the list to review for this issue.

**Comment by zepumph** [comment]
Lots of work has been done to SimVersion since this issue 3 years ago, including work on importing it for multiple runtimes. Given that @pixelzoom already gave a review to this, and that I just looked through the commits again, I think @jonathanolson's time would be better spend reviewing more important issues. Closing
