### ISSUE TITLE
Outputting the appropriate links for PhET-iO RCs

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#114]
From https://github.com/phetsims/molarity/issues/53

Older PhET-iO simulations have the wrapper index in sim/version/wrappers/index.  Newer PhET-iO simulations have wrapper index in sim/version/.  How can the maintenance release process know which to generate?  Or should it generate both?  Tagging for discussion in https://github.com/phetsims/special-ops/issues/122

**Comment by samreid** [comment]
@jonathanolson pointed out that perennial/js/common/ModifiedBranch.js is responsible for tracking status of each simulation version (and its SHAs) and we can use that to create correct URLs.

**Comment by samreid** [comment]
Is it naive for me to hope that we won't have too many more maintenance releases for PhET-iO before we start republishing PhET-iO sims with the reworked studio and wrapper index link?  The best case scenario is that perennial would just need to know how to publish the new style.

The relevant code in Perennial is:

https://github.com/phetsims/perennial/blob/a3abe5764f1589fde8dc747dc6ef302308c3601e/js/common/ModifiedBranch.js#L238-L255

For future releases of PhET-iO (starting with our next release), the RC and Production Link suffixes should end with:

```
${this.repo}/${versionString}${phetioFolder}/
```

We should discuss the above points briefly at an upcoming PhET-iO meeting.

**Comment by chrisklus** [comment]
From 08/29/19 phet-io meeting: @samreid is going investigate

**Comment by samreid** [comment]
@jonathanolson changed the paths in https://github.com/phetsims/perennial/commit/a31a1e78b792b6846016abcf78f70ebe24ff8989, @jonathanolson can this issue be closed?

**Comment by jonathanolson** [comment]
Yes, this seems to be working as desired. Closing.
