### ISSUE TITLE
Add an `every-repo` list?

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#116]
From https://github.com/phetsims/phet-info/issues/85#issuecomment-439469039 it looks like `active-repos` is not actually every repo. I think we should create a general list that actually lists every repo in phetsims. This may be useful for things other than just github labels? No matter it seems strange for github-labels to have and maintain its own list. Why wouldn't we just centralize that logic with the rest of the data lists.

Also note that `special-ops` is not in active-repos too, I'm not sure how many others there are like that.

**Comment by samreid** [comment]
Note: this means that special-ops doesn't have some labels it should have, like "status:blocks-publication"

**Comment by jonathanolson** [comment]
Sounds fine to me.

**Comment by mattpen** [comment]
Alternatively, we could use this API wherever a list of _literally every_ repo under phetsims is needed: https://developer.github.com/v3/repos/#list-organization-repositories.  This would remove the manual maintenance of a file like this.

**Comment by pixelzoom** [comment]
I prefer @mattpen's suggestion.  But if you want to create yet-another data file, I'm OK with that, as long as I never need to manually edit it.

**Comment by zepumph** [comment]
I think this is a consensus. @mattpen can you update the github labels script to use this api instead of looking at a list.
