### ISSUE TITLE
Investigate missing libraries

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#118]
The third party libraries are missing from https://phet.colorado.edu/en/simulation/graphing-quadratics and graphing-quadratics is missing from https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md#graphing-quadratics.

Assigning to myself to investigate and correct.

**Comment by mattpen** [comment]
@pixelzoom - It looks like reportThirdParty.js should have run in the grunt task on your machine when you deployed graphing-quadratics to production last Friday.  Do you remember if it ran this task and if so was there any error?

**Comment by pixelzoom** [comment]
I was admittedly multitasking. But I don't recall seeing any message about reportThirdParty.js or errors when running `grunt production --brands=phet --branch=1.0`.  And I received an email indicating that the build had succeeded.

Why is reportThirdParty.js generated locally? Why isn't it handled by the build server?

**Comment by mattpen** [comment]
I ran reportThirdParty.js manually and GQ has been added to the appropriate places.

> Why isn't it handled by the build server?

In #106 we decided to add it as a scheduled service on bayes.
