### ISSUE TITLE
Support for the maintenance release process

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#12]
Adding helpful scripts and documentation for the maintenance release process (testing with https://github.com/phetsims/chipper/issues/429).

**Comment by jonathanolson** [comment]
Due to build-server failures (https://github.com/phetsims/perennial/issues/14), I'll need to deploy a good amount of the RCs.

They've already had their versions auto-bumped, so checkout/grunt/grunt deploy-rc should be all that is needed.

**Comment by jonathanolson** [comment]
Initial documentation (with steps) at https://github.com/phetsims/phet-info/blob/master/maintenance-release-process.md

**Comment by ariel-phet** [comment]
Adding dev meeting tag (I would like to make sure we have all looked over the process doc)

**Comment by pixelzoom** [comment]
I haven't had time to read through the documentation, will take me 15-30 minutes to review properly.

**Comment by jonathanolson** [comment]
@ariel-phet, I'd be fine with only having one developer more thoroughly review the documentation and code.

I can briefly describe the general operation during the developer meeting it desired.

**Comment by ariel-phet** [comment]
@jonathanolson OK, then please make the "briefly describe" part of developer meeting.

**Comment by jonathanolson** [comment]
https://github.com/phetsims/phetcommon/network may also help explain, noting for tomorrow.

**Comment by samreid** [comment]
We will discuss this with @ariel-phet on Thursday.  In particular, choosing a developer to review this documentation and related grunt tasks, and setting priority levels, etc.

**Comment by pixelzoom** [comment]
@jonathanolson noted that all code is currently in perennial.

**Comment by ariel-phet** [comment]
Are we in good shape here?

**Comment by jonathanolson** [comment]
I've walked through the process with @jbphet, but I don't believe it's been code reviewed. I'll plan to use this for https://github.com/phetsims/chipper/issues/50.

**Comment by samreid** [comment]
@andrewadare and I took this for a test drive yesterday.  We added step 0 to the instructions and ran into one problem where lint was failing on one of the steps (not the final step) that we couldn't figure out.  We'll be running the process again today or within the next few days, so we'll report back if it happens again.

**Comment by jonathanolson** [comment]
Presumably we'll need to coordinate then, so we don't both try to run maintenance releases for the same sims at the same time!

**Comment by jbphet** [comment]
This issue has been languishing for a while.  I've done several maintenance releases using this process, and it wasn't easy, but it ultimately worked.  @jonathanolson has also done some.

@jonathanolson - is a code review still needed on this, or is it safe to close?

**Comment by jonathanolson** [comment]
Probably safe to close. We'll presumably code-review after build changes later this year.
