### ISSUE TITLE
'grunt create-sim' is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#120]
This was reported on in the Google Group by Rhys Lutsky, see https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/qOeVMo-OJKg.

Following the steps in the "Create a New Sim" section of the [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit#bookmark=id.m3y45bokim89):

> 1. Check out the template sim, called ‘simula-rasa’ using this git clone command:
> 
> cd phetsims
> git clone https://github.com/phetsims/simula-rasa.git
> 
> 2. Install the perennial dependencies:
> 
> cd perennial
> npm install
>
> 3. Use the perennial ‘grunt’ task to create a new sim, like so (still in the perennial directory):
> 
> grunt create-sim --repo=NAME --author=AUTHOR  

Rhys reports that step 3 fails with:

```js
I get fatal errors when I try to create a new sim in VS Code...HELP  trying to use this for a coding project: 

$ grunt create-sim --repo=mySim --author="Rhys"
warn: No build-local.json detected!
Running "create-sim" task
Greetings Rhys!
creating sim with repository name mySim
WARNING:../mySim already exists, overwriting
wrote ../mySim/.gitignore
wrote ../mySim/doc/implementation-notes.md
wrote ../mySim/doc/model.md
wrote ../mySim/Gruntfile.js
wrote ../mySim/images/license.json
wrote ../mySim/js/mySim/model/MysimModel.js
wrote ../mySim/js/mySim/MysimScreen.js
wrote ../mySim/js/mySim/view/MysimScreenView.js
wrote ../mySim/js/mySim-config.js
wrote ../mySim/js/mySim-main.js
wrote ../mySim/js/mysim.js
wrote ../mySim/LICENSE
wrote ../mySim/package.json
wrote ../mySim/mySim-strings_en.json
wrote ../mySim/mySim_en.html
info: npm update on mySim
Fatal error: Perennial task failed:
Error: grunt.cmd unpublished-README in ../mySim failed with exit code 3 and stdout:
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'grunt'
Warning: Task "unpublished-README" not found. Use --force to continue.

Aborted due to warnings.

  at ChildProcess.process.on.code (C:\Users\Rhys\CODE\Indiv\phetsims\perennial\js\common\execute.js:72:17)
  at ChildProcess.emit (events.js:182:13)
  at ChildProcess.EventEmitter.emit (domain.js:442:20)
  at maybeClose (internal/child_process.js:962:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

Full Error details:
{
  "cmd": "grunt.cmd",
  "args": [
    "unpublished-README"
  ],
  "cwd": "../mySim",
  "stdout": "Loading \"Gruntfile.js\" tasks...ERROR\n>> Error: Cannot find module 'grunt'\nWarning: Task \"unpublished-README\" not
found.\u0007 Use --force to continue.\n\nAborted due to warnings.\n",
  "stderr": "",
  "code": 3
}
```

Here's what I tried in my working copy.  A different failure, but still broken.

```
% cd ../perennial/
% rm -rf node_modules/
% npm install
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN deprecated mimelib@0.2.14: This module is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> fsevents@1.2.4 install /Users/cmalley/PhET/GitHub/perennial/node_modules/fsevents
> node install

[fsevents] Success: "/Users/cmalley/PhET/GitHub/perennial/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 509 packages from 348 contributors and audited 1649 packages in 20.203s
found 8 vulnerabilities (2 low, 6 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
% grunt create-sim --repo=foo --author="CM"
Running "create-sim" task
Greetings CM!
creating sim with repository name foo
wrote ../foo/.gitignore
wrote ../foo/Gruntfile.js
wrote ../foo/LICENSE
wrote ../foo/doc/implementation-notes.md
wrote ../foo/doc/model.md
wrote ../foo/images/license.json
wrote ../foo/js/foo/FooScreen.js
wrote ../foo/js/foo/model/FooModel.js
wrote ../foo/js/foo/view/FooScreenView.js
wrote ../foo/js/foo-config.js
wrote ../foo/js/foo-main.js
wrote ../foo/js/foo.js
wrote ../foo/package.json
wrote ../foo/foo-strings_en.json
wrote ../foo/foo_en.html
info: npm update on foo
Fatal error: Perennial task failed:
Error: grunt generate-config in ../foo failed with exit code 1 and stdout:
Running "generate-config" task
Fatal error: error executing binary "git": Error: git log --diff-filter=A --follow --date=short --format=%cd -1 -- js/foo-config.js in ../foo failed with exit code 128 and stdout:


  at ChildProcess.process.on.code (/Users/cmalley/PhET/GitHub/perennial/js/common/execute.js:72:17)
  at emitTwo (events.js:126:13)
  at ChildProcess.emit (events.js:214:7)
  at maybeClose (internal/child_process.js:925:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Full Error details:
{
  "cmd": "grunt",
  "args": [
    "generate-config"
  ],
  "cwd": "../foo",
  "stdout": "Running \"generate-config\" task\nFatal error: error executing binary \"git\": Error: git log --diff-filter=A --follow --date=short --format=%cd -1 -- js/foo-config.js in ../foo failed with exit code 128 and stdout:\n\u0007\n",
  "stderr": "",
  "code": 1
}
```

**Comment by pixelzoom** [comment]
@jonathanolson Could you take a look at this please, since you're most familiar with perennial? High priority, since this problem is public facing.

**Comment by pixelzoom** [comment]
On Slack, @jonathanolson said:
> Looking, may be needing to npm install in chipper

That's not the problem.  Example:

```
% cd chipper
% rm -rf node_modules
% npm install
% cd perennial
% rm -rf node_modules
% npm install
% grunt create-sim --repo=foo --author="CM"
```

... results in the identical failure that I experienced and reported in https://github.com/phetsims/perennial/issues/120#issue-397933943:

> Running "generate-config" task
Fatal error: error executing binary "git": Error: git log --diff-filter=A --follow --date=short --format=%cd -1 -- js/foo-config.js in ../foo failed with exit code 128 and stdout:

**Comment by pixelzoom** [comment]
@samreid identified the problem with this line in generateConfig.js, add by @jonathanolson on 

`71   await updateCopyrightDate( repo, relativeFile );`

`updateCopyrightDate` uses gitlog, and the new sim doesn't have a git repo at this point.

I'm going to comment out that line until @jonathanolson has a chance to fix and test.

Slack discussion:

Chris Malley [8:58 AM]
`grunt create-sim` was reported broken 5 days ago, see https://github.com/phetsims/perennial/issues/120.  This was reported by a Google Group member, and it’s blocking progress on his “coding project”, so I’d like to be responsive.  Does this ring a bell? Any recent chipper changes that may have broken this? (edited) 


Sam Reid [8:59 AM]
not sure, I’ll take a quick look but don’t have much time
The problem is generateConfig line 71
`updateCopyrightDate` uses git log.  The new directory doesn’t have a git repo yet.

**Comment by pixelzoom** [comment]
After commenting out the problem line in generateConfig.js, `grunt create-sim` succeeds.  I'm not sure why  `updateCopyrightDate`, because the copyrights in the .js files even look correct. 

I'll notify Rhys that this is fixed.

@jonathanolson please decide whether the `updateCopyrightDate` can be remove or needs to be done via a different means.

**Comment by chrisklus** [comment]
Can I comment out `const updateCopyrightDate = require( './updateCopyrightDate' );` so lint-everything passes?,

**Comment by samreid** [comment]
> Can I comment out `const updateCopyrightDate = require( './updateCopyrightDate' );` so lint-everything passes?

I have done so, please pull.

**Comment by zepumph** [comment]
This was fixed (or will be) as part of https://github.com/phetsims/chipper/issues/763
