### ISSUE TITLE
'grunt checkout-release' doesn't work as advertised

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#122]
The latest release branch for graphing-lines is 1.3, and `grunt checkout-release` is giving me the 1.2 branch.   So `grunt --help` and doc in checkoutRelease.js are apparently incorrect.  I suspect it's actually something like "the release branch for the latest production release".

```
% grunt --help
...
checkout-release  Check out the latest release branch for a    
                                  simulation and all of its declared           
                                  dependencies  
...
```

[checkoutRelease.js](https://github.com/phetsims/perennial/blob/153fa7537067dcb24f5b0fe59c04d3c745aa9b85/js/common/checkoutRelease.js):

```js
4  * Checks out the latest release branch (and dependencies) for a repository.

18 Checks out the latest release branch (and dependencies) for a repository.
```

**Comment by jonathanolson** [comment]
Sorry about that. I think our terminology changed a bit, as now "release branch" includes unpublished (RC) branches.

Does the above fix look good?

**Comment by pixelzoom** [comment]
👍 Closing.
