### ISSUE TITLE
problem with computing binDir in bash scripts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#128]
Reported by @phet-steele and @arouinfar.

```
% cd perennial/bin/
/Users/cmalley/PhET/GitHub/perennial/bin
% ./clone-missing-repos.sh 
./clone-missing-repos.sh: line 17: ./print-missing-repos.sh: No such file or directory
```

**Comment by pixelzoom** [comment]
We determine the directory where the script lives like this:

`binDir=`dirname "${BASH_SOURCE[0]}"`

But with `./clone-missing-repos.sh`, binDir is `.`, not the full path to `perennial/bin`. 

This should be:

`binDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"`

This problem occurs in 13 scripts in `perennial/bin/`.

Options:

(1) Leave as is and don't support `./something.sh`.

(2) Fix all 13 occurrences.

**Comment by pixelzoom** [comment]
Fixing all 13 scripts should be pretty quick, but you never know.  Each one should be tested.  And I don't have time to dive into this.  Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@mattpen said he is willing to tackle this one. This is an issue, but it is not breaking anything for anyone, just something that would be good to fix. Marked low-priority. Feel free to assign this back to me if it turns out to be difficult/rat hole

**Comment by mattpen** [comment]
This should be fixed. I tested all scripts for basic functionality using `./{{SCRIPT_NAME}}` and `perennial/bin/{{SCRIPT_NAME}}`.  Everything seems to be working fine.
