### ISSUE TITLE
create a grunt task to print deliverable phet-io links

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#131]
@kathy-phet from time to time asks us for a "master list" of all links, we should make a grunt task instead of manually doing this each time.

**Comment by zepumph** [comment]
The commit here is nice, but it may spit out more than one version per sim. Next let's only provide the "largest" version.

**Comment by zepumph** [comment]
Alright, now the task only prints out the latest sim version.

@samreid  will you please review. I went with the "map" implementation to isolate the latest version. Feel free to simplify and change as you desire.

Also thanks @jonathanolson for getting us going today with this.

**Comment by zepumph** [comment]
It should be noted that this currently doesn't support the "latest" feature, and that should be built into this so that the list delivered to clients will include versions that automatically increment to the latest.

**Comment by samreid** [comment]
I tested `grunt print-phet-io-links` and the results looked reasonable.  Some comments:

In this code:

```js
/**
 * See SimVersion.compareNumber()
 * @param {string} version1
 * @param {string} version2
 * @returns {number}
 */
const compareVersionNumber = ( version1, version2 ) => {
  if ( version1.versionMajor < version2.versionMajor ) { return -1; }
  if ( version1.versionMajor > version2.versionMajor ) { return 1; }
  if ( version1.versionMinor < version2.versionMinor ) { return -1; }
  if ( version1.versionMinor > version2.versionMinor ) { return 1; }
  if ( version1.versionMaintenance < version2.versionMaintenance ) { return -1; }
  if ( version1.versionMaintenance > version2.versionMaintenance ) { return 1; }
  return 0; // equal
};
```

The arguments are documented as `string` but also have `versionMajor` attributes, so they may not be strings.  Can we actually use `SimVersion` instances here?

Also, I see a few usages of `for..of` but I see this is restricted by our lint rule:

```js
    // Prohibit for...of statements
    'no-restricted-syntax': [
      2,
      {
        selector: 'ForOfStatement',
        message: 'Babel transpiles for...of to use Symbol which is not supported on all our platforms.'
      }
    ],
```

How is this passing lint?  But I should note it is marked up in the IDE:

![image](https://user-images.githubusercontent.com/679486/87356871-19c22280-c520-11ea-9782-86c75207279f.png)

**Comment by zepumph** [comment]
>Also, I see a few usages of for..of but I see this is restricted by our lint rule:

You are look at our base, default set of lint rules, but there is a special set of rules that apply just to node code. for-of loops are only problematic in the browser, thus, see how we turn them on in `node_eslintrc.js`:


`    'no-restricted-syntax': [ 'off', 'ForOfStatement' ],`



>How is this passing lint? But I should note it is marked up in the IDE:

This passes lint because perennial's package declares that the whole repo uses the node set of rules. The markup in your IDE may have to do with out-of date eslint setting in your IDE. Do you see how I have "automatic search" for my config file. That will use the each repo's package.json as the base eslint declaration. This way you have more granularity in a tree-like way. Each directory can specify its own custom eslintrc or override defaults. Please update that setting in your IDE and see if that fixes things.

>It should be noted that this currently doesn't support the "latest" feature, and that should be built into this so that the list delivered to clients will include versions that automatically increment to the latest.

It seems important that this works with the "latest" feature. I will look into that next.

**Comment by zepumph** [comment]
>It should be noted that this currently doesn't support the "latest" feature, and that should be built into this so that the list delivered to clients will include versions that automatically increment to the latest.

I think I confused myself. This seems to be working as expected. The "latest" feature is where you automatically get the latest maintenance number. This seems to be working as expected. Without posting the list here, I will just say that all version are only the `major.minor`. 

Over to @samreid to discuss the eslint stuff.

**Comment by samreid** [comment]
Thanks, the changes look good and the lint makes sense.  For this code:

```js
  const allSimsData = await simPhetioMetadata( {
    active: true,
    latest: true
  } );

  const filtered = allSimsData.filter( simData => simData.active && simData.latest );
```

Can you please add a code comment explaining why `active` and `latest` have to be specified to both `simPhetioMetadata` and the `filter`?

Also, I'm wondering if this code would read simpler if it was written using `_.maxBy`, is that an option?

```js
  // store only the latest version per sim in this map
  const oneVersionPerSimMap = {};

  // go through all versions and assign it to the map if it is a "later version" that that which is currently stored.
  for ( const simData of filtered ) {
    const simName = simData.name;
    oneVersionPerSimMap[ simName ] = oneVersionPerSimMap[ simName ] || simData;
    if ( compareVersionNumber( oneVersionPerSimMap[ simName ], simData ) < 0 ) {
      oneVersionPerSimMap[ simName ] = simData;
    }
  }
```

**Comment by zepumph** [comment]
Thanks for two suave comments. The above commit gets the same job done with a lot less code. Closing. Please reopen if you have anything else.
