### ISSUE TITLE
Integrate unpublished branch handling into maintenance process

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#135]
Ideally non-published release branches should be tracked somewhere, so that the automated maintenance process can detect and patch them (and notably without including them in the deployments).

Right now, there is an unclear easy-to-mess-up "ask developers on slack and look at QA issues" to determine the list of unpublished release branches. Additionally, this is handled as a second "phase" after the main maintenance work is done. (Noted in https://github.com/phetsims/perennial/issues/132)

Instead, these should be automatically processed/detected, and included in the main phase.

Tagging for developer meeting to decide on the potential approach. Possibilities are:

1. Scan branches for every simulation repository, and if it matches the `${major}.${minor}` pattern and is a newer branch than published, treat it as an unpublished release branch.
2. Register unpublished release branches somewhere (a file? the DB we use for tracking published branches?)
3. Other?

I'm leaning towards the scanning (1) approach at the moment.

**Comment by mattpen** [comment]
Could we add a step in `grunt rc` that adds the branch name to an unpublished release branch list file (something like `perennial/data/unpublished-rc`)? `grunt production` could then remove the name from that list.  The biggest problem I foresee is needing to manually remove RC branches that are abandoned and never published to production.

**Comment by mattpen** [comment]
> the DB we use for tracking published branches?

Do you mean the website postgres DB?  Currently it maintains one row per sim, not one row per release, so this would be a fairly significant change.

**Comment by pixelzoom** [comment]
5/16/19 dev meeting:

@jonathanolson prefers option (1) in https://github.com/phetsims/perennial/issues/135#issue-443494020, no objections.  @ jonathanolson will do this and integrate.

**Comment by jonathanolson** [comment]
Implemented, closing.
