### ISSUE TITLE
Great a grunt task to compare PDOM descriptions

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#137]
From a11y dev meeting today with @jessegreenberg, we were interested in prototyping around with a way to test description comparisons between two versions. We worked on a prototype today, and got to a commit point where we can compare the PDOMs on startup of working copy sim with the same from master (using `git stash`ing). This is working, but there are some pretty big todos to think about before diving fully in. Let's talk more about this @jessegreenberg!

**Comment by jessegreenberg** [comment]
github must really like this idea because it created two of these issues, this is identical to #138. Closing this one because #138 has labels and commits with references.
