### ISSUE TITLE
phet-io .htaccess rewrite loops

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#140]
In https://github.com/phetsims/phet-io/issues/1465, it was noticed that attempts to visit https://phet-io.colorado.edu/sims/phet-io-test-sim/1.1.0/ ended up showing content for the maintenance release 1.0.1.

Based on the rewrite rules (filtered for ones that don't apply):
```
RewriteRule 1.0/(.*) 1.0.1/$1
RewriteRule 1.1/(.*) 1.1.0/$1
```

It turns out that this is ignoring any prefixes in the URL, so that `1.0/(.*)` WILL actually end up matching on the url `/1.1.0/`.

Thus the sequence of rewrites was:

- `1.1/` matched the second rule, resulting in `1.1.0/`
- `1.1.0/` matched the first rule (erroneously), resulting in `1.0.1/`

Adding in carets to the rewrite rules seems to work, and should prevent this incorrect looping match behavior, so I'm changing the rewrite rules to look like:

```
RewriteRule ^1.0/(.*) 1.0.1/$1
RewriteRule ^1.1/(.*) 1.1.0/$1
```

@mattpen, can you review/verify this behavior? I'm going to spot-check this when the automated maintenance releases go live. It seems to be fully working in the phet-io-test-sim example (where I manually changed the URLs).

**Comment by jonathanolson** [comment]
Additionally, similar things seem to be possible in production, for example the following link actually loads the latest sim: https://phet.colorado.edu/sims/html/masses-and-springs-basics/somethingthatisthelatest/masses-and-springs-basics_en.html

I'll leave that for @mattpen to look into.

**Comment by jonathanolson** [comment]
Pulled build-server and restarted. Looks like the commit above is working correctly. Un-assigning myself and @chrisklus.

**Comment by zepumph** [comment]
This is blocking GQIO publication, marking as such

**Comment by mattpen** [comment]
@zepumph - It looks like @jonathanolson already deployed the fix for phet-io to production.  What about this issue is blocking GQIO?

**Comment by mattpen** [comment]
The carets look like the appropriate fix for this problem.

I've applied the fix to phet brand and deployed it to production (pulled perennial and restarted build-server on phet-server).

@zepumph, if this is no longer blocking GQIO, please close the issue.

**Comment by chrisklus** [comment]
Thanks @mattpen! Closing.

**Comment by zepumph** [comment]
@jonathanolson, I am curious about why a "^" works. I would expect for that to match the beginning of a string. Why is this better or more thorough than prefixing with a `/`? Does apache break up each path part and run it through the htaccess test? Or maybe the fact that this rewrite rule exists in the parent that holds the version folders means that a "^" applies to the path beginning with the folder with the htaccess file in it. Understanding this may help me to understand report bugs like this in the future. Please explain.

**Comment by mattpen** [comment]
These rules are preceded by a RewriteBase rule, which defines the beginning of the path.  The caret matches the beginning of the string after the rewrite base.  The rewrite base is defined as `/sims/{{sim-name}}/`.  So the slash is included in this part of the pattern rather than in the version matching.

**Comment by zepumph** [comment]
Ahh makes perfect sense. Thank you so kindly @mattpen.

**Comment by zepumph** [comment]
Nevermind :)
