### ISSUE TITLE
Create daily-grunt-work.sh and run it on bayes

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#141]
From https://github.com/phetsims/chipper/issues/763, it would be nice to have a script that runs once a day on bayes that can be run on bayes to do some of the automatic work that we don't want to have to deal with anymore.

So far we have the following items to be added to this list:
1. Third parties report in https://github.com/phetsims/chipper/issues/594
2.  updating copy right dates in https://github.com/phetsims/chipper/issues/763

**Comment by chrisklus** [comment]
@zepumph here is the comment with steps for updating copyright dates for the whole project: https://github.com/phetsims/tasks/issues/988#issuecomment-464892353.

**Comment by zepumph** [comment]
I created a script, and set it up to run every night with a cron job. Thanks @chrisklus for the steps to get started.

**Comment by zepumph** [comment]
For a bit I was thinking I would try to use pm2, and maybe to combine this with the generate-data process, but that runs continuosly, and we don't need this to run so much. I also like the idea of easily being able to add to this script and having the cron job pick it up. Furthermore, I am piping the output to a log in phet-admin's home `daily-grunt-work.log`, and will check in tomorrow to make sure things worked out.

**Comment by zepumph** [comment]
This cron job on phet-admin on bayes is working well. I checked the log at `~/daily-grunt-work.log`, which will continue to be overwritten each night when running. Things are looking very good! It worked as expected. Since the cron job pulls perennial before running the script, we can just change the script from here to add what we want. 

@jonathanolson would you please review these changes. As said above, I looked into pm2, but loop interval didn't seem like enough control for a daily run. Cron seemed like the tool for the job.

**Comment by zepumph** [comment]
This has now been running for a week, and the log still looks good to me.

**Comment by jonathanolson** [comment]
I see a mix of `npm update` (perennial) and `npm install && npm update` (chipper). I believe the ideal set of commands (and the ones that perennial usually uses) is `npm prune && npm update`.

Additionally, we'll probably want to update copyright dates in more places than active-runnables (e.g. scenery).

Otherwise, it looks good to me.

**Comment by jonathanolson** [comment]
> The list is manual right now, but I can't figure out the best way to create a list of gruntable repos. I'll keep thinking about it.

Honestly, I iterated over active-repos and ignored repos where `grunt` didn't work or do anything. Can we do that?

**Comment by zepumph** [comment]
>ignored repos where grunt didn't work or do anything

How do you do that? Also note with that answer that I would want to npm install first.

**Comment by zepumph** [comment]
The above commits have a few updates. 
* add clone missing repos
* push copyright updates
* update copyrights for active-repos
* simplify commit/push step for third party report

@jonathanolson please see how I'm still just doing npm update for non chipper/perennial repos, does that seem ok? Or should I use `npm prune && npm update`

**Comment by zepumph** [comment]
- [ ] @jonathanolson in addition to the above question, when this is good to go we should also remove `report-third-party` from production deploys. 

Is there anything else for this issue?

**Comment by jonathanolson** [comment]
> please see how I'm still just doing npm update for non chipper/perennial repos, does that seem ok? Or should I use npm prune && npm update

I'd recommend always doing the prune with the update.

Let me know when it's at the point to remove the third-party report from deploys (if I should do that, or if you were planning on doing it).

**Comment by zepumph** [comment]
Removed above. I also added binder doc and cleaned up the copyright loop since we are using active-repos now, @jonathanolson anything else?

**Comment by jonathanolson** [comment]
Looks good to me, thanks!

**Comment by zepumph** [comment]
Oops the third party credits is now being pushed correctly.
