### ISSUE TITLE
Add brands to build server notification email

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#143]
This would be of minor help as we begin to publish more sims for phet-io.

**Comment by zepumph** [comment]
I think that the build server needs to be restarted for this to be picked up. There is no rush, but if that only takes a minute or two that could be nice. @mattpen could you comment, deciding whether to restart now, or to let it sit until next restart. Either is alright with me. Feel free to close this issue if the change looks good.

**Comment by mattpen** [comment]
It's usually fine to restart it at anytime. I can restart it tomorrow if you're unsure of the process.

**Comment by zepumph** [comment]
That would be great thank you.

**Comment by mattpen** [comment]
Sorry for the delay.  I restarted the build server today.  @zepumph please confirm if this issue is resolved.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/61739581-2eb70c00-ad39-11e9-9070-6b3a2b56b002.png)
👍
