### ISSUE TITLE
gas-properties RC deploy failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#145]
I'm trying to deploy 1.0.0-rc.1 for gas-properties.  I ran:

```
% cd gas-properties
% grunt rc --brands=phet --branch=1.0
```

Email from PhET Build Server informs me that the build failed, see below.  I have no familiarity with the build server. I asked for help on Slack, but no response, so creating this issue.

@ariel-phet please assign.  This is blocking RC testing for gas-properties.

```
Build failure: Build aborted,Error: ssh phet-admin@bayes.colorado.edu mkdir -p /data/web/htdocs/dev/html/gas-properties/1.0.0-rc.1 in . failed with exit code 1 and stdout:
Sim = gas-properties Version = 1.0.0-rc.1 Brands = phet Locales = en Shas = {"comment":"# gas-properties 1.0.0-rc.1 Mon Jul 29 2019 13:51:25 GMT-0600 (Mountain Daylight Time)","assert":
{"sha":"201c50a840e082354b013f4ab9e9d45006f98cfe","branch":"HEAD"},"axon":{"sha":"3f0943a68952c903024c190a43e4f3b9033e8c4e","branch":"HEAD"},"brand":{"sha":"40dd405ec950d10e15e957cbda3d97362e925bef","branch":"HEAD"},"chipper":{"sha":"0dcc680922df28076301ea187742bc738bc4cdd4","branch":"HEAD"},"dot":{"sha":"29e6b8aa840d467420c601c918556117dbaf9df2","branch":"HEAD"},"gas-properties":{"sha":"54d88f4ecacc79847224370a8b3e69f3bbf83165","branch":"1.0"},"joist":{"sha":"45345276ab5d17c1dec37ec32b216553f828ff0e","branch":"HEAD"},"kite":{"sha":"34e7bdb4379b8faab55c728fdd462d4477f77fe7","branch":"HEAD"},"phet-core":{"sha":"30264b9e3edcadccdcc75364d383c69d23702529","branch":"HEAD"},"phet-io":{"sha":"34b581c4106625082369457881195b6aa3028592","branch":"HEAD"},"phet-io-wrappers":{"sha":"4c05b62ef1fcbc8f09536d95abd9308ccaebb84b","branch":"HEAD"},"phetcommon":{"sha":"b82ae2142fe0874561941895a4b36ce6f91428b9","branch":"HEAD"},"phetmarks":{"sha":"dfc5b1da1d7cc0939c484f7f26f7148f28264ee4","branch":"HEAD"},"query-string-machine":{"sha":"c4c6d494b474aeb14d700a8142da81776f62a2ba","branch":"HEAD"},"scenery":{"sha":"3bf29595fc9f2042a808090621af03869f547fbe","branch":"HEAD"},"scenery-phet":{"sha":"589f1bd24feec9c49b5415b3d7bc5d7322b2f7ab","branch":"HEAD"},"sherpa":{"sha":"4877464e8013ff1459091c854a8c2234c3d0e7d6","branch":"HEAD"},"sun":{"sha":"2956714d4645a2cffb6f87d2c6dbd545599d2843","branch":"HEAD"},"tambo":{"sha":"46e369d657d01af403c31d5f2c54a0f3e0486224","branch":"HEAD"},"tandem":{"sha":"4fc21af570be99ba9ffbe6b13f5b5e85679df316","branch":"HEAD"},"twixt":{"sha":"ade8b222df3906d5a3298c4e3f12c72c54bda855","branch":"HEAD"}}

```

**Comment by pixelzoom** [comment]
It looks like package.json in gas-properties 1.0 branch will need to be manually reverted.  Version should be rolled back to 1.0.0-rc.0.

```js
{
  "name": "gas-properties",
  "version": "1.0.0-rc.1",
  "license": "GPL-3.0",
```

**Comment by zepumph** [comment]
On bayes, looks like GP doesn't have group write:

`drwxr-sr-x.  47 malleyc    phet 4096 Jul 25 16:23 gas-properties`

**Comment by zepumph** [comment]
Perhaps this is a problem with the dev deploy process, but @pixelzoom you could fix it by going onto bayes and chmoding to add group write, then rerunning the rc.

**Comment by zepumph** [comment]
>you could fix it

fix the immediate, top priority problem.

**Comment by pixelzoom** [comment]
Hmmm.  I did not manually create `gas-properties/`.  And why did `grunt dev` worked 44 times?

**Comment by zepumph** [comment]
the dev process uses the username in your build-local, rc uses phet-admin via the build-server.

**Comment by zepumph** [comment]
>I did not manually create gas-properties/

Right that is the buggy part to be fixed in this issue. The dev process likely didn't give correct group permissions when creating that folder. Everything else I'm speaking about is just to get the ball rolling for GP.

**Comment by pixelzoom** [comment]
waves-intro/ is also `drwxr-sr-x` (@samreid), maybe that's a clue to when this problem was introduced.

**Comment by pixelzoom** [comment]
Thanks @zepumph.  After `chmod g+w` on gas-properties/, `grunt rc` is succeeding. 

I've created https://github.com/phetsims/perennial/issues/146 to track the problem with `grunt dev` and directory permissions.

Closing.
