### ISSUE TITLE
improving documentation and tracking for maintenance releases

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#147]
In 8/1/19 dev meeting, I brought up the topic of improving documentation and tracking for maintenance releases.   The process is currently a bit informal, and could bite us in the future.   

Examples that could be problematic:
* A patch sneaks into an active RC process, without the responsible developer or QA noticing.
* Something goes wrong and we want to answer the question "What maintenance releases were done since March 1, and which sims were patched?"
* Answering the question "does this sim have this patch?" requires a lot of poking around in GitHub issues and commits.

@ariel-phet asked me to create this issue, to further discuss what might be needed for the maintenance release process.

**Comment by ariel-phet** [comment]
How are we feeling about the maintenance release process these days? I feel like there have been some refinements, are we in a "good enough" working state or are there pain points we should be actively addressing?

**Comment by pixelzoom** [comment]
1/7/2021 dev meeting.

Most of these pain points were more related to batch maintenance releases.  Consensus was that this can be closed.  If we have future problems, we'll open a new issue.
