### ISSUE TITLE
"PhET-iO Latest Deploys" on website should respect `ignoreForAutomatedMaintenanceReleases`

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#149]
Found while looking at https://github.com/phetsims/perennial/issues/148. It would be nice if that flag set new release branches to be automatically inactive. It looks like bumper/chains may be already automatically set to inactive. 

`grunt print-phet-io-links`, and the maintenance release process use the phet-io metadata's active flag, and it would be good to make sure everything here is in sync. @mattpen let me know if I can help at all.

**Comment by mattpen** [comment]
This was addressed in https://github.com/phetsims/website/commit/53a0022acc5bbea42807cba0b73caadb1c0b0ad4 and deployed.  @zepumph when you were testing deploys of phet-io-test-sim in #148, did you notice if this was working or not?

I thought we had set everything to inactive, but it seems to have reverted itself here: https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminPhetioDeploy

**Comment by zepumph** [comment]
I checked the active status of phet-io-test-sim on https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminPhetioDeploy, and found that every minor version of phet-io-test-sim is active.

During out work wednesday, I toggled all of these to be inactive. From this I think that this issue is not done.

**Comment by zepumph** [comment]
I think that this issue should be raised in priority, all example-sim chains bumper and phet-io-test-sim branches have been switched to active. I would rather not manually toggle those, and it seems like whatever toggled them that way (perhaps a release?) means that it could happen programmatically again.

Discovered because phet-io-test-sim made it into a recent maintenance release and @KatieWoe was testing it without realizing that that was not needed.

**Comment by zepumph** [comment]
In https://github.com/phetsims/website/commit/53a0022acc5bbea42807cba0b73caadb1c0b0ad4 the flag is ignoreForAutomatedMaintenanceReleases, but over in PERENNIAL/notifyServer, it looks like the flag is called `active`. I thought we decided to have it be called `active` to hide the implementation detail of that package flag name from the website service.

**Comment by zepumph** [comment]
>all example-sim chains bumper and phet-io-test-sim branches have been switched to active.

Sorry this is not true!!! Only phet-io-test-sim's were switched, I misread the table. Still though, this bug would come up, and toggle any of these version to become active whenever they are redeployed. I still think the priority stays, especially if it is an east fix. @mattpen let me know if I can help, and feel free to production deploy phet-io-test-sim till your heart's content to test.

**Comment by mattpen** [comment]
@zepumph - is this actually high priority?  Sorry I haven't been able to prioritize the work.  Please reassign me if this is needed urgently.

**Comment by zepumph** [comment]
After much investigation and remembering what the heck I was talking about last year, I think that this is not a bug, but that there is a little cleanup that makes sense to do. 

the "ignoreForAutomatedMaintenanceReleases" flag is being set as the `active` flag when posted to the website service:

https://github.com/phetsims/perennial/blob/dfccee19db8034db6ff2da227a30eb7491e9cf96/js/build-server/notifyServer.js#L73

I got confused because I saw that PhetioDeploy.java has an unused string in it called `IGNORE_FOR_AUTOMATED_MAINTENANCE_RELEASES`. I didn't realize it was `ACTIVE` that the logic was related to. 


I published a production version of phet-io-test-sim for 1.5 a day or two ago, and all phet-io-test-sim branches are still set to inactive through the admin panel on the website.

I think all that is left for this issue is to likely delete this unused line for cleanup: https://github.com/phetsims/website/blob/master/src/java/edu/colorado/phet/website/data/PhetioDeploy.java#L31

Thanks!

**Comment by mattpen** [comment]
Ok, I cleaned up this file.  Closing.
