### ISSUE TITLE
Build server is up but crashed for unknown reasons.

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#15]
During https://github.com/phetsims/fraction-matcher/issues/92

I did:

```
$ grunt deploy-rc
Running "deploy-rc" task
```

Then after a minute or two it printed out:

```
Warning: Build request failed with status code 503. Use --force to continue.
```

I'm unfamiliar with perennial and the build-server so I'm not sure what's wrong.

**Comment by samreid** [comment]
Here's the description of a 503:

> 10.5.4 503 Service Unavailable

> The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response.

**Comment by samreid** [comment]
I can see that build-server.js uses winston for logging, but I don't see where the logs are being created.

**Comment by samreid** [comment]
@jessegreenberg @pixelzoom @jonathanolson @jbphet @phetsims/schmitzware @andrewadare heads up that the Build Server may be down.

**Comment by samreid** [comment]
According to build-server.js, winston is just outputting to the console.  I wonder if this is piped to a file somewhere?

```js
// add timestamps to log messages
winston.remove( winston.transports.Console );
winston.add( winston.transports.Console, { 'timestamp': function(){
  var now = new Date();
  return dateformat( now, 'mmm dd yyyy HH:MM:ss Z' );
} } );
```

**Comment by samreid** [comment]
Following the docs, I'll try:

```
sudo /etc/init.d/build-server restart
```

It reported:

```
Stopping build-server:                                     [  OK  ]
Starting build-server:                                     [  OK  ]
```

Now I can send commands to the build server again, though I am not sure why it failed in the first place.  Are there logs we can/should look at?

**Comment by jonathanolson** [comment]
/data/share/phet/phet-repos/perennial/build-server.log or something like that

**Comment by samreid** [comment]
Yes, that seems correct.

**Comment by samreid** [comment]
I'm seeing a few errors in the log for this time frame (but no indication of when the build server restarted):

Mar 10 2016 06:19:42 MST - error: adding to user_localized_simulation_mapping, translator probably already exists for this sim and locale
Mar 10 2016 06:19:42 MST - error:  error: duplicate key value violates unique constraint "user_localized_simulation_mapping_pkey"

Mar 10 2016 06:22:52 MST - error: Build failed with error: error running command ssh jblanco@spot.colorado.edu 'chmod -R g+w /htdocs/physics/phet/dev/html/fraction-matcher/1.1.0-dev.2': Error: Command failed: chmod: WARNING: can't change /htdocs/physics/phet/dev/html/fraction-matcher/1.1.0-dev.2/build

Mar 10 2016 06:24:05 MST - error: adding to user_localized_simulation_mapping, translator probably already exists for this sim and locale
Mar 10 2016 06:24:05 MST - error:  error: duplicate key value violates unique constraint "user_localized_simulation_mapping_pkey"

Mar 10 2016 06:25:19 MST - error: error running command: ssh jblanco@spot.colorado.edu 'chmod -R g+w /htdocs/physics/phet/dev/html/fraction-matcher/1.1.0-dev.2' in ../fraction-matcher/build. build aborted.

Are some of these errors good?

**Comment by jessegreenberg** [comment]
SR: What is the state of build server, is it prone to crashing or should we investigate making it more reliable?

JO: There are ways we can make build server more reliable.  We can investigate possibilities in the future.

**Comment by mattpen** [comment]
@samreid - Have you seen this behavior since March 2016?  I don't recall ever seeing this error.  Can we close this issue?

**Comment by samreid** [comment]
I haven't seen this problem for a long time, closing.
