### ISSUE TITLE
Problems with `data/testable-phet-io-validated`

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#150]
* Call it `phet-io-validated`, since all the other testable files are auto-generated
* Add that `&phetioValidateAPI=false` when not validated (along with restarting CT) (something like `continuous-server:676`)
* It isn't in the `data/README.md`. It should be documented as a way to opt in to tandem and API validatation

**Comment by samreid** [comment]
I believe this recommendation has been superceded by https://github.com/phetsims/phet-io/blob/1fa086bf66ead7384afc72e5ffbd404a3aadf3f1/doc/phet-io-instrumentation-technical-guide.md#validation, closing.
