### ISSUE TITLE
grunt generate-data bayes process broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#155]
@pixelzoom reported waiting for a while to get updated data lists, I'll investigate.

**Comment by zepumph** [comment]
I tried debugging this in a variety of ways, but I think what failed this is that there was an npm dependency added just that `grunt generate-data` failed. So even though the process will npm update, it won't ever get to that. I think that the way to fix that is to have the process run a script that pulls perennial, npm updates, and then runs `grunt generate-data`. Honestly I'm not too interested in implementing that right now, but could if people thought it was best. Otherwise things will just break again when we add another node module to perennial.

**Comment by zepumph** [comment]
I broke down and added `generate-data.sh`. @jonathanolson could you please review the updated documentation and new script.

**Comment by jonathanolson** [comment]
I don't see a place where chipper is explicitly npm pruned/updated (and we'll want to `npm prune` and `npm update` for perennial, instead of just `npm update`). Can we make that change for the bash script, and let me know how chipper's npm is handled?

**Comment by zepumph** [comment]
Why does chipper need to be handled? Don't we just need to read all the sim's `package.json` files? I added that in, and then took it out.

* I'll add npm prune`
* I'll then restart the process.

**Comment by jonathanolson** [comment]
It looks like we're not running any `grunt` tasks in the sim repos? Then it should be fine to omit chipper.

**Comment by zepumph** [comment]
Agreed, and thanks for the review. I just checked and the process is still running. Closing
