### ISSUE TITLE
Size of "file" column in apache index pages

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#159]
When navigating sim folders on phet.colorado.edu (i.e. https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/), all of the interesting bits of the filenames are cut off. This makes it quite challenging to find the file you are looking for.

Since this doesn't happen on phet-dev (https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0/phet/), I wonder if it is a small setting that can be toggled without much effort. 

This article makes it seem like it may just be replacing a hard coded width for a `*`, https://stackoverflow.com/questions/29586309/directory-listing-column-width.

I would think of this as a low priority issue.  @mattpen might this be possible to do?

**Comment by mattpen** [comment]
@zepumph - It looks like phet-dev was using a fixed width of 55.  phet was not specifying a width, so the column was auto sized but a maximum of 20.  I've changed both phet and phet-dev to use auto width, i.e. `*`.  This is already in place (only required a non-invasive reload of an .htaccess file) on both servers.  https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/ seems to be working nicely, please check and close if resolved.

**Comment by zepumph** [comment]
This is so awesome. Thank you greatly!!!

I see the entire filename now.

![image](https://user-images.githubusercontent.com/6856943/71699742-87211980-2d6d-11ea-81ea-4356f0191b17.png)
