### ISSUE TITLE
Command execution wrapper doesn't log error output

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#160]
I'm working on a build failure that seems to be caused be problems related to directory creation.  The email that gets sent as a result of the failure has the following line in it:

```
Build failure: Build aborted,Error: ssh phet-admin@bayes.colorado.edu mkdir -p /data/web/htdocs/dev/html/number-line-integers/1.0.0-rc.1 in . failed with exit code 1 and stdout:
```

The build server log has essentially the same line but with a time stamp:

```
Jan 03 17:24:54 phet-server.int.colorado.edu build-server[34225]: error: Build failure: Build aborted,Error: ssh phet-admin@bayes.colorado.edu mkdir -p /data/web/htdocs/dev/html/number-line-integers/1.0.0-rc.1 in . failed with exit code 1 and stdout:
```

In both cases, there is either nothing in `stdout` or it is not being printed correctly, which is unfortunate, because the error message would potentially be helpful in diagnosing the problem.  Should this be printing `stderr` instead of or in addition to `stdout`?

This seems like it would be a quick and beneficial thing to fix.  I think @mattpen is the current owner of the build server, so I'll assign to him initially, he can reassign as appropriate.

**Comment by mattpen** [comment]
@jbphet - This is handled in `perennial/js/common/execute.js`.  It looks like it is logging content from stderr in the logs (and has been since 2017).  Do you want the stderr content in the email as well?

**Comment by jbphet** [comment]
> Do you want the stderr content in the email as well?

I don't think that's necessary.  I generally go to the log to follow up on any emails that indicate build errors, and assume others do too.

> Or is there a bug with the stderr log output?

It seems like it.  I just looked through the log and saw a number of places where the `stderr` logging preamble is output but there isn't any content.  Here's an example from yesterday:

```
Dec 01 13:09:00 phet-server.int.colorado.edu build-server[6868]: > node install.js
Dec 01 13:09:02 phet-server.int.colorado.edu build-server[6868]: debug: stderr:
Dec 01 13:09:06 phet-server.int.colorado.edu build-server[6868]: debug: stdout: Chromium (818858) downloaded to /data/share/phet/phet-repos/chipper/node_modules/puppeteer/.local-chromium/linux-818858
```

I think we should understand why these blank `stderr` lines are being logged and make sure that we're not missing something.  If there is indeed no error information coming from the system in these cases, it would be best not to include them in the log, since they make it look like something was omitted.  I often search for the string `err` in logs like these, so entries that match the search but have no information associated with them are confusing and frustrating, and I assume others run into the same problem.

**Comment by mattpen** [comment]
I think I see what the problem was, stdout and stderr were printed asynchronously, so their outputs were interpolated.  I change the executor to accumlate all output for each and print them separately after the command finished.  It looks much better now.  There could still be blank lines, but they should be intentional (the command actually printed a blank line to stderr/stdout).  If stdout/stderr are actually empty, there will be a log saying so.

Example:
```
Dec 02 21:46:41 phet-server.int.colorado.edu build-server[15786]: debug: Running npm prune from ../chains
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: debug: Command npm finished. Output is below.
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: debug: stderr is empty.
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: debug: stdout: audited 97 packages in 0.78s
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: found 5 low severity vulnerabilities
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: run `npm audit fix` to fix them, or `npm audit` for details
Dec 02 21:46:42 phet-server.int.colorado.edu build-server[15786]: debug: Running npm update from ../chains
Dec 02 21:46:43 phet-server.int.colorado.edu build-server[15786]: debug: Command npm finished. Output is below.
Dec 02 21:46:43 phet-server.int.colorado.edu build-server[15786]: debug: stderr is empty.
Dec 02 21:46:43 phet-server.int.colorado.edu build-server[15786]: debug: stdout is empty.
```

This seems like a good enough improvement to me, @jbphet feel free to reopen if I missed something.

**Comment by jbphet** [comment]
Sounds good.  I just looked through the log and saw a number of non-blank `stderr` entries, so it seems like an improvement.
