### ISSUE TITLE
Daily grunt work deleted important code

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#161]
While working on https://github.com/phetsims/balancing-act/issues/96, I ran `grunt update` from a phet-io change, and noticed that it generated an unpublished readme for balancing act.  I tracked the problem down to a commit in which the daily grunt work deleted an important function:

https://github.com/phetsims/chipper/commit/63d47a9ca816515bbf3e5fc66e83c2f88a114c41

I'm unfamiliar with this script, so I'll assign it to the script's author.  Also marking as high priority in case it is causing other problems.

**Comment by zepumph** [comment]
Chippers SimVersion is copied from perennial each night. To make changes to the file you must commit to the one in perennial and it will be copied over. (or commit equally to both for a more immediate usage). It is noted at the top of the chipper version and perennial version. Please let me know how better the issue can be addressed if this linkage isn't documented well enough to you.

**Comment by samreid** [comment]
Thanks for the good information!  I committed to perennial/SimVersion, closing.
