### ISSUE TITLE
build server should copy built version to dev area for both RCs and production builds

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#17]
As of this writing, the build server copies the results of its build to the dev server (currently spot) when doing a release candidate (RC), but copies the _local_ version (i.e. from the developer's machine) to the dev server when doing a production release.  I'm not sure why it was done this way, but we discussed it in a recent dev meeting and decided that the version built by the build-server should be copied to the dev server in both cases.

Here's a few lines of code in build-server.js that will need to change, there may well be other changes required too:

``` js
  if ( option === 'rc' ) {
    spotScp( afterDeploy );
  }
  else {
    // ...
```

**Comment by jonathanolson** [comment]
@jbphet, I believe this currently happens in deployments (if not in build-server itself). Can you confirm, and close if it's done?

**Comment by jbphet** [comment]
I just looked at the build server and the grunt tasks in chipper, and it looks to me like the local build is still doing the transfer of the dev file.  In `build-server.js` I see the following code:
```js
if ( option === 'rc' ) {
   if ( brand === 'phet' ) {
      spotScp( brand, afterDeploy );
   }
   else if ( brand === 'phet-io' ) {
      writePhetioHtaccess( simDir + '/build/.htaccess', '/htdocs/physics/phet-io/config/.htpasswd', function() {
         spotScp( brand, afterDeploy );
      } );
   }
}
```
These are the only two calls to `spotScp`, which would seem to imply that they only happen if it's an rc build.  

In `chipper/js/grunt/Gruntfile.js`, I'm seeing this:

```js
if ( grunt.option( 'noDev' ) || grunt.option( 'dryRun' ) ) {
  deployUtil.commitAndPushDependenciesJSON( grunt, function() {
    deployProduction( grunt, buildConfig, done );
  } );
}
else {
  deployDev( grunt, buildConfig, function() {
    deployProduction( grunt, buildConfig, done );
  } );
}
```
This looks like a local `deployDev` happens, followed by a `deployProduction`.  So I think this is still an issue.

@jonathanolson - please review my thinking and, if you concur, we should probably mark this as a change for chipper 2.0.

**Comment by zepumph** [comment]
The build server supports this well at this point. Please see the "servers" option in production.js


```js
    // Send the build request
    await buildServerRequest( repo, version, branch, await getDependencies( repo ), {
      locales: '*',
      brands: brands,
      servers: [ 'dev', 'production' ]
    } );
```

Closing
