### ISSUE TITLE
Update puppeteer from v1.11.0 to v2.1.1 (latest)

### ISSUE THREAD

**Issue by chrisklus** [phetsims/perennial#170]
This update will fix https://github.com/phetsims/chipper/issues/928.

I'm not sure who to ask before doing this and what all needs to be checked after it's updated. If updating to the latest version is problematic, a small update to `v1.12.0` will likely still fix the above issue.

Assigning to @zepumph and @samreid for now, please feel free to unassign and recommend someone else.

**Comment by zepumph** [comment]
I don't think perennials puppeteer is used for update phet io files.
Wouldn't it be chippers? I updated chippers to fix an npm vulnerability
last  month.

**Comment by samreid** [comment]
Why does perennial even have puppeteer?

**Comment by chrisklus** [comment]
Oh whoops, yeah the problem from https://github.com/phetsims/chipper/issues/928 is fixed if i revert my local update in perennial and `npm prune && npm install` in chipper. Thanks.

**Comment by zepumph** [comment]
>Why does perennial even have puppeteer? 

I added it for the PDOMComparison task. 

I think this issue is now a duplicate of https://github.com/phetsims/chipper/issues/949. Closing
