### ISSUE TITLE
Outline processes devs use for git hooks

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#171]
This is the parent issue to https://github.com/phetsims/aqua/issues/90, as well as other things.

It was brought up during dev meeting that linting as a git hook on master is very valuable.

@jonathanolson mentioned that for maintenance releases we need to have an easy way to turn this off.

We should also outline that git hooks is a method for running code before a git commit goes through, but there are lots of things that could run before allowing a commit to go through.

As mentioned in https://github.com/phetsims/aqua/issues/90, the "acceptable amount of time" for this code to run before a commit happens should be discussed here too. 

Marking for dev meeting.

**Comment by zepumph** [comment]
This is largely a duplicate of https://github.com/phetsims/chipper/issues/751, but oh well.

**Comment by pixelzoom** [comment]
5/14/2020 dev meeting:
Re:
> @jonathanolson mentioned that for maintenance releases we need to have an easy way to turn this off.

Run maintenance processes with hooks off (`--no-hooks`?)

**Comment by pixelzoom** [comment]
> @pixelzoom will add something to PhET Development Overview about how to install hooks.

As I started to do this, I realized that the change to be made in https://github.com/phetsims/aqua/issues/90#issuecomment-628844352 will likely make what I write immediately obsolete. So I've moved this task to that issue.

**Comment by pixelzoom** [comment]
@zepumph I'm not sure what else you had in mind for this issue, so back to you.  I'm guessing that the work to be done in https://github.com/phetsims/aqua/issues/90#issuecomment-628844352 will address this, and that this issue can be closed.
