### ISSUE TITLE
Use http.createServer instead of localTestingURL

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#175]
After seeing some great work done over in https://github.com/phetsims/phet-io/issues/1664 by @samreid, it is clear and simple to create a server instead of relying on `localTestingURL`. For example see this commit here: https://github.com/phetsims/chipper/commit/9d74fe9631d73521029ff548d13549813991975e.

I think we should try to get rid of this everywhere. Here is where I see usages currently:

- [x] PDOMComparison task using puppeteer (@zepumph)
- [x] binder/
- [x] aqua's Gruntfile https://github.com/phetsims/aqua/issues/97
- [x] (see https://github.com/phetsims/aqua/issues/97) puppeteer unit tests on pre-commit hook
- [x] decaf/buildDecaf.js, excluding the last two usages of URL_ROOT

Assigning to @samreid also in case he has opinions.

**Comment by samreid** [comment]
I agree we should let node serve files and get away from localTestingURL as much as possible.  I opened https://github.com/phetsims/aqua/issues/97 for the qunit part.

**Comment by samreid** [comment]
`localTestingURL` is now used in a sublime plugin:

```py
def get_local_testing_url():
  return get_build_local()[ 'localTestingURL' ]

// ...

class PhetOpenPhetmarksCommand(sublime_plugin.TextCommand):
  def run(self, edit):
    view = self.view
    open_link(get_local_testing_url() + 'phetmarks')

```

Hence we may not be able to delete it.  But we should still get rid of as many usages as possible.

**Comment by samreid** [comment]
I'm not planning to work on this in the near future, unassigning.

**Comment by zepumph** [comment]
@jonathanolson created `withServer` in perennial which is pretty excellent. I would like to use it, or a copy of it, whenever possible, but I have a few concerns. It uses `express`, and I would rather do something that is more vanilla, so that we don't need to depend on such a heavy-weight server app across our project. For example, if I want to use this script in binder/ (for the issue found in https://github.com/phetsims/perennial/issues/229), I don't want express leaking throughout our project.

The vanilla server used by PhET-iO API generation seems a bit more straight forward. I would like to try to use that instead. Tagging @jonathanolson about the work (in my working copy to be committed soon).

**Comment by zepumph** [comment]
I could not figure out an easy way to test ReleaseBranch, so I converted the usage in Binder to confirm that the conversion works. I found that the mime types in the PhET-iO api generation are not complete for phet sims, and I had to add svg and json in order for the sim to fully load in puppeteer. 

I didn't rerun generation though to make sure that new commits in https://github.com/phetsims/perennial/issues/229 are working as expected.

**Comment by zepumph** [comment]
I was able to use PERENNIAL/withServer for binder's usage above. That works really well, but we won't be able to use perennial in Chipper for `generatePhetioMacroAPI`. Perhaps that could benefit from a `dual/` strategy for `withServer`.

**Comment by zepumph** [comment]
PDOM Comparison went smoothly as well.

**Comment by zepumph** [comment]
Alright, all usages of localTestingURL have been removed expect that used by the phet-sublime-plugin. @jonathanolson over to you to review the above commits, and to update the python code for the plugin.


My goal is to tell people that they can remove that key from their build-local, so let me know when you think it is safe for me to do that.

**Comment by jonathanolson** [comment]
Looks good to me! I'll change the plugin at my own convenience.

Looks safe to tell people that!

**Comment by zepumph** [comment]
Posted, closing

>localTestingURL is no longer used on the project. It can be removed from everyone's build-local.json files. This pattern was exchanged for just spinning up a simple, custom server whenever needed, see https://github.com/phetsims/perennial/issues/175 for details.



>14:30
The most dangerous usage conversion was in our pre-commit unit testing task. If you run into unexpected trouble there, please post in that issue. Thanks!
