### ISSUE TITLE
Need to update graceful-fs before updating node

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#179]
While working on https://github.com/phetsims/perennial/issues/178 I noticed the following message in the build server log:

```
Jun 12 02:40:39 phet-server.int.colorado.edu build-server[63225]: debug: stderr: npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

That sounds fairly urgent, and I know we're thinking about updating node in October if not before, so this should probably be attended to.

Assigning to @mattpen since he's the main build-server guy, and to @ariel-phet since he is tracking several issues related to the upgrade of Node, so he may want this one on his "October list".

**Comment by ariel-phet** [comment]
Speaking with @mattpen it would appear this is a fix that can be made independent of node upgrades.

It does not sound like a huge lift of a fix, but @mattpen currently has bigger priorities.

This might be a good small project for after the successful deploy of the browse/filter pages.

**Comment by mattpen** [comment]
Hmm, this is a bit confusing.  We've never used graceful-fs < 4.0.0.  When I added graceful-fs to the build-server, it started at 4.1.1.  See: c8a9e902e88227502b925c9b4f026922cf1dae10

Also, it says "graceful-fs v3.0.0 and before will fail on node releases >= v7.0" and we have been using Node 8 or higher for 2 years.

**Comment by mattpen** [comment]
This looks like it might be a problem with grunt.  I noticed in arithmetic that the only dependency is `"grunt": "~1.0.0"`, but grunt has a dependency on `"glob": "~3.1.21"` which depends on `"graceful-fs": "~1.2.0"`.  See arithmetic/node_modules/glob/package.json in master.

@ariel-phet I think someone more familiar with grunt should continue this investigation.

**Comment by ariel-phet** [comment]
@jonathanolson will investigate for about an hour soon, and then reassign to me if going to be a long project (with an estimate)

**Comment by jonathanolson** [comment]
Switched to grunt 1.1.0, this should solve the problem. @jbphet can you verify that we don't get the same warning now?

**Comment by jbphet** [comment]
The process to verify this change will be something like this:

+ pull the latest changes on to phet-server
+ restart the build server
+ run a test build
+ verify that the test build succeeded and that there are no instances of this message that were generated as a result of the build (there will likely be instances of the message in the log from before the restart)

We might want to try it all out on ox-dev first.

I'm a little uncomfortable doing this, since @mattpen has been the main point of contact on the build server for a while no, and I wouldn't want to pull any changes that aren't ready yet, so I'm going to turn it over to him to verify and, hopefully, close this issue.

**Comment by mattpen** [comment]
This didn't involve a change to the build-server, @jbphet's proposed testing scheme won't work.  To actually test this on the build-server would require a batch maintenance release for all affected sims.  I would assume that this could just be tested with a local build on master for every sim and checking for the presence of this line in the npm output.  As this hasn't caused any problems with the build-server to date, I would assume that a batch release is not needed.

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

**Discussion:**
@mattpen @jbphet : This doesn't seem like it requires a maintenance release and isn't a high priority. This hasn't failed since using grunt despite the warning. Updating the grunt version seemed to fix this issue.

@jbphet The worst-case scenario we upgrade Node and it fails to build sims. We have been using an upgraded version of sim and it hasn't broken. To test we would run/build an old RC with an older version of Node and determine if the warning is shown. Then run/build the RC with the newer Node version.

**Resolution**:
When we upgrade to Node 14 make sure graceful-fs (dependency of grunt) isn't failing despite the warning. This should be added to the dev google doc.

**Comment by chrisklus** [comment]
From 11/12/20 dev meeting:

We are good with closing this and opening a new issue for updating grunt (or getting rid of it??)
