### ISSUE TITLE
Add call to syncronize website DB for decaf deployment

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#180]
I've added an http method call to notify the website that it should add a given project to the list of CheerpJ simulations.  We should add a process so that developers like @samreid can call this automatically.

@samreid pointed me towards https://github.com/phetsims/perennial/blob/master/js/grunt/decaf/deployDecaf.js.  

Sam, if we put the http call in this script, it will add it to the DB as soon as the cheerpj sim is deployed.  Is this desirable, or do we want a process more like (1) deploy, (2) verify correctness, (3) publish deployed sim to the website?   If we want the latter, I'll add a separate grunt task.

**Comment by samreid** [comment]
When running the dev deploy task, it outputs a script that can be run to promote the dev version to a production version (see line 140).  Would it make sense to make it part of that script?

**Comment by mattpen** [comment]
@samreid - that is a possibility.  Which user runs that script on phet-server?  The user would need the `serverToken` key in `~/.phet/build-local.json`, if the user is `phet-admin` then this is already in place.

**Comment by samreid** [comment]
I believe the user is `phet-admin` for that build step.

> Also, do we want to have the change be visible on the website as soon as the files are copied over? 

Since there is already a dev step, and the production step is solely copying files over, it seems pretty safe to make the change visible after files are copied.  If we detect a problem afterwards, could it be rolled back?  I also see the advantage of matching this with our other deployment processes.  Which is easier?

**Comment by mattpen** [comment]
> I also see the advantage of matching this with our other deployment processes.  Which is easier?

Not adding an additional check/publish step is easier as that is already in place.  It would take an additional 4-5 hours to setup, test, and deploy a "Publish CheerpJ" button on the sim admin page.

**Comment by mattpen** [comment]
@samreid - The script should now include commands to sync the DB and effectively publish the cheerpj sim.

The curl command will currently fail with a 404 Not Found until the following issues are complete:

https://github.com/phetsims/website/issues/1070
https://github.com/phetsims/website-meteor/issues/216

**Comment by mattpen** [comment]
@samreid - This should be operational now.
