### ISSUE TITLE
Check api differences on phet-io production deploys? 

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#181]
In the past the phet-io team created PERENNIAL/phetioAPIChangeCheck to validate that nothing changes between maintenance releases, but while trying to publish GFL for a MR in https://github.com/phetsims/gravity-force-lab/issues/266, this function was trouble. I removed it for now, but we should decide if we want it back in at all, and if so, how we want it to work.

**Comment by samreid** [comment]
Can you please comment how this disrupted the GFL MR?

**Comment by zepumph** [comment]
Great question! I will need to think about it. All I remember is that it failed on `phetioAPIChangeCheck` when running `grunt production`. I remember feeling like it was because api files had changed, and so it wasn't expected to work anymore. I will need to take a closer look sometime, and perhaps try to reproduce.

**Comment by zepumph** [comment]
@samreid and I discussed this today and it seemed like there was good reason that this check failed out for the GFL release. I think we should reinstate this check.

**Comment by zepumph** [comment]
@samreid anything else here?

**Comment by samreid** [comment]
Looks good, thanks!  We still could improve on the "backward compatible vs exact match" comparison, but there is already a TODO and issue for that, closing.
