### ISSUE TITLE
Only require phet-io dependencies when building for phet-io

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#182]
@jbphet mentioned that he got this error when building tambo for phet-io:

![image (3)](https://user-images.githubusercontent.com/6856943/84717460-54856a80-af22-11ea-8d7c-ded91f3c8ddc.png)

I was thinking that this logic should only occur if phet-io is in the `brands` option.

**Comment by zepumph** [comment]
@jonathanolson will you please review this at a high priority, to make sure we are on the same page.

**Comment by zepumph** [comment]
@jonathanolson, could this be problematic in a case where you built in phet brand without a phet-io repo checked out and then committed that dependencies.json file to our codebase? Then we would no longer be tracking this. Perhaps we should assert somehow that all our dependencies are in dependencies.json?

**Comment by jonathanolson** [comment]
That could perhaps mess with dependencies.json in master, if there's a dev version deployed with only phet brand AND the user had missing phet-io dependencies?

Thoughts, should we test with that setup? Release branches should generally be fine.

**Comment by zepumph** [comment]
Yeah, perhaps just test in dev.js then, eh?

**Comment by zepumph** [comment]
I don't really see the issue about master, since we never use master's dependencies.json to checkout shas. 

Let's say you make the following actions:
* Don't have `phet-io/` checked out
* Create a dev version of simX with `--brands=phet`
* Now master will have a copy of dependencies.json without phet-io.js in it.

Who cares though? The next time someone builds a dev version with phet-io brand (or in phet brand with phet-io repos checked out), the dependencies.json will be back to normal.


This is the case that I think is more worrisome:
* A dev on our team doesn't have `phet-io/` checked out
* They are working on a user request for a sim with BAA that only effects phet brand (like on the game screen)
* The MR that into the latest version
* They deploy with --brands=phet

Wouldn't this remove the `phet-io/` from the list of dependencies.json, and so the next time we try to publish with --brands=phet-io, the `phet-io/` repo shas will be messed up?

**Comment by jonathanolson** [comment]
> I don't really see the issue about master, since we never use master's dependencies.json to checkout shas.

It will likely mess with checkout-master/checkout-target, things to use master dependencies.json (although we could make that more consistent).

> Wouldn't this remove the phet-io/ from the list of dependencies.json, and so the next time we try to publish with --brands=phet-io, the phet-io/ repo shas will be messed up?

We don't really switch release branches to/from multiple brands, BUT we might want to.

New plan: how about we don't write dependencies.json (ever) if you don't have dependencies for all brands checked out?

**Comment by zepumph** [comment]
>New plan: how about we don't write dependencies.json (ever) if you don't have dependencies for all brands checked out?

Seems reasonable to me!

So instead of erroring only when building phet-io, instead it should be based on supportedBrands. Please review the above commit.

I tested with `grunt dev --brands=phet --repo=ratio-and-proportion` when I deleted the `studio/` repo. It failed like so:

```
info: building ratio-and-proportion
Fatal error: Perennial task failed:
Error: phet-io dependencies missing
    at module.exports (C:\Users\Michael\PhET\git\perennial\js\common\build.js:105:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (C:\Users\Michael\PhET\git\perennial\js\grunt\dev.js:122:22)
    at async C:\Users\Michael\PhET\git\perennial\js\grunt\Gruntfile.js:309:7
    at async wrap (C:\Users\Michael\PhET\git\perennial\js\grunt\Gruntfile.js:64:7)
Full Error details:
Error: phet-io dependencies missing
Fatal error: perennial grunt "--repo=ratio-and-proportion" "dev" "--brands=phet" failed with code 1

```

Then it passed when I cloned studio back in. This is because ratio and proportion supports phet-io brand in its package.

If you feel like there is more work to be done about writing dependencies, can you create a new issue and coassign me.

**Comment by jonathanolson** [comment]
The commit above sounds good, however I was recommending that we isolate the writing of dependencies.json at the root to "do we have all of the dependencies checked out". If not, building still would be fine, but it wouldn't write the file.

> If you feel like there is more work to be done about writing dependencies, can you create a new issue and coassign me.

Will do.

**Comment by jonathanolson** [comment]
Created in https://github.com/phetsims/perennial/issues/223, closing.
