### ISSUE TITLE
clone-missing-repos.sh should install git hooks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#184]
Now that all PhET developers are using git hooks...  Should clone-missing-repos.sh be modified so that it installs the git hooks for each repo that it clones?  If it does not, then developers need to remember to do that manually, and I see evidence (CT lint errors) that that is not happening.

**Comment by pixelzoom** [comment]
PSA to Slack dev-public channel:

> PSA: clone-missing-repos.sh now installs git hooks. See https://github.com/phetsims/perennial/issues/184.

@chrisklus would you mind reviewing this?

**Comment by chrisklus** [comment]
Looks great, working on my end. Thanks!

**Comment by jessegreenberg** [comment]
This is a great idea. However, I recently ran clone-missing-repos.sh and it nested the directories in an incorrect way. It put weddell inside of tangible inside of ratio-and-proportion.  I think we are missing a `cd ..` after the new line in https://github.com/phetsims/perennial/commit/f7805e9643f15cd857596f6713b176303885dff5.

**Comment by pixelzoom** [comment]
Sorry about that @jessegreenberg.   Fixed in the above commit.   The `cd` is made temporary by putting parentheses around the command.  Please verify.

**Comment by pixelzoom** [comment]
@jessegreenberg ping.

**Comment by jessegreenberg** [comment]
Thanks, it is working well. I tested by removing three repositories and then running clone-missing-repos.sh and verified that the new repos were in the right spot.
