### ISSUE TITLE
make clone-missing-repos.sh usable by 3rd parties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#185]
clone-missing-repos.sh iterates over active-repos, which includes both public and private repos.  For 3rd parties that don't have access to private repos, this makes clone-missing-repos.sh difficult/confusing to use.

At 7/2/2020 dev meeting, we discussed a couple of options:

(1) Add a flag to clone-missing-repos.sh and a private-repos file that excludes private repos.  This requires private repos to be added to 2 files, and is inconvenient for 3rd-party devs.

(2) Keep a separate list of "active public repos" and "all active repos".  Use the former as the default, require PhET devs to use the latter.  This requires public repos to be added to 2 files and is inconvenient for PhET devs. 

Of these 2 options, I lean towards the first, because: private repos are added infrequently, and inconveniencing 3rd-party devs is preferable to inconveniencing PhET devs. 

@ariel-phet FYI.

**Comment by pixelzoom** [comment]
If I go with option 1 above...  Create perennial/data/private-repos.  Use `comm -23 active-repos private-repos` to filter out private repos.

**Comment by pixelzoom** [comment]
I went with option 1.  Summary:

* There's a new file, `perennial/data/active-repos-private`.  I named it `active-repos-private` hoping that it might remind developers when adding a private to `active-repos`. 
* clone-missing-repos.sh has a new option, `-p`, which ignores private repos.  PhET developers will generally not have to use `-p`. It's intend for use by 3rd-party developers who don't have access to private repos.

@ariel-phet please assign someone to review.

**Comment by pixelzoom** [comment]
I notified @heldentodd about the `-p` option.

**Comment by ariel-phet** [comment]
@mattpen will review - marking medium as this should be a quick review.

**Comment by mattpen** [comment]
These changes look fine to me. Closing.
