### ISSUE TITLE
bad doc for lint-everything-say-bitbar.sh

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#186]
In lint-everything-say-bitbar.sh:

```
# Runs 'grunt lint-everything --say".  Developed for usage with fswatch like so:
# cd perennial/
# fswatch ../ -e ".*" -i "\\.js$" --one-per-batch | xargs -n1 ~/apache-document-root/main/perennial/bin/lint-everything-say.sh
#
# Usage: checkout-branch.sh branchName
```

The 3rd line looks wrong, `lint-everything-say.sh` does not exist.

The last line looks like a copy-paste error, since this script has nothing to co with `checkout-branch.sh`.

The documentation also doesn't tell me what this script does. I have no idea what `fswatch` is, or how this script might be useful to me.   And what is "bitbar"?

**Comment by samreid** [comment]
The work in https://github.com/phetsims/chipper/issues/918 was obviated by commit hooks.  I'll delete the script and daemon task.

**Comment by samreid** [comment]
Removed, closing.
