### ISSUE TITLE
build server is sometimes copying translations to spot (dev server)

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#19]
On April 1 at 3:25 PM, a bulk rebuild of a bunch of sims was initiated.  During this process the build server copied translated files for some, but not all, of the simulations to spot (our development server).  I'm not at all sure why this would occur, and have dug into it a little bit and recorded my findings below.

For an example where the translated sims were copied over, see http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.4-rc.1/.  For an example where they weren't, see http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.4-rc.1/.

In the build server log, the messages associated with the bulk rebuild start at time stamp Apr 01 2016 15:25:28 MDT.

There are several problems with this:
- all of these translated sim files on spot will chew up disk space
- if the translations are all getting rebuilt, this process will take longer
- all the transfers to spot cause an occasional failure of the `scp` command, which in turn results in a "BUILD FAILED" email getting sent out.

I'd like to clarify the desired behavior with the other devs.  My assumption is that translations should _not_ be rebuilt when an RC build is performed.  For production builds, translations _should_ get rebuilt, but they should _not_ be copied to spot.  @pixelzoom, @samreid, and @jonathanolson - can you chime in and let me know if you concur with this?  Thanks.

**Comment by jbphet** [comment]
The effort to fix this should be coordinated with #17 since it's the same area of the code.  In fact, this one (#19) should be fixed first so that we don't end up copying over all of the translations on a deploy.

**Comment by pixelzoom** [comment]
@jbphet asked for feedback on:

>   My assumption is that translations should not be rebuilt when an RC build is performed. 

That's the default. But building translations should be possible, via the `--locales` option. Otherwise we won't have the ability to RC test locale-specific changes or fixes.

> For production builds, translations should get rebuilt, but they should not be copied to spot.

Yes, translations must be rebuilt for production releases. 

But I'm not sure whether translations should be copied to spot.  Of the drawbacks you enumerated in https://github.com/phetsims/perennial/issues/19#issue-146088537, "disk space" and "takes longer" seem like valid (but minor) concerns; the 3rd concern ("scp failures") is a lack of robustness in the build tools that should be addressed.

**Comment by samreid** [comment]
> My assumption is that translations should not be rebuilt when an RC build is performed.

We may need to RC test some translations in the future.

> For production builds, translations should get rebuilt, but they should not be copied to spot.

I don't feel strongly either way.  Having an exact dev mirror of figaro seems advantageous (it's a backup, it keeps things simple and clean to be a direct copy), but I agree it suffers the drawbacks you pointed out.

**Comment by jbphet** [comment]
Marking for discussion in dev meeting to finalize the desired behavior.

**Comment by jbphet** [comment]
This was discussed in the 4/7/2016 developer meeting, and we decided that the build tools should behave as follows:
+ ```grunt deploy-rc``` should, by default, build just the English sim version, but the locales flag can be used to specify other locales
+ ```grunt deploy-production``` should, by default, build all current translations, but the locales flag can be used specify some other set of locales (though it's not clear when this would be useful)
+ everything that is built by either ```deploy-rc``` or ```deploy-production``` should be copied to spot (the dev server), disk space is not a concern, at least not yet

Note that these changes are likely to affect the chipper repo more than this repo (perennial).  That will mean that the behavior is going to be captured in the dependencies.json, and will not behave as described above for simulations whose dependencies are/were captured before these changes are made.

**Comment by jonathanolson** [comment]
@mattpen, it was recently noted that build-server's rc (but not production) copies things to spot. Just noting that the proposal is that build-server rc/production both copy the files to spot (so client-side no dev upload should be done).

Furthermore, we'll potentially want to factor out some of the perennial code (where the deploy code will live) for use in build-server for this. See `dev.js`.

**Comment by mattpen** [comment]
`grunt production` now requests that the build-server deploy to both the production and dev servers and this has been working nicely.  Closing.
