### ISSUE TITLE
Can I use assert in listContinuousTests?

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#193]
From https://github.com/phetsims/perennial/issues/191#issuecomment-673122044:

>Tagging @jonathanolson to make sure that it is alright to use assert in listContinuousTests.js as I did above.

Over to you @jonathanolson to confirm that the usage of assert in listContinuousTests is ok. Feel free to close.

**Comment by jonathanolson** [comment]
Yes, seems fine. It will presumably fail loudly if this starts happening!
