### ISSUE TITLE
Maintenance Process improvements

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#195]
From my MR I am doing for https://github.com/phetsims/chipper/issues/979#issuecomment-686674583, I have a couple things that could be really nice to do for UX.

1. I kept getting errors because of my working copy and network while calling `Maintenance.addNeededPatchesAfter()`. It would be really nice if you could give it a repo to start with, so that you don't have to repeat the first half of the list after and error.
2. A point of confusion I had was in step 7 and 8. I wasn't until going through them, and getting a bit confused, that I realized I didn't need to do them because I already had a "fix" sha from master. This line was helpful in the intro, but I think something could be done to add this doc to the actual steps also:
>Then loop the following until no more release branches need patches. NOTE: If you have a "fix" commit SHA, feel free to skip to step 9 (adding the patch SHA). 
3. `Maintenance.listLinks()` is a bit cryptic. It seems like it may change between rc and production, although I'm not really sure. No matter, my chief complaint is that It isn't explained what what the criteria is to make it into this list. Over in https://github.com/phetsims/chipper/issues/979#issuecomment-686674583 a small fraction of the release branches were listed. Most because they were unpublished RCs, but I felt like I had to make that jump a bit.

**Comment by zepumph** [comment]
Over to @jonathanolson for comment.

**Comment by jonathanolson** [comment]
Added documentation improvements that hopefully help with 2 and 3. The first point has been annoying for me too, wholeheartedly agree it should be a change (leaving assigned).

**Comment by zepumph** [comment]
- [ ] I also felt like `Maintenance.checkBranchStatus()` was really a nuisance, beause it takes so long and can cull my momentum on an MR (which is often not my highest priority). Is there a way to parallelize that, or perhaps make it faster?

**Comment by jonathanolson** [comment]
> I also felt like Maintenance.checkBranchStatus() was really a nuisance, beause it takes so long and can cull my momentum on an MR (which is often not my highest priority). Is there a way to parallelize that, or perhaps make it faster?

Yes, it takes a frustrating amount of time! It has to check out a lot of things, I'm unaware of any easy way to make it faster.

**Comment by zepumph** [comment]
Ok. Thanks so much for the doc updates.
