### ISSUE TITLE
`-phetio` is not added to dev server version path for chipper 1.0

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#196]
Noted in https://github.com/phetsims/QA/issues/559. 

Instance Proxy paths are broken because the directory structure isn't as expected. Notice this is broken in these sims, even an old MR:
https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-rc.3/wrappers/index/
https://phet-dev.colorado.edu/html/charges-and-fields/1.0.7-rc.1/wrappers/index/

This isn't broken on the production server:
https://phet-io.colorado.edu/sims/charges-and-fields/1.0.7-phetio/wrappers/index/index.html

It looks like the proper logic exists to support adding `-phetio` to chipper 1.0 phet-io sims when deploying to production:

https://github.com/phetsims/perennial/blob/939a2223f9459b7e174189fdd19f89c3a39a6225/js/build-server/taskWorker.js#L279-L286

But not for the dev server:

https://github.com/phetsims/perennial/blob/939a2223f9459b7e174189fdd19f89c3a39a6225/js/build-server/taskWorker.js#L238-L248

Mostly @samreid and I are confused about how this is broken. As it seems like every RC made on a chipper 1.0 phet-io sim since chipper 2.0 would be broken in this way. Perhaps our MR process has mostly involved testing production sims on phet-io.colorado.edu.
The production version directory was fixed in https://github.com/phetsims/perennial/commit/9134c742104fd9763aabdc6398b8ccbbd8d50306 (7/2018)

It is likely that this patch would fix this issue:

<details>

```diff
Index: js/build-server/devDeploy.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/build-server/devDeploy.js	(revision 579f61811ab3cd89b4322b10d4f9df204b69c4f8)
+++ js/build-server/devDeploy.js	(date 1602693474739)
@@ -24,9 +24,15 @@
  * @returns {Promise}
  */
 module.exports = async function( simDir, simName, version, chipperVersion, brands ) {
-  const simVersionDirectory = constants.BUILD_SERVER_CONFIG.devDeployPath + simName + '/' + version;
-
+  const simDirectory = constants.BUILD_SERVER_CONFIG.devDeployPath + simName;
+  let versionDirectory = version;
   try {
+
+    if ( brands.length === 1 && brands[ 0 ] === constants.PHET_IO_BRAND && chipperVersion.major === 0 && !version.match( '-phetio' ) ) {
+      versionDirectory = version.split( '-' ).join( '-phetio' );
+    }
+    const simVersionDirectory = `${simDirectory}/${versionDirectory}`;
+
     // mkdir first in case it doesn't exist already
     await devSsh( 'mkdir -p ' + simVersionDirectory );
     const buildDir = simDir + '/build';
@@ -45,7 +51,7 @@
     return await new Promise( ( resolve, reject ) => {
       new rsync()
         .flags( 'razpFFO' )
-        .set( 'no-perms')
+        .set( 'no-perms' )
         .source( buildDir + '/' )
         .destination( user + '@' + host + ':' + simVersionDirectory )
         .execute( ( err, code, cmd ) => {

```

</details>

@jonathanolson what do you  think about the above patch, especially the assumptions about 1 brand. Do you think I could apply this for testing?

**Comment by jonathanolson** [comment]
I believe this sounds good, although presumably we'd also need to update the maintenance links generation code (I can do it after).

Can we have that applied, and then do another RC for that branch, to ensure it resolves the issue?

**Comment by zepumph** [comment]
@ariel-phet what is the priority of this as it pertains to my other PhET-iO work (like https://github.com/phetsims/scenery/issues/1047)?

**Comment by zepumph** [comment]
@mattpen, is there an easy way to test a build with chipper 1.0? For example chains in a certain branch or something like that? I remember 2 years ago when you were working on this, that you were doing a lot of test builds, split on chipper 1.0/2.0. Do you have guidance on how I could reproduce a chipper 1.0 phet-io build for testing?

**Comment by mattpen** [comment]
Ostensibly you would just check out an old branch of chipper and follow the old deployment instructions. I'm not an expert on what happens in chipper, but the build server should still work for chipper 1.0.

There is no build-server 1.0. The build server just has two ways of interpreting input.  Once it knows what to deploy it does the same thing whether it received the request from chipper 1.0 or 2.0. So you may be able to reproduce a build from chipper 1.0,  but the deployed result might not match.  

If you actually need to build from an old version of the build server, we might be able to get something running on ox-dev.

**Comment by ariel-phet** [comment]
@zepumph as to priority I would like to understand ramifications here a bit better and discuss briefly at dev meeting so I am sure I am clear on the issue

**Comment by mattpen** [comment]
@zepumph - Let me know if you need anything else from me on this issue.

**Comment by zepumph** [comment]
I committed the update above, and I'm testing by publishing CAF 1.0.20-rc.4.

**Comment by zepumph** [comment]
I did the necessary steps, and found success in changing the name of the version directory.

I still found that instance proxies was trying to reach the production version of the sim. 

To get around this, I used `launchLocalVersion`, and things worked well. See https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-phetiorc.4/wrappers/instance-proxies/instance-proxies.html?sim=charges-and-fields&launchLocalVersion.

@jonathanolson, you should be able to test even the previous RC with that query parameter. I guess I forgot, since it has been so long since chipper 1.0.
https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-rc.3/wrappers/instance-proxies/instance-proxies.html?sim=charges-and-fields&launchLocalVersion

Feel free to carry on with your MR now.
