### ISSUE TITLE
Make it easy to share working copy changes

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#198]
Often in pair programming, we would like to share all changes to a new driver.  It used to work pretty well to Webstorm => VCS => Create Patch From Working Copy Changes => Paste into Slack => Copy out of Slack => Apply Patch from Working Copy Changes.  But lately apply patch has been intermittently failing, saying “chunks failed to process”.  Also, sometimes the patch is larger than a slack message can support, and we end up copy/pasting into a GitHub issue.  This all seems like too much hassle for something that we would like to do regularly.

Some potential alternatives:
* Investigate a plugin like GitLive: https://plugins.jetbrains.com/plugin/11955-gitlive
* Streamline the process for creating branches.  Perhaps if a branch is named with “temp-” prefix, then it doesn’t need an issue?  We also discussed creating tooling a while back to automatically create branches for N repos.  But I’m not sure committing branches is the best plan for sharing working copy changes (which aren’t necessarily commit-ready).
* Research why “apply patch” is intermittently failing.
* Create a perennial script to generate and transmit a patch from working copy changes, and a perennial script to receive and apply working copy changes.  Maybe based on “git diff” and “git apply” across repos?  How would we transmit the patches--a private repo?

See also notes from dev meeting Thursday, Feb 20, 2020 where CM showed how to use the “patch” command line function.

**Comment by pixelzoom** [comment]
@samreid said:
> See also notes from dev meeting Thursday, Feb 20, 2020 where CM showed how to use the “patch” command line function.

From https://docs.google.com/document/d/1duip7__YZk_waSeedH0AnpcSaG7kn7-c05aQUpLLk14/edit:
> WebStorm creates patches in diff format. “VCS > Create Patch from Local Changes > Create Patch” to open the “Patch File Settings” dialog .  To span repos, set the "Base path" field to the root of your working copy.  To apply the patch, navigate to the root of the working copy to be patched, then run `patch -p0 < myPatch.patch`. On macOS: `/usr/bin/patch`, and `man patch` to read about the `-p` option.

**Comment by pixelzoom** [comment]
12/10/2020 dev meeting

@pixelzoom I would start by trying to figure out why patches are not working.  If it's a WebStorm bug, report to JetBrains.  As a workaround, try using the command line.

@jbphet suggested creating a temporary branch for collaborating. @zepumph said that's problematic because we're sometimes in multiple repos. 

@samreid will keep this on his radar and investigate the next time he runs into this workflow issue.

**Comment by samreid** [comment]
We also discussed trying zoom remote control.

**Comment by pixelzoom** [comment]
Zoom remote control requires you to explicitly transfer control to the remote user.  As soon as you click on your screen, you take control back.  If one person is driving for a chunk of time, that can work OK.  If you really want to collaborate at the same time, it's a pain.

**Comment by pixelzoom** [comment]
I receiveved an email from JetBrains today, announcing"Code With Me", a new collaborative development and pair programming service: https://www.jetbrains.com/code-with-me/

**Comment by samreid** [comment]
Patches have been working very well, closing.
