### ISSUE TITLE
createSim propagates readmeCreatedManually:true to new sims

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#199]
I see 30 usages of `readmeCreatedManually: true` in package.json files, and it is because the simula rasa package.json has `readmeCreatedManually: true` in it. I think that we can add a simple piece of code to PERENNIAL/createSim that deletes that and keeps this from becoming a bigger problem

Then we need to remove this from other sims already having this problem.

**Comment by zepumph** [comment]
I added code to createSim and removed this from all new sims. Luckily the only ones I found had not been published yet, so there were no changes to the readme files. @samreid will you please review.

**Comment by samreid** [comment]
Good catch! This solution looks appropriate, thanks!  Closing.
