### ISSUE TITLE
Build server is down

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#200]
From https://github.com/phetsims/gravity-and-orbits/issues/345#issuecomment-727232279

> I ran a grunt rc command for gravity-and-orbits about 5 minutes ago, and I haven’t seen any build outputs yet.  I think it normally would have completed by now.  Is anyone aware of build-server outages?  What is the best way to debug this kind of problem?
> 
> I followed the instructions in https://github.com/phetsims/perennial/blob/master/js/build-server/README.md for outputting the build server logs, but they said permission denied, even when I logged in the admin account.

@ariel-phet can you please recommend how to proceed?

**Comment by samreid** [comment]
To clarify, the build command completed with:

```
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.1/phet/gravity-and-orbits_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.1/phet-io/
Please wait for the build-server to complete the deployment, and then test!
```

**Comment by Denz1994** [comment]
Just noting that I ran `grunt rc` for CLB and it successfully deployed and sent me an email. The logs were also captured on our production server. I didn't see any logs for GAO, but @samreid confirmed that a request was successfully sent to deploy to the production server (as noted in his CLI output) during the rc deploy.

**Comment by samreid** [comment]
Working with @Denz1994 and @zepumph, we determined there were unpushed changes in phet-core.  I pushed that and will try again, thanks!
