### ISSUE TITLE
Extract sim screen titles for the translations XML

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#204]
We need to update createTranslationsXML.js to report the translated names for all screens of a sim.  This will require adding screen data to package.json for every sim.  For each sim, for master and each of its active release branches, we need to add an entry like the following to package.json's `phet` object:

```json
screens: [
   { "screenTitleKey": "{{STRING_REPO_NAMESPACE}}/{{screen.name}}" } ...
]
```

For example, here is how area-model-multiplication/package.json would look:
```json
{
...
  "phet": {
    ...
    "screens": [
      { "screenTitleKey": "AREA_MODEL_COMMON/screen.explore" },
      { "screenTitleKey": "AREA_MODEL_COMMON/screen.generic" },
      { "screenTitleKey": "AREA_MODEL_COMMON/screen.game" },
    ]
    ...
  }, ... 
}
```
Once these changes are in place, we can iterate over each of the active release branches and trigger an update to this translated title XML file, then ask the website to syncronize the database with these files.

This is the first step for providing this data in the Simulation metadata service.  @kathy-phet has requested that this be completed by 1/31/2021.

Adding to developer meeting to discuss the best methods for making these changes to all of the branches necessary.

- Should we assign one person to manually go through all sims, or create a chip away task and assign all responsible devs?
- Are there any sims/branches about to be released that are not listed below?

**Comment by mattpen** [comment]
Assigning self to generate a list of all branches that need to be updated.

**Comment by mattpen** [comment]
- [ ] acid-base-solutions 1.2
- [ ] acid-base-solutions master
- [ ] area-builder 1.1
- [ ] area-builder master
- [ ] area-model-algebra 1.2
- [ ] area-model-algebra master
- [ ] area-model-decimals 1.2
- [ ] area-model-decimals master
- [ ] area-model-introduction 1.2
- [ ] area-model-introduction master
- [ ] area-model-multiplication 1.2
- [ ] area-model-multiplication master
- [ ] arithmetic 1.0
- [ ] arithmetic master
- [ ] atomic-interactions 1.1
- [ ] atomic-interactions 1.2
- [ ] atomic-interactions master
- [ ] balancing-act 1.1
- [ ] balancing-act 1.2
- [ ] balancing-act master
- [ ] balancing-chemical-equations 1.2
- [ ] balancing-chemical-equations master
- [ ] balloons-and-static-electricity 1.3-phetio
- [ ] balloons-and-static-electricity 1.4
- [ ] balloons-and-static-electricity master
- [ ] beers-law-lab 1.4
- [ ] beers-law-lab 1.5-phetio
- [ ] beers-law-lab 1.6-phetio
- [ ] beers-law-lab master
- [ ] bending-light 1.1
- [ ] bending-light master
- [ ] blackbody-spectrum 1.0
- [ ] blackbody-spectrum master
- [ ] blast master
- [ ] build-a-fraction 1.0
- [ ] build-a-fraction master
- [ ] build-a-molecule 1.0
- [ ] build-a-molecule master
- [ ] build-an-atom 1.4-phetio
- [ ] build-an-atom 1.5-phetio
- [ ] build-an-atom 1.6
- [ ] build-an-atom master
- [ ] bumper master
- [ ] buoyancy master
- [ ] calculus-grapher master
- [ ] capacitor-lab-basics 1.3-phetio
- [ ] capacitor-lab-basics 1.6
- [ ] capacitor-lab-basics 1.7
- [ ] capacitor-lab-basics master
- [ ] chains master
- [ ] charges-and-fields 1.0
- [ ] charges-and-fields 1.0-phetio
- [ ] charges-and-fields master
- [ ] circuit-construction-kit-ac master
- [ ] circuit-construction-kit-ac-virtual-lab master
- [ ] circuit-construction-kit-black-box-study 1.1-phetio
- [ ] circuit-construction-kit-black-box-study master
- [ ] circuit-construction-kit-dc 1.1
- [ ] circuit-construction-kit-dc master
- [ ] circuit-construction-kit-dc-virtual-lab 1.1
- [ ] circuit-construction-kit-dc-virtual-lab master
- [ ] collision-lab 1.0
- [ ] collision-lab master
- [ ] color-vision 1.1
- [ ] color-vision 1.2-phetio
- [ ] color-vision master
- [ ] concentration 1.3
- [ ] concentration 1.5-phetio
- [ ] concentration master
- [ ] coulombs-law 1.0
- [ ] coulombs-law master
- [ ] curve-fitting 1.0
- [ ] curve-fitting master
- [ ] density master
- [ ] diffusion 1.0
- [ ] diffusion master
- [ ] eating-exercise-and-energy master
- [ ] energy-forms-and-changes 1.4
- [ ] energy-forms-and-changes master
- [ ] energy-skate-park 1.1
- [ ] energy-skate-park master
- [ ] energy-skate-park-basics 1.1
- [ ] energy-skate-park-basics 1.3-phetio
- [ ] energy-skate-park-basics 1.4
- [ ] energy-skate-park-basics master
- [ ] equality-explorer 1.0
- [ ] equality-explorer master
- [ ] equality-explorer-basics 1.0
- [ ] equality-explorer-basics master
- [ ] equality-explorer-two-variables 1.0
- [ ] equality-explorer-two-variables master
- [ ] estimation master
- [ ] example-sim master
- [ ] expression-exchange 1.1
- [ ] expression-exchange master
- [ ] faradays-law 1.3-phetio
- [ ] faradays-law 1.4
- [ ] faradays-law master
- [ ] fluid-pressure-and-flow master
- [ ] forces-and-motion-basics 2.1-phetio
- [ ] forces-and-motion-basics 2.3
- [ ] forces-and-motion-basics master
- [ ] fourier-making-waves master
- [ ] fraction-comparison master
- [ ] fraction-matcher 1.2
- [ ] fraction-matcher master
- [ ] fractions-equality 1.1
- [ ] fractions-equality master
- [ ] fractions-intro 1.0
- [ ] fractions-intro master
- [ ] fractions-mixed-numbers 1.0
- [ ] fractions-mixed-numbers master
- [ ] friction 1.5
- [ ] friction master
- [ ] function-builder 1.0
- [ ] function-builder master
- [ ] function-builder-basics 1.0
- [ ] function-builder-basics master
- [ ] gas-properties 1.0
- [ ] gas-properties master
- [ ] gases-intro master
- [ ] gene-expression-essentials 1.0
- [ ] gene-expression-essentials master
- [ ] graphing-lines 1.3
- [ ] graphing-lines master
- [ ] graphing-quadratics 1.1
- [ ] graphing-quadratics master
- [ ] graphing-slope-intercept 1.1
- [ ] graphing-slope-intercept master
- [ ] gravity-and-orbits 1.1
- [ ] gravity-and-orbits 1.2
- [ ] gravity-and-orbits 1.3
- [ ] gravity-and-orbits master
- [ ] gravity-force-lab 2.2
- [ ] gravity-force-lab master
- [ ] gravity-force-lab-basics 1.0
- [ ] gravity-force-lab-basics master
- [ ] greenhouse-effect master
- [ ] hookes-law 1.0
- [ ] hookes-law master
- [ ] interaction-dashboard master
- [ ] isotopes-and-atomic-mass 1.1
- [ ] isotopes-and-atomic-mass master
- [ ] john-travoltage 1.4-phetio
- [ ] john-travoltage 1.5
- [ ] john-travoltage master
- [ ] least-squares-regression 1.1
- [ ] least-squares-regression master
- [ ] maintenance> gases-intro 1.0
- [ ] make-a-ten 1.0
- [ ] make-a-ten master
- [ ] masses-and-springs 1.0
- [ ] masses-and-springs master
- [ ] masses-and-springs-basics 1.0
- [ ] masses-and-springs-basics master
- [ ] models-of-the-hydrogen-atom master
- [ ] molarity 1.4
- [ ] molarity 1.5
- [ ] molarity master
- [ ] molecule-polarity 1.0
- [ ] molecule-polarity master
- [ ] molecule-shapes 1.2
- [ ] molecule-shapes master
- [ ] molecule-shapes-basics 1.2
- [ ] molecule-shapes-basics master
- [ ] molecules-and-light 1.3-phetio
- [ ] molecules-and-light 1.5
- [ ] molecules-and-light master
- [ ] my-solar-system master
- [ ] natural-selection 1.1
- [ ] natural-selection 1.2
- [ ] natural-selection master
- [ ] neuron 1.1
- [ ] neuron master
- [ ] normal-modes master
- [ ] number-line-distance master
- [ ] number-line-integers 1.0
- [ ] number-line-integers master
- [ ] number-line-operations master
- [ ] number-play master
- [ ] ohms-law 1.4
- [ ] ohms-law master
- [ ] optics-lab master
- [ ] pendulum-lab 1.0
- [ ] pendulum-lab master
- [ ] ph-scale 1.3
- [ ] ph-scale 1.4
- [ ] ph-scale master
- [ ] ph-scale-basics 1.3
- [ ] ph-scale-basics 1.4
- [ ] ph-scale-basics master
- [ ] phet-io-test-sim master
- [ ] plinko-probability 1.1
- [ ] plinko-probability master
- [ ] projectile-motion 1.0
- [ ] projectile-motion master
- [ ] proportion-playground 1.0
- [ ] proportion-playground master
- [ ] ratio-and-proportion master
- [ ] reactants-products-and-leftovers 1.2
- [ ] reactants-products-and-leftovers master
- [ ] resistance-in-a-wire 1.3-phetio
- [ ] resistance-in-a-wire 1.6
- [ ] resistance-in-a-wire master
- [ ] rutherford-scattering 1.1
- [ ] rutherford-scattering master
- [ ] simula-rasa master
- [ ] states-of-matter 1.2
- [ ] states-of-matter master
- [ ] states-of-matter-basics 1.2
- [ ] states-of-matter-basics master
- [ ] trig-tour 1.0
- [ ] trig-tour master
- [ ] under-pressure 1.1
- [ ] under-pressure master
- [ ] unit-rates 1.0
- [ ] unit-rates master
- [ ] vector-addition 1.0
- [ ] vector-addition master
- [ ] vector-addition-equations 1.0
- [ ] vector-addition-equations master
- [ ] wave-interference 2.0
- [ ] wave-interference master
- [ ] wave-on-a-string 1.1
- [ ] wave-on-a-string master
- [ ] waves-intro 1.0
- [ ] waves-intro 1.1
- [ ] waves-intro master
- [ ] wilder master
- [ ] xray-diffraction master

I think this is a list of all active release branches and master, which is where package.json will need to change.

**Comment by jessegreenberg** [comment]
1/14/21 Meeting:

Devs will meet at 10am MT 1/15/21 to discuss the proposal. During discussion on 1/14/21 it wasn't clear whether this could be done by the deadline of 1/31/21, we will discuss that as well.

**Comment by mattpen** [comment]
Chris Malley said:
> If there’s anything that comes up in dev meeting that I need to know about or respond to, please mention me in the associated GitHub issue.

@pixelzoom - We are planning to discuss this issue tomorrow.  This is potentially a chip away task for the entire dev team so we wanted to make sure you were aware and would welcome any input you have.

**Comment by samreid** [comment]
I took this for a test drive in Bending Light, for master and 1.1.  It took about 16 minutes to review the issue and update both.  I couldn't cherry pick due to significant changes in the package.json.

**Comment by pixelzoom** [comment]
I see from the bending-light example that this was added to package.json:

```
    "screens": [
       { "screenTitleKey": "BENDING_LIGHT/intro" },
       { "screenTitleKey": "BENDING_LIGHT/prisms" },
       { "screenTitleKey": "BENDING_LIGHT/moreTools" }
     ]
```

PhET convention is that keys for screen titles have the format "screen.*". Why can't we just extract all matches for that pattern directly from the strings.json files?

**Comment by pixelzoom** [comment]
Also pointing out that there's a problem with bending-light. Those keys should be screen.intro, screen.prisms, and screen.moreTools.

**Comment by pixelzoom** [comment]
I see from the bending-light example that this was added to package.json:

```
    "screens": [
       { "screenTitleKey": "BENDING_LIGHT/intro" },
       { "screenTitleKey": "BENDING_LIGHT/prisms" },
       { "screenTitleKey": "BENDING_LIGHT/moreTools" }
     ]
```

I'm wondering why it's necessary to add that to package.json

First, it's duplicated information.  And if a change is made to strings.json, you now have to remember to also change package.json. 

Second, it seems unnecessarry. PhET convention is that keys for screen titles have the format "screen.*". Why can't we just extract all matches for that pattern directly from the strings.json files?

Finally... There's a problem with bending-light. Those keys should be screen.intro, screen.prisms, and screen.moreTools.

**Comment by samreid** [comment]
Does the metadata require the correct ordering of the screens (array-like), or just the unordered list (set-like)?

**Comment by mattpen** [comment]
> Does the metadata require the correct ordering of the screens (array-like), or just the unordered list (set-like)?

We need to link the screen titles with their position that is used by the screens query parameter.  Including these as an ordered list should accomplish this (albeit with an off-by-one error), but we could also do a set-like representation with additional properties, e.g.:
```
    "screens": [
       { 
           "screenTitleKey": "BENDING_LIGHT/intro",
           "position": 1
       },
       { 
           "screenTitleKey": "BENDING_LIGHT/prisms",
           "position": 2
        },
        { 
           "screenTitleKey": "BENDING_LIGHT/moreTools",
           "position": 3
        }
     ]
```

> First, it's undesriable because it's duplicated information. If a change is made to a screens key strings.json, you now have to remember to also change package.json.

Agreed! I don't like the duplication either and we're open to better solutions.  @chrisklus, @jonathanolson, and I spent about an hour on this and couldn't devise an easy way to parse this automatically.

> Second, it seems unnecessarry. PhET convention is that keys for screen titles have the format "screen.*".

We can get the key's and translated values for all the strings (except when the convention isn't followed) but this does not include vital information:  (a) which sim(s) own a particular screen and (b) the position of the screen within the sim.  Some screen titles have their string stored in a common repo (see the area-model-multiplication example in the first comment).  

> Finally... There's a problem with bending-light - it doesn't follow the naming convention for keys. 

Agreed, and it is not the only sim that breaks with the convention.  EFAC also is missing the `screen.` prefix from screen names.  Fixing this will require a manual review of all screen titles, I think.  If we're going to do this as a chip away task it seems like a great opportunity to address this deficiency.

**Comment by pixelzoom** [comment]
I'm not sure how to address the problems that @mattpen raises in the preceding comment.  But my recollection is that PhET adopted the "screen.*" key convention to make it easy to identify strings that correspond to screen names.  So if we're unable to make use of that convention here, I have another question - why bother with this convention?

**Comment by samreid** [comment]
Would it be worth it spending time applying that convention to all of the branches?  Also, that convention was proposed before we had structured strings.  Should we finish support for translating structured strings, and move toward:

```
screens:{
  intro: ...
  lab: ...
}
```

If we did that, could we rely on the parse order to get the screen indices?

**Comment by pixelzoom** [comment]
> If we did that, could we rely on the parse order to get the screen indices?

From https://www.rfc-editor.org/rfc/rfc7159.txt: "An object is an unordered collection of zero or more name/value pairs ..."

**Comment by mattpen** [comment]
1. Should we assign one person to manually go through all sims, or create a chip away task and assign all responsible devs?

2. Are there any sims/branches about to be released that are not listed below?

It sounds like this is a no, we don't need to handle this for this issue.

3. Does the metadata require the correct ordering of the screens (array-like), or just the unordered list (set-like)?

Let's use an ordered array, and the website metadata service will have knowledge about the off-by-one problem.

4. Should we use structured strings?

We would need support for arrays in our structured string component, and support in rosetta for structured strings.  We would need to move some strings around, if the screen title strings are currently in a common repo.

This could potentially solve the code duplication problem, but it sounds like it would be very expensive to change. @jonathanolson also mentioned that there are potential pitfalls for embedding metadata in our string data.

5. Can we write a script that uses puppeteer to retrieve the information?

Running a sim with `screens={N}` and then pulling `phet.joist.sim.screens[0].name` will provide the English string title.  Can we do a reverse lookup for the key from this and get 90% of the work done?

```
for each sim:
  for each locale:
    i = 0
    while sim run does not fail:
       run sim?screens={i++}
       extract phet.joist.sim.screens[0].name
       // generate screenshots, etc?
```

6. If we're writing this script, can we use it to also generate screen shots?

This is a question for KP/designers. We could also use this to automatically generate localized screenshots (1 per locale) if desired.

7. Should we generate another metadata json file that defines the basic structure of the sim, and is used in main.js?

This could capture things in the future like learning goals and supported query parameters.

**Comment by mattpen** [comment]
```
const puppeteer = require( 'puppeteer' );
( async () => {
  const browser = await puppeteer.launch();
  const simsText = `acid-base-solutions
area-builder
area-model-algebra
area-model-decimals
area-model-introduction
area-model-multiplication
arithmetic
atomic-interactions
balancing-act
balancing-chemical-equations
balloons-and-static-electricity
beers-law-lab
bending-light
blackbody-spectrum
build-a-fraction
build-a-molecule
build-an-atom
bumper
buoyancy
calculus-grapher
capacitor-lab-basics
charges-and-fields
circuit-construction-kit-ac
circuit-construction-kit-ac-virtual-lab
circuit-construction-kit-black-box-study
circuit-construction-kit-dc
circuit-construction-kit-dc-virtual-lab
collision-lab
color-vision
concentration
coulombs-law
curve-fitting
density
diffusion
eating-exercise-and-energy
energy-forms-and-changes
energy-skate-park
energy-skate-park-basics
equality-explorer
equality-explorer-basics
equality-explorer-two-variables
estimation
example-sim
expression-exchange
faradays-law
fluid-pressure-and-flow
forces-and-motion-basics
fourier-making-waves
fraction-comparison
fraction-matcher
fractions-equality
fractions-intro
fractions-mixed-numbers
friction
function-builder
function-builder-basics
gas-properties
gases-intro
gene-expression-essentials
graphing-lines
graphing-quadratics
graphing-slope-intercept
gravity-and-orbits
gravity-force-lab
gravity-force-lab-basics
greenhouse-effect
hookes-law
interaction-dashboard
isotopes-and-atomic-mass
john-travoltage
least-squares-regression
make-a-ten
masses-and-springs
masses-and-springs-basics
models-of-the-hydrogen-atom
molarity
molecule-polarity
molecule-shapes
molecule-shapes-basics
molecules-and-light
my-solar-system
natural-selection
neuron
normal-modes
number-line-distance
number-line-integers
number-line-operations
number-play
ohms-law
optics-lab
pendulum-lab
ph-scale
ph-scale-basics
phet-io-test-sim
plinko-probability
projectile-motion
proportion-playground
ratio-and-proportion
reactants-products-and-leftovers
resistance-in-a-wire
rutherford-scattering
simula-rasa
states-of-matter
states-of-matter-basics
trig-tour
under-pressure
unit-rates
vector-addition
vector-addition-equations
wave-interference
wave-on-a-string
waves-intro
wilder
xray-diffraction
`;
  const sims = simsText.trim().split('\n');
  console.log(sims);
  const locales = [ 'en', 'sq' ];
  for ( let k = 0; k < sims.length; k++ ) {
    const sim = sims[ k ];
    console.log( sim );
    for ( let i = 0; i < locales.length; i++ ) {
      const page = await browser.newPage();
      const s = `https://phet.colorado.edu/sims/html/${sim}/latest/${sim}_all.html?locale=${locales[ i ]}`;
      await page.goto( s );
      await page.waitForFunction('phet');
      await page.waitForFunction('phet.joist');
      await page.waitForFunction('phet.joist.sim');
      await page.waitForFunction('phet.joist.sim.screens');
      const screenNames = await page.evaluate( () => {
        return phet.joist.sim.screens.map( screen => screen.name );
      } );
      console.log( screenNames.length, screenNames );
    }
  }
  await browser.close();
} )();
```

**Comment by mattpen** [comment]
Dev Meeting 1/15:

I'm going to move ahead with using a script like this in the build-server and I'll bring this up again in dev meeting if there are roadblocks. The main concern is build-server performance in a production context.

 There was no clear consensus on a method to retrieve this data without duplicating information (as proposed in the package.json scheme), so we are going to table the discussion of changing the sims to be driven by a data file for now.

**Comment by zepumph** [comment]
In https://github.com/phetsims/joist/issues/603 we updated how the `phet.joist.sim.screens` global operated. Before that issue, the array did not include the HomeScreen as its first element, and after (and on master) it does. I think this is commit where that changed. https://github.com/phetsims/joist/commit/ea3f51d0f497775752d2c86dc46ba995b9167255. Perhaps that will be helpful when getting a consistent API for your screen names.

**Comment by mattpen** [comment]
@samreid - do we need to revert phetsims/bending-light@6e59aeac8b344069ed18e6b30a5d95010a61d23f and phetsims/bending-light@9cc1594139bc37d5a8b98440645662eb23790ff7?

**Comment by samreid** [comment]
Yes, I'll revert those, thanks!

**Comment by mattpen** [comment]
@jonathanolson - When we capture strings by using puppeteer, they are wrapped in what looks like embedding marks.  Do you think these should be stripped out before the strings are stored in the database for the metadata api?

**Comment by mattpen** [comment]
```
blackbody-spectrum
curve-fitting
equality-explorer-two-variables
faradays-law
friction
gravity-force-lab
gravity-force-lab-basics
john-travoltage
molarity
molecules-and-light
neuron
ohms-law
resistance-in-a-wire
```

These sims all have one screen with `phet.joist.sim.screens[0].name`  equal to `null`.  Some other sims with one screen, like area-model-decimals and atomic-interactions, have a named screen, but it generally looks like it is the same as the title of the sim.

Is there a better way to get the screen name for these sims? If not, can I assume that if `phet.joist.sim.screens[0].name` is null and that `phet.joist.sim.screens.length` is 1, that the name of the screen is the same as the title of the sim?

**Comment by samreid** [comment]
Sims with one screen often do not have screen names in the code.  I don’t know what will be best for the metadata service. The cases that have a single, named screen are cases where one screen is reused from another sim.

Here are some choices:
* Metadata service should always return null for screen names for 1-screen sims
* Metadata service should always return the sim name for screen names for 1-screen sims
* For 1-screen sims, the metadata service should use the screen name, if it is defined, otherwise it should return the sim name or null.

I’m not sure how the metadata service will be used, so I’m not sure which is more appropriate.

**Comment by mattpen** [comment]
> Metadata service should always return null for screen names for 1-screen sims

This seems appropriate to me, but we can handle any one of those options on the metadata service side, so I think it is fine to just leave these screen names out or let them be null.

**Comment by jonathanolson** [comment]
> When we capture strings by using puppeteer, they are wrapped in what looks like embedding marks. Do you think these should be stripped out before the strings are stored in the database for the metadata api?

I honestly don't know... what do we do with translated sim titles? Probably whatever we do for that.

**Comment by mattpen** [comment]
Thanks for the comments @jonathanolson @zepumph.  We currently don't store these marks in babel, we don't store them from sim titles in the translations xml, nor do we store or use them in website translation. I think it is a means for simulations to show mixed direction strings.  I'm planning to strip these out for delivery in the API.

**Comment by samreid** [comment]
CT is reporting a lint problem for the commit https://github.com/phetsims/perennial/commit/5c3dec1a0ca90467a6e051711f8b7d254dd33edf

**Comment by mattpen** [comment]
@samreid - `grunt lint-everything` isn't working on my machine at the moment.  Is the error just a missing semi-colon on line 31?

**Comment by mattpen** [comment]
I just pushed fixes for the lint failures.

**Comment by mattpen** [comment]
The partner api now has screen names in the latest version in production, and screen names are automatically updated on production deploys of sims as well as translations. Closing.
