### ISSUE TITLE
How to deal with unpushed commits?

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#205]
Several times in the last few months there have been problems caused by local commits remaining unpushed. This leads to problems and duplication of effort such as in: https://github.com/phetsims/sun/issues/676#issuecomment-765151686

My IDE push dialog takes a long time to populate and doesn't always check all of the repos with commits. 

I'd like to investigate better ways to address this problem.

**Comment by samreid** [comment]
I added a script that quickly pushes all repos with unpushed commits in any branch.  I also unwired the key command for the IDE push dialog.  Hopefully this will help, but I'm also wondering if I should just set up a post-commit hook as described in https://stackoverflow.com/questions/7925850/how-to-automatically-push-after-committing-in-git

**Comment by samreid** [comment]
Here's a patch for parallel push, but it isn't faster (>4 seconds):

<details>

```diff
Index: bin/push-all.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/push-all.sh b/bin/push-all.sh
--- a/bin/push-all.sh	(revision a9a61fe419de511a287cb30ca1a7cca8ce89d6f9)
+++ b/bin/push-all.sh	(date 1611367451675)
@@ -16,15 +16,7 @@
 for repo in `cat perennial/data/active-repos | xargs | tr -d '\r'`
 do
   if [ -d "${repo}" ]; then
-    echo ${repo}
-    cd ${repo} > /dev/null
-
-    if [[ $(git log origin/master..master) ]]; then
-      git push
-    else
-      echo "nothing to push"
-    fi
-
-    cd ..
+    ./perennial/bin/push-fast.sh ${repo} &
   fi
-done
\ No newline at end of file
+done
+wait
\ No newline at end of file
Index: bin/push-fast.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/push-fast.sh b/bin/push-fast.sh
new file mode 100755
--- /dev/null	(date 1611367451672)
+++ b/bin/push-fast.sh	(date 1611367451672)
@@ -0,0 +1,12 @@
+#!/bin/bash
+#====================================================================================================
+#
+# Does a 'git pull --rebase' on every active repo.
+# Use -p option to handle each repository in parallel.
+#
+# Author: Jonathan Olson
+#
+#====================================================================================================
+
+cd $1
+git push
\ No newline at end of file

```

</details>

**Comment by samreid** [comment]
I'll try the "after commit tool" for a bit, combined with the first solution "push all".  So far it seems nice!

![image](https://user-images.githubusercontent.com/679486/105565640-0e2c9100-5ce5-11eb-8465-4ce3a329f246.png)

**Comment by samreid** [comment]
"Run tool" has been working well.  @zepumph also suggested adding "-p" to the `push-all.sh` script like we have done for the `pull-all.sh`.  I'm not opposed to the idea, but I don't think it will speed things up, if we just add an `&` to the push task, since it takes >2 seconds even for unpushed repos.  `push-parallel` adds 2 new files (but each is trivial), but it runs in around 1.2 seconds, and I prefer the output (it is silent except if there is a problem or if a repo is pushed).  Here's a patch for the minimal output for `push-all.sh`:

```diff
Index: bin/push-all.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/push-all.sh b/bin/push-all.sh
--- a/bin/push-all.sh	(revision a9a61fe419de511a287cb30ca1a7cca8ce89d6f9)
+++ b/bin/push-all.sh	(date 1611432504431)
@@ -16,13 +16,11 @@
 for repo in `cat perennial/data/active-repos | xargs | tr -d '\r'`
 do
   if [ -d "${repo}" ]; then
-    echo ${repo}
     cd ${repo} > /dev/null
 
     if [[ $(git log origin/master..master) ]]; then
+      echo ${repo}
       git push
-    else
-      echo "nothing to push"
     fi
 
     cd ..
```

If `push-parallel.sh` is too flaky or requires maintenance, I'll abandon it and work on `pull-all.sh`, but for now it seems OK.  I don't plan any further work for this issue, but thought @zepumph might have suggestions.  @zepumph can you take a look at your convenience?  Feel free to open side issues or close at your discretion.

**Comment by zepumph** [comment]
I'm glad that your platform-specific script is working well! I added `-p` support to push-all.sh by following `pull-all.sh` as a template. It is working well for me, and because git has the local ability to check if there are unpushed changes, it works very fast in the repos that have no commits to push with or without the `-p` option. I also liked your idea of getting rid of the "nothing to push" log.  Closing. Please reopen if you have anything else to discuss.

**Comment by samreid** [comment]
The node script in https://github.com/phetsims/perennial/issues/206 is working well, I decided to try a similar thing for push-all.

**Comment by samreid** [comment]
I committed it and it seems OK in initial testing, running in about half the time of push-parallel

```
~/apache-document-root/main$ time node perennial/js/scripts/push-all.js 

real	0m0.638s
~/apache-document-root/main$ time perennial/bin/push-parallel.sh 

real	0m1.290s
~/apache-document-root/main$ time perennial/bin/push-all.sh -p

real	0m2.246s
~/apache-document-root/main$ time perennial/bin/push-all.sh

real	0m2.172s
```

I'll test in practice over the next few business days.

**Comment by zepumph** [comment]
Did I do something something wrong here? 


```
 Michael ~/PhET/git
 $ node perennial/js/scripts/push-all.js
(node:22364) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'log',
    '--branches',
    '--not',
    '--remotes',
    '--simplify-by-decoration',
    '--decorate',
    '--oneline'
  ]
}

```

**Comment by samreid** [comment]
I suspect the recommendations at the end of https://github.com/phetsims/perennial/issues/206 would address this issue.  Closing.  @zepumph please reopen as appropriate
