### ISSUE TITLE
Make it so execute can run without stopping on first failure on Promise.all

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#207]
From https://github.com/phetsims/perennial/issues/206.  Currently when `execute` is used as a Promise, `Promise.all` fails on the first error.  In order to run `pull-all.js` for https://github.com/phetsims/perennial/issues/206, I'd like to receive a report of the errors rather than fail on the first one.  Hence I'll add an option that lets you resolve on errors.  I'll leave the default as it is now, to reject errors.

**Comment by samreid** [comment]
In the commit, I added an option to `execute` that allows you to resolve instead of reject errors.  I tested in a test harness for https://github.com/phetsims/perennial/issues/206, which I'll commit shortly.  @jonathanolson since you are the original author of `execute`, can you please take a look?

**Comment by jonathanolson** [comment]
Looks like things broke a few things, it used to resolve the stdout value by default (so e.g. getBranch is failing).

example:
```
Jonathans-MacBook-Pro:~/phet/git/bumper # grunt create-release --branch=19.5 --message="Testing"
Running "create-release" task
(Forwarding task to perennial)
Running "create-release" task
>> (node:18098) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
>> (Use `node --trace-warnings ...` to show where the warning was created)
Fatal error: Perennial task failed:
TypeError: stdout.trim is not a function
    at /Users/jon/phet/git/perennial/js/common/getBranch.js:21:98
    at async module.exports (/Users/jon/phet/git/perennial/js/grunt/createRelease.js:44:25)
    at async /Users/jon/phet/git/perennial/js/grunt/Gruntfile.js:230:7
    at async wrap (/Users/jon/phet/git/perennial/js/grunt/Gruntfile.js:63:7)
Full Error details:
{}
Fatal error: perennial grunt "--repo=bumper" "create-release" "--branch=19.5" "--message=Testing" failed with code 1
```

**Comment by jonathanolson** [comment]
Also `assert && assert(` should just be `assert(` in node code.

**Comment by jonathanolson** [comment]
Fixed above. I like the general change and everything else. @samreid can you review my fix?

**Comment by samreid** [comment]
Good catch, thanks for fixing that.  Closing.
