### ISSUE TITLE
There is duplication in opt-out lists.

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#212]
In https://github.com/phetsims/perennial/issues/208#issuecomment-784464694 @zepumph said:

> I'm bummed about duplication of opt out lists.
> 
> https://github.com/phetsims/chipper/blob/ba14aa5aa70c4166a471569cd35d1da89a56fd28/eslint/.eslintignore#
> 
> https://github.com/phetsims/chipper/blob/60ccd7596ac8c4e1f2d5dc91736f1be17923a363/js/grunt/lint.js#L18-L32
> 
> I could not figure out a way to combine the two above lists. Could we work to combine `optOutOfLint` with the list in `lint.js` so that there is only one list for that?

**Comment by samreid** [comment]
I moved 'phet-io-website' from the precommit ignore list to the lint ignore list.  This way the precommit hook doesn't need a lint ignore list any more.  @zepumph can you please review?

**Comment by zepumph** [comment]
Very nice thanks! Having done this work, so you still like the list for `optOutOfReportMedia`? Feel free to close.

**Comment by samreid** [comment]
It's not great, but I don't see a preferable alternative at the moment, I recommend closing and we can re-evaluate if it causes problems in the future.
