### ISSUE TITLE
The grunt generate-data.sh task on bayes often needs help

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#213]
@pixelzoom reported:

> I updated molecule-polarity/package.json at 10:23AM today, added “phet-io” as a supported brand.  What do I have to do to get the PhET-iO Modes to show up in phetmarks?  PhET-iO instrumentation checklist says this should happen automatically.

then later

> Still no update to phetmarks for molecule-polarity. Do I need to manually add it to perennial/data/phet-io ?

then later:

> FYI, the grunt generate-data process must be offline on bayes.  I ran it manually.

I have had similar experiences with this, can we discuss why this process is prone to being offline, making it more robust, or converting it to a manual process?  Assigning @jonathanolson and @zepumph who appear to be authors of the file, but also marking for dev meeting in case that's helpful.

**Comment by jonathanolson** [comment]
Hmm, @zepumph do we get notifications when there is a problem with it?

**Comment by zepumph** [comment]
No. I check on bayes every few months and it always says it is online, but I don't think there is anything set up to know when the task fails. This is the same for daily-grunt-work, which I think broke some time ago but still gets kicked off, failing every night. @jonathanolson how might we be able to set up notifications for these pm2 tasks when things break?

**Comment by jonathanolson** [comment]
Yotta does the following in its error.sh:

```sh
date | /bin/mail -s "[Yotta] $*" ${NOTIFICATION_EMAILS}
```

and reliably pings me whenever an error happens.

**Comment by zepumph** [comment]
I may need a bit more info at some point, but that's enough to get the ball rolling.

**Comment by zepumph** [comment]
I'm going to leave open for dev meeting because I'm totally swamped at the moment. It would be good to just tell devs to manually run generate-data on their own machines when they need to. Or if someone else wants to take the lead on this.

**Comment by pixelzoom** [comment]
Btw...  `cd perennial ; grunt --help` says:

> generate-data  [NOTE: Runs automatically on bayes. DO NOT run locally] Generates the lists under       perennial/data/, and if there were changes, will commit and push. 

That "DO NOT run locally" bit isn't exactly reassuring, and is why I've avoided doing so.

**Comment by jonathanolson** [comment]
> That "DO NOT run locally" bit isn't exactly reassuring, and is why I've avoided doing so. I'm not a fan of things that automatically push before I've had an opportunity to review changes.

The main part of the "do not run locally" is that you WOULD be likely to cause a merge conflict for the process on bayes also trying to update it.

**Comment by samreid** [comment]
At today's dev meeting, we discussed that we would like this to run on the server, but we will need to dedicate time to investigating this.  Until then, it seems we need to run it manually.  If developers run into problems with this, please add a note in this issue and increase the priority.

**Comment by jessegreenberg** [comment]
Dev meeting 4/29/21

@zepumph reiterated https://github.com/phetsims/perennial/issues/213#issuecomment-789937944, and mentioned he wouldn't get to this any time soon.

MK: One way forward would be to move generate-data.sh to "daily grunt work" and then allow people to run it locally. But that isn't ideal.

SR: Should we gravitate towards a philosophy where it is up to the developer who makes a change to run generate-data.sh?

JO: Historically people have been not been running this correctly which is why we wanted to make this an automated task.

MK: Lets say that people should run this locally after making a change that would change data, but still run generate-data daily to catch when people accidentally forget.

MK: Someone should audit generate-data to double check that it is doing too much work and could be more efficient. Maybe we could have developers pull everything and then generate data, instead of having a fresh pull part of the generate-data task.

List of changes from @zepumph if we make this a task that gets run locally.
- Remove the pm2 task on bayes.
- Updates to the perennial/generateData.js to not pull all first.
- Update documentation around processes involved with this change.
- Add to daily grunt work.

@jessegreenberg will do this. I have no experience doing work on bayes, seems like a good place for me to learn. @samreid offered to be the reviewer.

**Comment by zepumph** [comment]
I will just take the pm2 task offline here, since it isn't working anyways. Then all you need to do is update generateData and daily-grunt-work.sh and confirm that's running on bayes.

**Comment by zepumph** [comment]
Stopped and deleted:

<details>

```

 Michael ~/PHET/git/perennial (master)
 $ ssh pabayes
Last login: Thu Apr 29 13:20:44 2021 from cu-vpn-limited-172.21.39.142.int.colorado.edu
[phet-admin@bayes ~]$ pm2 list

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.3.0
Local PM2 version: 4.5.0

┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ continuous-server    │ N/A         │ N/A     │ fork    │ 161052   │ 9D     │ 2    │ online    │ 0%       │ 639.6mb  │ phe… │ disabled │
│ 1   │ generate-data        │ N/A         │ N/A     │ fork    │ 195242   │ 2s     │ 750… │ online    │ 0%       │ 1.3mb    │ phe… │ disabled │
│ 3   │ phettest-server      │ N/A         │ N/A     │ fork    │ 145400   │ 36D    │ 0    │ online    │ 0%       │ 31.5mb   │ phe… │ disabled │
│ 0   │ yotta-server         │ N/A         │ N/A     │ fork    │ 145328   │ 36D    │ 1    │ online    │ 0%       │ 44.6mb   │ phe… │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[phet-admin@bayes ~]$ pm2 stop generate-data

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.3.0
Local PM2 version: 4.5.0

[PM2] Applying action stopProcessId on app [generate-data](ids: [ 1 ])
pm2[PM2] [generate-data](1) ✓
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ continuous-server    │ N/A         │ N/A     │ fork    │ 161052   │ 9D     │ 2    │ online    │ 0%       │ 865.9mb  │ phe… │ disabled │
│ 1   │ generate-data        │ N/A         │ N/A     │ fork    │ 0        │ 0      │ 750… │ stopped   │ 0%       │ 0b       │ phe… │ disabled │
│ 3   │ phettest-server      │ N/A         │ N/A     │ fork    │ 145400   │ 36D    │ 0    │ online    │ 0%       │ 31.5mb   │ phe… │ disabled │
│ 0   │ yotta-server         │ N/A         │ N/A     │ fork    │ 145328   │ 36D    │ 1    │ online    │ 0%       │ 44.6mb   │ phe… │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[phet-admin@bayes ~]$ pm2 delete generate-data

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.3.0
Local PM2 version: 4.5.0

[PM2] Applying action deleteProcessId on app [generate-data](ids: [ 1 ])
[PM2] [generate-data](1) ✓
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2   │ continuous-server    │ N/A         │ N/A     │ fork    │ 161052   │ 9D     │ 2    │ online    │ 0%       │ 669.3mb  │ phe… │ disabled │
│ 3   │ phettest-server      │ N/A         │ N/A     │ fork    │ 145400   │ 36D    │ 0    │ online    │ 0%       │ 31.8mb   │ phe… │ disabled │
│ 0   │ yotta-server         │ N/A         │ N/A     │ fork    │ 145328   │ 36D    │ 1    │ online    │ 0%       │ 44.6mb   │ phe… │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[phet-admin@bayes ~]$

```

</details>

**Comment by jessegreenberg** [comment]
Thanks @zepumph! In https://github.com/phetsims/perennial/commit/30214b75ad2188415ceefabe5a1b21955540ef23 I removed the pull-all and clone-missing-repos part of generate-data. In https://github.com/phetsims/perennial/commit/9ce446be8c2b2a1381d7c2deb19ea138c1f26526 I added it to daily-grunt-work.

I am getting an error when trying to run locally though 
<details>

```
Fatal error: Perennial task failed:
Error: git commit --no-verify -m Automated update of perennial data files in ../perennial failed with exit code 1 and stdout:
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
        modified:   data/phet-io-api-stable

no changes added to commit

    at ChildProcess.<anonymous> (C:\Users\Jesse\Documents\Development\phetsims\perennial\js\common\execute.js:99:21)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
Full Error details:
Error: git commit --no-verify -m Automated update of perennial data files in ../perennial failed with exit code 1 and stdout:
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
        modified:   data/phet-io-api-stable

no changes added to commit
```

**Comment by jessegreenberg** [comment]
After https://github.com/phetsims/perennial/commit/5b9a257acc47ba6c9331524130ac2309a9c44fe2 it worked when I ran it locally and https://github.com/phetsims/perennial/commit/772389e88b8a05daa49bab79f90e4b720aa99f5f was the resulting commit.

@samreid volunteered to be a reviewer in https://github.com/phetsims/perennial/issues/213#issuecomment-829520835, would you mind reviewing? How can we best verify it is working on bayes? Make a change to a sim that would update lists and wait to see if the commit comes through?

**Comment by jessegreenberg** [comment]
I removed interactive-description from example-sim to test this. If we see the perennial lists update with an automated commit from bayes in the next 24 hours hat will confirm it is running. After we can add interactive-description back to example-sim.

**Comment by jessegreenberg** [comment]
I found another reference to this that needed updating in the phet-io-instrumentation-process-checklist in https://github.com/phetsims/phet-io/commit/702d4a01df70924479f843f63de245c62c7e6f3b

**Comment by jessegreenberg** [comment]
I am not seeing an automated commit to perennial for https://github.com/phetsims/example-sim/commit/79b00cf2f68be610f8f115c9c3e6a09de1bbbdf0 so maybe the process isn't running or it hasn't gotten the update. So not ready for review yet, Ill see if I can figure out why.

**Comment by zepumph** [comment]
It's unclear the current status of daily grunt work on Bayes. I haven't checked up on it recently.

**Comment by jessegreenberg** [comment]
I see, thanks. If it were running would it have showed up in the list in https://github.com/phetsims/perennial/issues/213#issuecomment-830276556?

**Comment by jessegreenberg** [comment]
I read through https://github.com/phetsims/perennial/issues/141 and noticed that this is not running with pm2, but is a cron job on phet-admin on bayes. I tried to go to phet-admin on bayes but I don't have permission. I shouldn't/can't poke around any more on my own, will need some help to troubleshoot further.

**Comment by zepumph** [comment]
@jessegreenberg and I went through `daily-grunt-work.sh` and how to use it and how it runs on bayes.

We found two more clean up spots for `generate-data`. We also cleaned up the `automated-grunt-work/` folder. In which there were two messed up repos (coloumbs-law and phet-io-test-sim). There was a merge conflict when pulling, so we recloned.

**Comment by jessegreenberg** [comment]
We ran daily-grunt-work.sh directly on bayes and observed it working through updating npm for its copy and updating copyright dates. We should see it run early tomorrow morning to do the rest.

We also discussed that generate-data.sh can be deleted.

**Comment by jessegreenberg** [comment]
daily-grunt-work.sh hit an error when trying to update copyright dates that looks like
![errors](https://user-images.githubusercontent.com/6396244/119382803-8c4b7500-bc90-11eb-844c-a7c2c0dd1d23.png)

But these errors do not appear when running daily-grunt-work.sh directly with grunt in the automated-grunt-work folder. Perhaps this is an issue with cronjob.

**Comment by jessegreenberg** [comment]
Maybe we need to use the full path to grunt to allow it to run in cron?
https://askubuntu.com/questions/604438/command-works-on-terminal-but-doesnt-work-in-cron and https://stackoverflow.com/questions/17735043/running-grunt-and-node-as-batch-files-through-cron

`which grunt` yields `/usr/bin/grunt`, I might try replacing `grunt` with `/usr/bin/grunt` in daily-grunt-work.sh.

**Comment by zepumph** [comment]
Sounds like a great idea! Good luck and thank you.

**Comment by jessegreenberg** [comment]
Thanks! Using the path to grunt in https://github.com/phetsims/perennial/commit/6d934dc9ef9cc017b3e4d2a761e06f84d8fae274, lets see if that does the trick.

**Comment by jessegreenberg** [comment]
That didn't fix it. To debug a bit further I temporarily added a task to crontab that lints molecules-and-light with -v and got this more verbose output:
![image](https://user-images.githubusercontent.com/6396244/119540273-45768180-bd5b-11eb-95ae-d0d394b31239.png)

**Comment by jessegreenberg** [comment]
I think I need some help here again, does anyone know why this error might happen when running from cron but not when run directly from command line?

**Comment by jessegreenberg** [comment]
Inspecting Page.js, line 707 is at the catch in 
```js
let payload;
try {
    payload = JSON.parse(event.payload);
}
catch {
    // The binding was either called by something in the page or it was
    // called before our wrapper was initialized.
    return;
}
```

**Comment by jessegreenberg** [comment]
bayes is using node at version 14.15.0, but the cronjob is using node at 8.17, Using `which node` I see that bayes is using node at /usr/local/bin/node and the cronjob is using node at /usr/bin/node. So we need to set the path to node in our crontab I think.

**Comment by zepumph** [comment]
You probably already know this, but you can `node` the `grunt` runnable like ` node node_modules/grunt/bin/grunt`, so perhaps it is just that simple, like `/usr/local/bin/node` `/usr/bin/grunt` . . . .

**Comment by zepumph** [comment]
But better yet, @mattpen, can we get the cronjobs on bayes phet-admin to use the newer version of node and grunt?

**Comment by jessegreenberg** [comment]
> You probably already know this, but you can node the grunt runnable like...

Thanks! I did not know that, but doing that much fixed the problem just when linting a single sim from cron.

**Comment by jessegreenberg** [comment]
@mattpen said on slack
> I just looked into this briefly, it looks like the easiest way to go is to just specify absolute paths rather than relying on $PATH.  I can look into it some more if this is problematic

In the above commit I changed the task to use paths to node and grunt we want to use in the cronjob.

**Comment by zepumph** [comment]
This is unfortunate because we have lost a way to test this locally. If I continued to maintain this file, I would definitely prefer to have a way to run this file locally.

**Comment by jessegreenberg** [comment]
Understood - I can't spend more time on this this week, but I am seeing references to being able to set the PATH from crontab, Ill try this out later. https://stackoverflow.com/questions/23834276/how-to-set-path-variable-in-crontab-via-whenever-gem

**Comment by zepumph** [comment]
I wanted to note that it isn't a pure win, but I also don't see myself running this locally anytime soon. I definitely think this is in a much better state than it was! Thanks for all your hard work.

**Comment by mattpen** [comment]
It looks like you can set environment variables directly in crontab.  The current value of $PATH was `/usr/bin:/bin`.  I added this line to the top of the crontab: `PATH=/usr/local/bin:/bin:/usr/bin`, as apparently you can't use the `/some/path:$PATH` expansion in crontab.  When you call node in phet-admin's crontab now, it will point at `/usr/local/bin/node`.  I don't think we ever needed full paths for `grunt`, as that lives in `/usr/bin`, but it seems to be working now as well.

I tested by adding this crontab job:
```
*/1 * * * * cd /data/share/phet/automated-grunt-work/perennial; node -v >> ~/pathvar.txt; grunt --version >> ~/pathvar.txt
```

which results in pathvar.txt that looks like:
```
$ cat pathvar.txt
v14.15.0
grunt-cli v1.2.0
grunt v1.4.1
```

**Comment by jessegreenberg** [comment]
Excellent @mattpen, thanks! I will revert the change and then verify tomorrow that grunt tasks ran from daily-grunt-work.sh from the cron job.

**Comment by jessegreenberg** [comment]
I am seeing commits coming in regularly form the daily task, and I just checked the log and saw no errors. It is working well, closing.
