### ISSUE TITLE
Automated maintenance process may be deploying phet-io brand when it shouldn't

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/perennial#215]
Noticed while using the automated maintenance process for https://github.com/phetsims/phetmarks/issues/48. One of the release branches failed to build a phet-io brand sim, but it was found that that release branch probably shouldn't include phet-io anyway. From https://github.com/phetsims/phetmarks/issues/48#issuecomment-792963400

> The most recent CLB version published for PhET-iO is 1.6. How was phet-io brand added to 1.7 as a supported brand by the MR process? I look at the phet-io deploy status as well as the master phet-io spreadsheet and neither have 1.7 on it? I see 1.7 is not currently published for either brand (last RC was phetsims/QA#588), but dev test on the way? (phetsims/QA#616).
> Over to JO with two questions:
> - How do we make sure phet-io isn't attempted to be published on branches that don't support it?
> - Is CLB being published with PhET-iO? Because I didn't think so.

Assigning to @jonathanolson and @zepumph.

**Comment by jonathanolson** [comment]
> How do we make sure phet-io isn't attempted to be published on branches that don't support it?

It's an unpublished release branch, so the maintenance process has to kind of "guess" what to build for it. Since its package.json marks it as phet-io, it builds it, but it WILL NOT deploy anything, because it's an unpublished release branch.

> Is CLB being published with PhET-iO? Because I didn't think so.

Last I heard, no, the next version wouldn't include phet-io.

So, once CLB is published (with phet-brand only), it will show up in MR as phet-brand only.

**Comment by zepumph** [comment]
So only for unpublished versions does this happen, which is fine for the RC, and may result in a bit of confusion for the spot check, presumably you could remove a supported brand manually if you noticed it. Is that right @jonathanolson? I feel like we should close this issue as a wontfix.

**Comment by jonathanolson** [comment]
Clarification: The automated maintenance process doesn't even RC unpublished versions. It won't deploy them.

It WILL show up in the maintenance tools as "phet,phet-io", even if it will only by a phet-brand sim. But it shouldn't affect things deployment-wise.

**Comment by samreid** [comment]
Based on the remarks above it seems this issue can be closed as wontfix.
