### ISSUE TITLE
Promise executor functions should not be async

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#216]
From https://github.com/phetsims/chipper/issues/814, I tried enabling `no-async-promise-executor` and saw 3 problems in perennial:

```
/Users/samreid/apache-document-root/main/perennial/js/build-server/taskWorker.js
  291:30  error  Promise executor functions should not be async  no-async-promise-executor

/Users/samreid/apache-document-root/main/perennial/js/grunt/PDOMComparison.js
  148:23  error  Promise executor functions should not be async  no-async-promise-executor

/Users/samreid/apache-document-root/main/perennial/js/grunt/decaf/getPreloads.js
  16:23  error  Promise executor functions should not be async  no-async-promise-executor
```

ESLint says https://eslint.org/docs/rules/no-async-promise-executor

> The executor function can also be an async function. However, this is usually a mistake, for a few reasons:
> 
> If an async executor function throws an error, the error will be lost and won't cause the newly-constructed Promise to reject. This could make it difficult to debug and handle some errors.
> If a Promise executor function is using await, this is usually a sign that it is not actually necessary to use the new Promise constructor, or the scope of the new Promise constructor can be reduced.

I assigned to the primary authors of the files, can you please take a look?

**Comment by zepumph** [comment]
PDOMComparison may not run right now, but I fixed that lint rule.

**Comment by mattpen** [comment]
f3e53bcfe27512695a12fa198647e147f4479217 should fix the lint issue.  I switched to using the `fs.promises` API over using the `graceful-fs` api wrapped in an async function wrapped in a Promise.  There were some issues with race conditions during file creation in this part of the process during the chipper-2.0 sprint, and the klugey promise/async wrappers were a leftover and failed attempt to fix those issues.  Hopefully, switching to the `fs.promises` api doesn't reintroduce those, but I need to verify that before publishing this.

I need to make sure that builds work:
(a) if there is no temporary build directory
(b) if there is a previous build directory that did not get cleaned up
(c) for a sim with a new name
(d) for a sim with an existing name and a new version
(e) for a sim with an existing name and existing version (in the filesystem, i.e. a redeploy of a build failure) 

(c) may be difficult to test, I may just need to be on hand the next time we do a production deploy of a new sim.

**Comment by mattpen** [comment]
I was not able to run tests due to https://github.com/npm/cli/issues/3044, but there have been several successful translations and RCs since I deployed this.  I think we can close this issue and address any problems if they come up.
