### ISSUE TITLE
Move phet-io tests under phet-io section

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#217]
In https://github.com/phetsims/phet-io/issues/1741, I noticed some phet-io tests that are not listed with the main phet-io tests.

**Comment by samreid** [comment]
Fixed in the commit. I'm unfamiliar with this file, so a quick spot check would be nice.  @zepumph and @jonathanolson both have commits in this area, so I'll assign to them.

**Comment by jonathanolson** [comment]
Looks good to me!

**Comment by samreid** [comment]
Thanks, closing.
