### ISSUE TITLE
Delete deprecated instructions from build-server/README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#218]
Can this be deleted from https://github.com/phetsims/perennial/blob/master/js/build-server/README.md? 

> !!!DEPRECATED!!! - figaro has been decommisioned and simian is nearing end of life. To start, stop, or restart the build server on figaro or simian, run this command: sudo /etc/init.d/build-server {{start|stop|restart}}

**Comment by mattpen** [comment]
These have been removed, neither of these servers is currently running the build-server
