### ISSUE TITLE
Build server is not sending email notifications

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#219]
I published molecule-polarity 1.1.0-rc.1 today and received no email notification.

@samreid reported:
> I also ran a build this morning, which looked successful, but I didn’t get an email notification like I usually do

The log shows ECONNRESET error when attempting to send email:
 
```
% sudo journalctl -u build-server -f
...
> Mar 22 10:13:38 phet-server.int.colorado.edu build-server[28967]: info: build for molecule-polarity finished successfully
Mar 22 10:13:38 phet-server.int.colorado.edu build-server[28967]: info: attempting to send email
Mar 22 11:54:52 phet-server.int.colorado.edu build-server[28967]: error: error when attempted to send email, err = Error: read ECONNRESET
Mar 22 11:54:52 phet-server.int.colorado.edu build-server[28967]: error: error when attempted to send email, err = Error: no connection has been established
```

I'm not sure who is responsible for build-server, so I'll start by assigning to @jonathanolson and @mattpen.

**Comment by pixelzoom** [comment]
I'm not sure who is responsible for build-server, so starting by assigning to @jonathanolson and @mattpen.

**Comment by jonathanolson** [comment]
This doesn't look critical, and I'm not as familiar with build-server as @mattpen (so I'll defer to him).

**Comment by zepumph** [comment]
This occurred just now in my recent build of Ratio and Proportion 1.0.0-rc.4.

**Comment by zepumph** [comment]
My logs were a bit different, they end with "attempting to send email" and don't get an error. Perhaps because it was only 10 minutes ago (and the connection hasn't reset yet). Likely the same error.

```
Mar 22 16:59:17 phet-server.int.colorado.edu build-server[28967]: debug: stderr is empty.
Mar 22 16:59:17 phet-server.int.colorado.edu build-server[28967]: debug: stdout is empty.
Mar 22 16:59:17 phet-server.int.colorado.edu build-server[28967]: info: build for ratio-and-proportion finished successfully
Mar 22 16:59:17 phet-server.int.colorado.edu build-server[28967]: info: attempting to send email

```

**Comment by pixelzoom** [comment]
I published Molecule Polarity 1.1.0-rc.2.  I never received email notification.  This time I see what @zepumph reported in https://github.com/phetsims/perennial/issues/219#issuecomment-804454012.  There is no ECONNRESET in the log, just "attempting to send email", followed by nothing:

```
Mar 25 19:10:44 phet-server.int.colorado.edu build-server[28967]: info: build for molecule-polarity finished successfully
Mar 25 19:10:44 phet-server.int.colorado.edu build-server[28967]: info: attempting to send email

```

**Comment by zepumph** [comment]
Yes, this is the same behavior I see in the logs for Ratio and Proportion 1.0.0 production deploy I just did. @pixelzoom  if you look at the timestamps, the ECONNRESET is something like a timeout 40 minutes later or so.

**Comment by mattpen** [comment]
OIT ticket: [INC0726665](https://colorado.service-now.com/sncms/view.do?sysparm_document_key=task,204ed1101bdfe410fe790f6cdc4bcbdb)

**Comment by mattpen** [comment]
I worked on this again today and found a problem with the port configuration after the upgrade to the latest version of emailjs, and email started working after I started using the correct ports.  

This is currently blocked by #216.

**Comment by mattpen** [comment]
This was fixed some time ago. Closing.
