### ISSUE TITLE
maintenance release doesn't fully run on Windows

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#22]
There is an issue where npm install doesn't work on Windows due to some oddness about invoking it from scripts.  As of this writing, the problematic code looks like this:

``` js
this.execute( 'npm', [ 'install' ], '../' + repo, function() {
        callback();
      } );
```

@jonathanolson put a workaround for a similar issue into test-server.js in chipper, and it looked like this:

``` js
  var npmInstall = spawn( 'node', [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js', 'install' ], {
    cwd: rootDir + simName
  } );
```

This is, however, not a portable solution.  We need to figure out something that will work on Windows as well as Unix-ish machines (i.e. OSX and Linux).

**Comment by jbphet** [comment]
@jonathanolson found this and thinks it might be related: https://github.com/nodejs/node/issues/3675.

**Comment by jonathanolson** [comment]
I believe this is fixed, closing.
