### ISSUE TITLE
Change wording of prompt in production.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#230]
Running `grunt production` (production.js) prompts the user with:

> Are there no untested maintenance patches that need spot checks? (An issue would be created in the sim repo) [y/N]?

Every time I see this, I have to read it at least twice. It's a double negative.  How about changing this prompt to the following?

> Have all maintenance patches that need spot checks been tested? (An issue would be created in the sim repo) [y/N]?

I would have changed this myself, by because it's in perennial, I wasn't sure if changing would mess something up.

**Comment by jonathanolson** [comment]
Changed above, thanks. Closing.
