### ISSUE TITLE
When updating the PhET-iO spreadsheet, make sure the text and link are both updated

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#233]
When updating the PhET-iO spreadsheet, make sure the text and link are both updated.  @kathy-phet said:

> One thing I noticed in the PhET-iO simulations spreadsheet is that you had updated the text [to 1.5], but it was still linked to 1.4. I fixed that, but its something we need to be aware of... cell should be cleared entirely before doing the paste of the new version to avoid this issue. Can you note that in the process deployment docs.

**Comment by samreid** [comment]
Proposed fix is in the commit.  @zepumph can you please spot check?

**Comment by zepumph** [comment]
Seems right to me! Thanks
