### ISSUE TITLE
dot and kit units test are looking for chipper/js/SimVersion.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#238]
dot-tests.html and kite-tests.html are both pointing to 

```js
'../chipper/js/SimVersion.js',
```

... which does not exist.  This results in a 404 error when running those tests.

**Comment by samreid** [comment]
Fixed and ready for review.  scenery/ did not seem to have the same problem.

**Comment by pixelzoom** [comment]
👍🏻
