### ISSUE TITLE
Can we trim "unneeded" repos from active-repos?

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#239]
I was recently downloading a new checkout of the codebase on to a different computer, and I was surprised to see that the apps were in this list. I recommend the following thoughts:

1. Remove repos from active repos that the core, sim-development team doesn't need to have in actice-repos.
2. Create a new list called `all-repos`, which we use the script I wrote over in phet-info to populate with literally all non-archived phetsims repositories (https://github.com/phetsims/phet-info/blob/master/sim-info/getAllRepos.js).
3. Potentially rename active-repos, but that is a total pain that would need an MR to achieve fully, so I'd say lets not.

Marking for dev meeting to see if people agree with this.

**Comment by samreid** [comment]
We also saw a way to list all repos in https://github.com/phetsims/special-ops/issues/201#issuecomment-902319277

```
gh repo list phetsims -L 500
```

**Comment by samreid** [comment]
In dev meeting:

MK: Is this list trying to be all repos, or all repos related to sim development?
SR: It would be nice to prune this as much as possible.  What would go wrong if we remove the apps from active repos?
MP: I don't really use active-repos, you can take them out.
SR: Would we want to change the name if we also change the semantics?
MK: I'd like to keep the name as active-repos
MP: Smithers is website helper tools.  It probably doesn't need to be in active-repos.

So we will change the semantics for active-repos to mean "active-repos for sim development".  It will no longer include apps, website supporting material, etc.  People can list all repos via the GitHub CLI: `gh repo list phetsims -L 500`

MK: proposes removing:

* the android app
* the iOS apps
* smithers
* weddell
* yotta (doesn't depend on perennial at the moment)

**Comment by jbphet** [comment]
We discussed this in today's dev meeting and decided that we can remove:
- the android app
- the iOS app
- smithers

The others should probably stay because of dependencies and the need to keep an eye on them.

Weddell's size should be reduced in the future so that it doesn't take so long to clone.
