### ISSUE TITLE
update dual

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#241]
From https://github.com/phetsims/chipper/issues/1018

Now that we have perennial-alias, we can optimize dual/ and its contents around it.

**Comment by samreid** [comment]
I updated the documentation.  The main other aspect to consider is whether we should move execute.js and SimVersion.js to other directories since they no longer need to be in dual/.  Dual is clear to me that they have this different usage style, but that's probably just because I'm used to it.  I wouldn't want everything usable by perennial-alias to be in dual/.  @jonathanolson or @zepumph can you recommend what package(s) execute.js and SimVersion.js should be in?

**Comment by zepumph** [comment]
I think we should deprecate dual. We can search for usages of `perennial-alias` to understand all files that are used by our versioned code. 

>...what package(s)...

Is that what you mean? Or did you want me to say "joist and chipper, and likely others."

**Comment by samreid** [comment]
Sorry, holdover from talking about "packages" terminology in Java.  I'm wondering what directory those files should move to.

**Comment by jonathanolson** [comment]
execute/simVersion could presumably move to js/common (since they're used by grunt stuff, build-server stuff, externals, etc.)

**Comment by samreid** [comment]
Thanks, I'll do that in a separate issue.  Closing.
