### ISSUE TITLE
Move execute and SimVersion to js/common/

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#246]
From https://github.com/phetsims/perennial/issues/241#issuecomment-933651581 @jonathanolson said:

> execute/simVersion could presumably move to js/common (since they're used by grunt stuff, build-server stuff, externals, etc.)

**Comment by samreid** [comment]
Pushes complete, @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
Looks good to me, everything working after pull. Thanks!
