### ISSUE TITLE
Prototype type deployments are not updated by the maintenance tools

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#249]
While performing a maintenance release to address https://github.com/phetsims/tambo/issues/151 and subsequently https://github.com/phetsims/tambo/issues/152, I noticed that the greenhouse-effect phet brand prototype, which is version 1.0, was not being deployed as part of the process.  The phet-io version _was_ being deployed.  I discussed this with @jonathanolson, and our best guess is that prototypes are likely not being patched during the maintenance release process, probably because they don't appear in the metadata from the website.

We should figure out what exactly is going on and fix the process so that prototypes _are_ patched and redeployed.

For reference, the prototype deployment process is described [here](https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md#prototype-deployments) (note that this is a living document, so this link could go bad at some point).

**Comment by jessegreenberg** [comment]
Discussed 10/14/21:

JB: How many prototypes would need to be patched if we were to fix this?
MP: Currently there are three.
MP: We could add a query to fix this so that we can maintain published prototypes. Should be pretty easy for me to support this. Whatever queries are used by the batch MR process would need to be change to use this.

Assigning to MP to add the query parameter. Then JO will update the batch maintenance release process as needed.

**Comment by mattpen** [comment]
From Developer meeting discussion:

> 
> JO: Also, prototype deployments are not maintenance released. They are missing a flag in the website APIs.
> CM: It was mentioned that MR are not necessary for prototype deploys. We should check with management that it is necessary.
> MP: The website should be set up to support this. Updating the MR process should be all that we need to do.
> JO/MP: Technical details about maintenance releasing chains/bumper and authentication.
> MP: I’ll add details about the query parameter in https://github.com/phetsims/perennial/issues/249. We can discuss there whether the existing query parameter is sufficient for this need.

**Comment by mattpen** [comment]
I noticed today that simMetadata.js is still using API v1.0, which doesn't support the query parameter that would fetch prototype sims (`includeUnpublished`).  Ideally we should upgrade simMetadata to use v1.3, which introduces some breaking changes.  If this is prohibitively expensive, we could retrofit 1.0 to support this parameter but that is not preferable.

**Comment by jonathanolson** [comment]
Updated above, this will include them in the RCs/deploys. I'm handling everything needed for the current maintenance release. Thanks @mattpen!
