### ISSUE TITLE
Add npm prune for automated maintenance release process

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#25]
See https://github.com/phetsims/chipper/issues/445 for details on why this is needed.

Will want "npm prune" before every "npm install".

**Comment by mattpen** [comment]
"npm install" was still failing when switching from an older version of chipper to a newer during deploys.  This problem appeared to be remedied by using update instead of install.

**Comment by jonathanolson** [comment]
@mattpen or @samreid, should I still prune before 'npm update', or is 'npm update' sufficient? This will need to switch between new and old versions of chipper (before/after grunt update).

**Comment by mattpen** [comment]
@jonathanolson - We found that for the build-server, both 'npm prune' and 'npm install' were needed to successfully run grunt with the appropriate version.  In a context that is not switching between two versions of grunt, this may not be necessary.

**Comment by jonathanolson** [comment]
Did this in https://github.com/phetsims/perennial/commit/4d60c1abbbaeb48e6ad8bf8df8821b30b6099046.
