### ISSUE TITLE
Minor logging update for pull-all.js

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#261]
I have been seeing that a couple of "Already up to date" lines have been sneaking through for my git bash on windows, related to https://github.com/phetsims/perennial/blob/a2a1a6c8b2b47e303c34a508fcf1c96b799515fb/js/scripts/pull-all.js#L35-L37. Can we be a bit more graceful with an `includes( 'up to date')`?

**Comment by zepumph** [comment]
@samreid, does this feel alright to you?

**Comment by samreid** [comment]
I see the problem and it is probably OK, but maybe we should guard ourselves by explicitly listing them.  For example, what if in git 2.31 they change the wording to "The repo is not up to date", then this would misclassify it.  Can we just try to list out the problematic lines explicitly?

**Comment by zepumph** [comment]
I believe that the contents were different because I had unpushed changes in a non-checked out branch. I have since fixed that, so there are no more to update at this time. I reverted the commit.
