### ISSUE TITLE
Email notification failed from build-server

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#265]
I deployed geometric-optics 1.1.0-rc.1 today.  The deployed files look correct.  But I never received an email confirmation.    Here's the log (`XXXXXX` is a potential password that I've redacted.)

```
% ssh -l malleyc phet-server2.int.colorado.edu
% sudo journalctl -u build-server -f
...
info: build for geometric-optics finished successfully
Mar 18 14:42:29 phet-server2.int.colorado.edu build-server[886175]: info: attempting to send email
Mar 18 14:42:30 phet-server2.int.colorado.edu build-server[886175]: error: error when attempted to send email, err = Error: authorization.failed (bad response on command 'XXXXXX': #5.7.0 Authentication failed)
```

**Comment by zepumph** [comment]
>(bad response on command 'XXXXXX': #5.7.0 Authentication failed)

@pixelzoom and I think the `XXXXXX` part may be a password. If this is the case @mattpen, could we get that out of the log in the future?

**Comment by mattpen** [comment]
I think both issues should be fixed, the bad email password and the logging of the password in plain text.  The logs with the old password were deleted upon the last log rotation. I successfully ran an RC and production deploy for chains to test. Closing.
