### ISSUE TITLE
Remove productionServerName

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#267]
We don't use this anymore, and @mattpen says we can delete it. This also exists in our build-local. 

It is only used in error logging, so perhaps we can use productionServerURL instead?

**Comment by zepumph** [comment]
We can also factor out usages of phet-server2 while we are at it.

**Comment by mattpen** [comment]
@zepumph - I think your commit should be sufficient, I can't find any uses of this property in master across all our repos.  Is this ok to close?

**Comment by zepumph** [comment]
`phet-server2` as a string is in quite a few spots (35) right now, but it doesn't seem obvious how I would factor it out, most of it is in documentation or code comments. Or in different applications (MR process vs build-server etc). If we need to change the server again, presumably we would easily find these usages and change them too.
