### ISSUE TITLE
ts-status shell script

### ISSUE THREAD

**Issue by marlitas** [phetsims/perennial#274]
A shell script that counts and keeps track of javascript and typescript lines of code and percent completeness in relevant common code repositories. 

Info tracked:
- ts LOC
- js LOC
- % Complete
- @ts-ignore
- @private

**Comment by zepumph** [comment]
Now ts-ignore and private searches are only in typescript files.

**Comment by jonathanolson** [comment]
Added some additional review notes above.

**Comment by marlitas** [comment]
@jonathanolson Looked into the use of Number() vs. parseInt() and it seems like it's very dependent on context. Here is a pretty thorough [discussion on stackOverflow. ](https://stackoverflow.com/questions/4090518/what-is-the-difference-between-parseint-and-number)

General overview from my understanding:
- Number() is type conversion
- parseInt() parses the string to return a number
- Number() will return NaN if parameter contains a letter or symbol or not a number in string.
- parseInt() will return a number all the way up to the nearest symbol or letter.
- parseInt() can take a radix as a second argument, Number() cannot

Might require further discussion to determine which is better for PhET use, but I went with Number() because it would return NaN if an incorrect string was passed in and would be easier to trace errors. But maybe there's a more efficient way to do this?

**Comment by jonathanolson** [comment]
I wasn't actually familiar that parseInt would ignore certain content in the string (eek).

It looks like `Number(...)` is equivalent to a + operator cast. Since it NaNs more easily, it seems better to use in general for numbers. Perhaps we could add an integer variety that only outputs integers.

Might be worthy of dev meeting discussion.

**Comment by marlitas** [comment]
Created new issue for dev meeting discussion. https://github.com/phetsims/perennial/issues/275

**Comment by marlitas** [comment]
TS-Status script is completed and reviewed. Closing.
