### ISSUE TITLE
Number() vs. parseInt()

### ISSUE THREAD

**Issue by marlitas** [phetsims/perennial#275]
This issue comes from a discussion in: https://github.com/phetsims/perennial/issues/274

What is the best string => number conversion for PhET usage. A couple of things to note that have come up from initial discussions/research:
- parseInt() can ignore content in a string to return a number (not great)
- Number() returns a NaN if string has symbols that do not equate to numbers ( is equivalent to a + operator cast)

Historically PhET devs have preferred parseInt(), should that change?

**Comment by zepumph** [comment]
When converting, let's also remember to search for parseFloat, and Number.parseInt.

**Comment by marlitas** [comment]
@jbphet discovered an infinite loop in Expression Exchange that we traced back to another inconsistency between parseInt() and Number().
Below screenshot demonstrates the issue as it relates to Expression Exchange. 

![Image](https://user-images.githubusercontent.com/42476338/174163405-8b41ae37-7ee5-472e-8e5a-189e8ed9e9db.png)

PSA:
Number( '' ) => 0
vs.
parseInt( '' ) => undefined

**Comment by zepumph** [comment]
From dev meeting today. @marlitas is still chipping away at this. Moving to subgroups

**Comment by marlitas** [comment]
Conversion done. Will leave issue open for a few days in case something comes up that I didn't see in testing.

**Comment by marlitas** [comment]
I did not find any CT errors related to the Number() conversion in the last few days. Closing
