### ISSUE TITLE
hook-pre-commit.js does not print tsc errors by default

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/perennial#277]
`tsc` errors are only printed if `outputToConsole` is true.

https://github.com/phetsims/perennial/blob/master/js/scripts/hook-pre-commit.js#L101-L107

Would it be OK if we always print tsc errors? hook-pre-commit.js always reports lint errors so I had expected tsc errors to always be reported as well. Without printing I had thought that hook-pre-commit.js was failing silently somewhere. If there is a failure to commit it is nice to be told where it is without needing to run `tsc` again.

**Comment by jessegreenberg** [comment]
I removed the `outputToConsole` check so it always prints if there is error. @samreid are you OK with this?

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
