### ISSUE TITLE
Precommit hooks should run from perennial-alias instead of perennial

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#278]
From https://github.com/phetsims/chipper/issues/1286 we identified that the precommit hooks `node ../perennial/js/scripts/hook-pre-commit.js` are loading files from chipper and aqua:

```js
const lint = require( '../../../chipper/js/grunt/lint' );

// ....
const reportMedia = require( '../../../chipper/js/grunt/reportMedia' );

// ...
if ( fs.existsSync( '../chipper/tsconfig/all/tsconfig.json' ) ) {

// ...
const results = await execute( 'node', [ '../../../chipper/node_modules/typescript/bin/tsc' ], '../chipper/tsconfig/all', {

// ...
const puppeteerQUnit = require( '../../../aqua/js/local/puppeteerQUnit' );
```

Generally, perennial should not import from chipper. But it is OK for perennial-alias to import from chipper.  Rather than move all these processes to perennial, it seems like the precommit hooks should run from perennial-alias.  This will also allow us to run precommit hooks while in maintenance SHAs, which we have wanted to do but not had a reliable way to do so.

Heads up to @zepumph and @jonathanolson

**Comment by zepumph** [comment]
While this is true, and  we talked about this on Friday, we also said that it would be buggy if you had sim shas checked out and tried to commit in a repo on master (like perennial or aqua). Does this seem like an important case?

**Comment by samreid** [comment]
I recall that conversation and wanted to discuss a bit further.

Let's say we have checked out maintenance SHAs for gravity-and-orbits and we want to commit a change to perennial.  On the maintenance SHAs chipper/eslint has a rule that requires us to use `type` instead of `interface`.  But in master, chipper/eslint has a rule that requires us to use `interface` instead of `type`.  So the precommit hooks will fail.  The problem is the inconsistency of having the precommit hooks in perennial run rule sets and implementations from chipper SHAs.  The solutions are:

* Move everything (eslint, rules, our custom rules, type checker, unit test harness, etc) to perennial so perennial can use the master version while maintenance SHAs use the maintenance version.
* Only commit to perennial/master when dependencies such as chipper are also checked out to master.  This is akin to saying work will be done in perennial-alias.

Based on these considerations, I'm planning on doing more things in perennial-alias and only using perennial for the small subset of operations that deal with checking out and managing maintenance SHAs.  Specifically, at the moment I have `perennial-alias` excluded in my IDE and navigate/work in `perennial`, so I would switch that.  Likewise, on the command line, I typically navigate to `perennial` to run `grunt lint-everything` but maybe I should do this from `perennial`.

**Comment by samreid** [comment]
In today's meeting, we agreed to move precommit hooks, absolute-tsc, and other code that uses ../chipper over to chipper itself.

**Comment by samreid** [comment]
@marlitas and I moved:

* precommit hooks, and the multi-script
* absolute-tsc

We do not think the build-server commands should be moved.  We are uncertain about these remaining usages of `../chipper` in perennial:

* ChipperVersion
* outputJSAll
* Gruntfile/lint

@jonathanolson what do you recommend for these parts?

**Comment by marlitas** [comment]
@samreid and I discussed and side issues can be created for `ChipperVersion`, `outputJSAll`, `Gruntfile/lint` if we decide to move them to chipper in the future. Closing.
