### ISSUE TITLE
Add build-server status report

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#298]
@zepumph and I thought that an http endpoint that returns a simple report of the build-server's queue status would be a nice-to-have feature.

>   https://phetsims.slack.com/archives/C6HPE0J91/p1672936506159459?thread_ts=1672875653.698849&cid=C6HPE0J91
> 
> Michael Kauzmann
> Yeah, perhaps a "currentState" or "log" or "debug" endpoint that gives some json info from a browser?
> 
> 
> Matt Pennington
> Probably wouldn’t be hard to add a path like [phet.colorado.edu/build-server/status](http://phet.colorado.edu/build-server/status) that is just a simple text list or even json array of the current queue and maybe some timing
> 
> 
> Michael Kauzmann
> I like it! Likely not urgent, but a fun idea. Up to you.

This would be pretty quick to knock out in tandem with [parallel checkouts](https://github.com/phetsims/chipper/issues/1112).

This would be useful for quickly determining status during batch translations and maintenance releases, where we currently have to manually parse through the build-server logs on phet-server2

**Comment by mattpen** [comment]
I was able to get a quick report working that shows the current build and any builds in the queue and the times they were added to the queue.  Some additional features that might be nice: error status on failed builds, historical log of prior builds and their success/failure status.  Adding more features will probably tilt the scales toward setting up a simple DB table to manage this rather than a file.

I'll be testing this out today on phet-server-dev.

**Comment by mattpen** [comment]
Looks like it is working nicely.  Here is the output for 3 builds (all identical) on ox-dev:

<img width="598" alt="image" src="https://github.com/phetsims/perennial/assets/11747676/8789ad87-08cc-4be9-8d8c-1fcbacaa010b">

**Comment by mattpen** [comment]
I deployed this to phet-server2 (our production instance) and it is working well there too.  It needs an update to the varnish config to be accessible from outside the server.  I'll deploy that change tonight after hours.

**Comment by mattpen** [comment]
This was deployed to production tonight. Closing.

**Comment by zepumph** [comment]
Could you post a link to this? Either in slack or this issue?

**Comment by zepumph** [comment]
https://phet.colorado.edu/deploy-status
