### ISSUE TITLE
[build-server] add option for adding email to build fail list

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/perennial#3]
Discussed over Skype that it would be useful to be notified of some build fails but not all. 

>CM: 'd like to be notified of the build status of my own builds, but not particularly interested in other builds. would it be possible to add an optional mailTo address to build-local.json, that gets passed through to build-server?

**Comment by aaronsamuel137** [comment]
Added a --email option to grunt deploy-production. Anything else we should do here? Do we want to send an email on build success too?

We could also add a field in build-local.json so that a desired email is always passed automatically to deploy-production every time.

Assigning to @pixelzoom for review since he suggested this change.

**Comment by pixelzoom** [comment]
I think it would be great to send an email on success.  That way you get an email either way, indicating how things went, and you'll know when the process has completed.

**Comment by aaronsamuel137** [comment]
Added email on build success, as well as an optional field in build-local.json, buildServerNotifyEmail, which will automatically pass an email every time so you don't need to add --email.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I don't see the `email` option described in the `grunt --help` for `deploy-production`.  

Also, the original request was for an option in build-local.json. Any chance that we could add that, with the ability to override via `--email`?

**Comment by aaronsamuel137** [comment]
There is a new optional field in build-local.json, buildServerNotifyEmail, if you want to be notified by default if your deploy-production succeeds or fails. If you are on the default email list you will get all failure notices, but not success ones.

Discussed with @pixelzoom, closing.

**Comment by pixelzoom** [comment]
Reopening. This is not working for me.  I've added buildServerNotifyEmail to $HOME/.phet/build-local.json, and have yet to receive an email. Searching for "buildServerNotifyEmail" through all .js yields not found.  And build-server.js includes this documentation:

```js
 * Include these fields in build-local.json to enable sending emails from build-server on build failure.
 * They are only needed on the production server, not locally. A valid emailUsername and emailPassword are needed to authenticate
 * sending mail from the smtp server, though the actual emails will be sent from 'PhET Build Server <phethelp@colorado.edu>',
 * not from the address you put here.
 * {string} emailUsername - e.g. "[identikey]@colorado.edu"
 * {string} emailPassword
 * {string} emailServer - (optional: defaults to "smtp.colorado.edu")
 * {string} emailTo - e.g. "Me <[identikey]@colorado.edu>, Another Person <person@example.com>"
```

So I'm confused. There is no buildServerNotifyEmail field documented. And there are other fields that I thought had gone away.

@aaronsamuel137 ?

**Comment by pixelzoom** [comment]
My bad. I was on a chipper sha dates 11/10/15 that precedes the addition of buildServerNotifyEmail.

Closing.
