### ISSUE TITLE
Adding branch protection changes to a fix process

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#306]
@jessegreenberg can you review the incoming commit on this issue? I'm curious if this will cause issues (it seems to do the job properly).

**Comment by jonathanolson** [comment]
Also, perhaps they should live in a common place if so? `githubProtectBranches` could also potentially expose more functionality to the outside than just a single function.

**Comment by jessegreenberg** [comment]
fixDivergedReleaseBranch looks very nice - good documentation and code is easy to read. I exported a new function to clear branch protections for repos, protectGithubBranches.js exports `protectBranches()` and `clearBranchProtections()` now if that is helpful.

But using octokit here is also fine and I can't think of any problems with this.

**Comment by jonathanolson** [comment]
Sounds good, thanks!
