### ISSUE TITLE
remove unused code and dependency

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#33]
The file `build-server.js` has a require statement for pg-query, and the it appears to configure a query but never use it.  The actual code looks like this:

```js
var query = require( 'pg-query' ); // eslint-disable-line
   .
   .
   .
// configure postgres connection
if ( BUILD_SERVER_CONFIG.pgConnectionString ) {
  query.connectionParameters = BUILD_SERVER_CONFIG.pgConnectionString;
}
else {
  query.connectionParameters = 'postgresql://localhost/rosetta';
}
```

I've looked through the history of the code and the query code was originally added on 10/27/2015 (commit 5ac71c3601835d6b0a8163cbbc80d2b669a2fb07) in order to put translation credits into the database.  However, the current version of the code adds translation credits by using a URL to our server.  It looks like the code that makes the query was removed, but the code that includes it and sets it up was not.

I'm going to remove it, then work with @mattpen to get this inspected and tested.

**Comment by jbphet** [comment]
I've addressed this issue and have tested on ox-dev, see https://github.com/phetsims/perennial/issues/32#issuecomment-280130531 for details.  Assigning to @mattpen to inspect changes and do any further testing he things is necessary.  Once he approves, we should make the changes live on phet-server and close this.

**Comment by mattpen** [comment]
@jbphet - I reviewed https://github.com/phetsims/perennial/commit/14730564e405afd183182f2530bfb9c43a98ad46 and it looks good to me.  I also reviewed the logs from the test on phet-server-dev and everything looks like it is working as expected.  I believe this is ready for deployment on phet-server.

**Comment by jbphet** [comment]
I've pulled these changes on to phet-server and restarted the build server, and ran a successful test build.  All looks good at this point.  Closing, will reopen if any problems are found as a result of these changes.
