### ISSUE TITLE
Production deploys publish from the dependencies on the tip of the branch, not from provided dependencies

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#334]
@jonathanolson @samreid @jbphet and I found a bug where production versions of phet and phet-io brand sims have rc test version. 

For example https://phet.colorado.edu/sims/html/calculus-grapher/1.0.3/calculus-grapher_all.html points to 1.0.4-rc.1.

This is since parallel checkouts on the build server in https://github.com/phetsims/chipper/issues/1112

Also tagging https://github.com/phetsims/perennial/issues/332

We should outfit ReleaseBranch.updateCheckout() to support provided dependencies.

**Comment by zepumph** [comment]
https://github.com/phetsims/perennial/commit/3b46d4d0e6e841cc522445e663cbdf644473bce1 fixed this bug as far as we can tell by testing on ox-dev. We kicked off  chains deploy after making an RC, and confirmed it didn't push the RC changes to production. I just pulled the changes onto the production build-server and all seems good. I published chains 1.44 to production on the main production build-server. I think we are ready to close, and I will do a bit of damage searching on the phet-io side over in https://github.com/phetsims/special-ops/issues/249.

**Comment by zepumph** [comment]
@jonathanolson, is there anything else here?

**Comment by zepumph** [comment]
Notes while implementing:

<details>

```

chains current version - 1.44.5
push bad dependency onto release branch 1.44
	chains good 09c109a60c999d35c173d27d5880ae9a5d305279
		    bad  9cab75e700494615a368e1494421c66a3df2ddc1 (has the doc)	
		    other bad bfa0b6e51060268f85a7c196986a9933b999612e (rc version update)
	scenery good bb2ea3a8c08144267b1ec8c4755c1e96d3825080
		    bad 7f2042f86171c08543c6c75f0698e9be4a2c6db7
1. make local rc which will update the version rc. 
	on tip: version 1.44.6-rc.1

(3) ox-dev
	run translation (from ox-dev) make sure it doesn't have our bad commit.

(2)



1. RC works
3. buggy case fixed 
2. Production works

**Comment by jonathanolson** [comment]
Looks good to me!
