### ISSUE TITLE
Rename '/data/share/phet/phet-repos'?

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#34]
I have found that this folder name is misleading. It is named as though anything on the server could access the repo needed to access its content. Recently I was told that in fact this is not the case, because the build-server uses these repos to checkout shas and make production builds.  Maybe it would be more clear to rename this to 'phet-repos-for-build-server' or 'phet-repos-no-touching' or something to dictate how it's off limits. Then we could have another folder called 'come-one-come-all-for-the-phet-repos-that-you-need'. This directory could server all of our other phet-repo needs on phet-server. Here are the cases I have run into so far:

* phet-io-website ( to deploy to the static dir)
* phet-office-mix (for the chron job that updates the store.html)
* installer-builder (perhaps deprecated because it is running on bayes now)

All of these currently have a top level directories in `/data/share/phet/`. This seems like a slippery slope to me. Marking for developer meeting to discuss some organization of `phet-server:/data/share/phet/`

**Comment by mattpen** [comment]
It seems to me like `perennial-repos` may be more accurate and we should repurpose `phet-repos` for general use.  

However, I don't think the three repos you mentioned should be affected by perennial because sims should  not be dependent on them and vice versa.  We are currently running rosetta in the phet-repos directory and it hasn't caused any problems. 

Is there a use case other than perennial where a repo that runs an application on phet-server is dependent on a sim repo?

**Comment by jonathanolson** [comment]
A similar example on bayes.colorado.edu: I have `/data/share/phet/continuous-testing` with checked-out repos for continuous testing, and `/data/share/phet/yotta-statistics` similarly for yotta.

Following that pattern, would `/data/share/phet/build-server` be sufficient?

Additionally, this may be an issue for phettest.colorado.edu (`/home/mendeleev/git`), although I've been the only one maintaining that for now.

**Comment by zepumph** [comment]
>However, I don't think the three repos you mentioned should be affected by perennial because sims should not be dependent on them and vice versa. 

phet-io sims have a dependency on phet-io-website for the devguide documentation.

**Comment by samreid** [comment]
`/data/share/phet/build-server` sounds fine to me

**Comment by samreid** [comment]
@zepumph says: `data/share/phet/perennial-repos/`

**Comment by zepumph** [comment]
Consensus was to discuss further with @mattpen and @jbphet about naming. @samreid and I think that it makes sense to have every use case have its own directory from `/data/share/phet`. So the phet-io-website and all repos needed for that use case (even though it is just the one repo) will live in `/data/share/phet/phet-io-website/` and the same for the installer-builder, and then also for perennial. This just makes it much more explicit who is allowed to use the content of each folder. That seemed to be a general consensus but please chime in if not.

**Comment by jbphet** [comment]
I've looked into this a bit, and realized what was nagging at me about this.  Rosetta (the translation utility) also runs from these repos, and though it interacts with the string files directly through github, there is a file that is shared between Rosetta and the build-server called `simInfoArray`, and there is code in both code bases that uses a relative path to get to that file.  This is perhaps a bit of a brittle architecture and should be remedied at some point, but this is unlikely to change in the near future.  With this in mind, can we rename the directory to either 'perennial-and-rosetta-repos' or the more generic 'build-server-and-translation-server-repos'?  I'd be okay with either.

**Comment by samreid** [comment]
I'd prefer not to have to change the name twice.  Perhaps we can call it "perennial-repos" for now, and document that rosetta currently uses perennial repos?  Hopefully it is not too much work to get rosetta using its own copy of `simInfoArray`?

**Comment by jbphet** [comment]
Renaming it twice wouldn't bother me, but if it's troubling to others, I'd be okay with renaming it to 'perennial-repos' and having Rosetta continue to run out of there until I or someone else takes the time to pull it into a separate directory.  I've logged an issue for Rosetta that describes roughly what would need to be done, see https://github.com/phetsims/rosetta/issues/148.

**Comment by samreid** [comment]
> Renaming it twice wouldn't bother me, but if it's troubling to others,

I'd be ok with it being renamed twice, may be best if it will be a while for the rosetta issue to be fixed.

**Comment by zepumph** [comment]
Is it as easy as a 'mv' command? I like 'perennial-and-rosetta-repos' for now, I don't think it matters too much,  and I don't mind renaming it twice. I just worry a bit about flat out naming it without 'usage' search. Perhaps aliases will change if they point in that folder. Otherwise can anyone think of any dangers of just renaming as is?

**Comment by samreid** [comment]
Presumably the build server and rosetta services would have to be updated to point to the new location and restarted.

**Comment by zepumph** [comment]
Yeah I would assume so, but I'm not the guy to ask. I searched our repos for 'phet-repos' and this is all that came up. Readme files (some of which shouldn't be pointing there anyways. I'll fix this). I think that it's important to get @mattpen and @jbphet in on this conversation.

![image](https://cloud.githubusercontent.com/assets/6856943/24155568/d6faf51e-0e19-11e7-9948-4b82ca661aa0.png)

**Comment by mattpen** [comment]
We would also need to update the RHEL service files for rosetta and phet-server, at the same time that we actually rename the repos.

**Comment by zepumph** [comment]
Perhaps just renaming it once is smarter.

**Comment by mattpen** [comment]
Do rosetta and phet-server need to be able to access the same instance of simInfoArray.json in real time?  Or can they just work from the latest version of it in github (meaning separate directories would be fine)?  It looks like it only changes whenever a production sim is published.

**Comment by jbphet** [comment]
Let's just rename it once, and I'll make it a priority to pull rosetta into a separate directory area.  I'll add the code to pull simInfoArray before each new publication attempt, and we should be golden.

**Comment by zepumph** [comment]
Assigning to @jbphet to let us know when rosetta is out of this dir.

**Comment by mattpen** [comment]
Removing assignment, please let me know if I can be of assistance.

**Comment by zepumph** [comment]
@jbphet what is the status on this, what can I do to help?

**Comment by jbphet** [comment]
@zepumph - it just keeps getting put off for higher priority items.  You're welcome to just do it if you have the time and inclination.  If this has become a high priority and you need my input, let me know and we'll put it at the top of the list.  If you're just trying to reduce the number of items assigned to you, go ahead and remove your assignment, and I'll take care of it when some time is set aside for translation.

**Comment by zepumph** [comment]
Sure thing. There is no rush, I just had a bit of time and was organizing. Let me know when this gets done or if you want my input.

**Comment by jbphet** [comment]
**Note:** When rosetta is moved and its systemctl files are updated, the same actions need to be done on ox-dev to keep them in sync.

**Comment by jonathanolson** [comment]
No strong preferences.

**Comment by pixelzoom** [comment]
No preference, I didn't know this directory existed.

**Comment by mattpen** [comment]
I would prefer not to change the directory name at this time, for reasons stated above.

**Comment by zepumph** [comment]
@pixelzoom suggested making a readme file for the top of that directory saying "These are for the build server, don't use them."  We all agree, @mattpen volunteered to take this on.

**Comment by mattpen** [comment]
I added the following to `/data/share/phet/phet-repos/README`:

```
The phet-repos directory is intended for exclusive use by the build-server application.  Any changes to this directory should be made
only by the phet-admin user.  The repos in this directory are not guaranteed to stay on any particular branch or SHA at any point in t
ime. For further details see ./perennial/js/build-server/README.md.
```
