### ISSUE TITLE
daily grunt work maintenance

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#353]
I constantly apply some changes as problems occur with daily grunt work. I'll post commits here.

**Comment by zepumph** [comment]
Today I was able to reproduce that the reopen github issues with TODO script was sending along a URL like `29`. Instead of `https://github.com. . . . `. I added another logging step to see if that helps. I can't find any interesting usages of `29` in kite, which is where the bug co-located (based on other TODO issues).

**Comment by zepumph** [comment]
Things looked good last night. Closing

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
