### ISSUE TITLE
How to identify branches that need manual maintenance release patches

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#36]
When a fix needs to be pushed out (e.g. recently https://github.com/phetsims/phet-android-app/issues/16, https://github.com/phetsims/phetcommon/issues/37, https://github.com/phetsims/vibe/issues/30, https://github.com/phetsims/special-ops/issues/68), I've patched master and every release branch for every live simulation.

This currently misses simulations that have a different branch (or are not on the website yet) for RCs, e.g. https://github.com/phetsims/graphing-slope-intercept/issues/17.

What's the best way to handle identifying all of the extra branches that I'd need to patch (new sims with an RC branch, existing sims with a newer RC branch like BASE, etc.)?

**Comment by samreid** [comment]
RCs should be deployed from a release branch, so how are they being missed?

**Comment by jonathanolson** [comment]
> RCs should be deployed from a release branch, so how are they being missed?

e.g. graphing-slope-intercept, as it has never been deployed to production, so the website/DB doesn't have any information about branches.

Or also say balloons-and-static-electricity, where it successfully patches 1.1 (the live version), but 1.2 was branched before the patches were applied and is in RC testing.

**Comment by samreid** [comment]
Can you query the git repo for branches and use our naming conventions in order to see which branches need work?

**Comment by jonathanolson** [comment]
> Can you query the git repo for branches and use our naming conventions in order to see which branches need work?

Sounds like you're proposing trying to patch any repo that acts like a sim that has a release-like branch (and patching all branches for existing sims that are greater or equal to the production version?)

This could probably be done, but would need to either be a "what did the automated process miss, and fix it manually", or heavily modify the automated process (it assumes it only has to patch one branch per sim, so it would need refactoring).

**Comment by pixelzoom** [comment]
4/20/17 dev meeting:

• @jonathanolson will send an email to phet-dev when a patch is eminent. 
• Developers will decide whether they have anything in QA that needs patching.
• @phet-steele will be added to phet-dev mailing list.
