### ISSUE TITLE
reopenIssuesFromTODOs no longer works

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#362]
This is because `saveTODOIssues` environment variable no longer propagates now that grunt tasks are in separate processes.

**Comment by samreid** [comment]
Maybe we just need to make sure the env propagates through.

**Comment by zepumph** [comment]
I'll check back in tomorrow to see if this worked.

**Comment by zepumph** [comment]
I see that the script is now writing the TODO issues to chipper/dist nightly. The next issue is that bayes is still running node v16.
