### ISSUE TITLE
Move our typescript system to perennial

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#364]
From https://github.com/phetsims/chipper/issues/1464. Instead of using tsc from chipper, we need this to be in perennial so we can use typescript in perennial.

- [ ] ~Also phet-core/types should move to perennial~ let's chat in https://github.com/phetsims/perennial/issues/371
- [x] Move check.ts from grunt check to perennial (done in https://github.com/phetsims/chipper/issues/1487
- [x] Copy chipper/tsconfig history to perennial/tsconfig
- [x] New thing in chipper's grunt file to forward to perennial-alias. For linting and type checking.
- [x] lint and lint-everything and type checking should use __dirname so it works in perennial and alias
- [x] move chipper's package.json's typescript entry to perennial. rm -rf node modules for a thorough test
- [x] search for usages of `tsc` and move to perennial. Use `grunt check` too
- [x] update documentation about how tsc works.
- [ ] eslint may have a peer dependency on this, just check it and be aware. Notify @zepumph if lint problems like that are discovered.
- [ ] ~Delete chipper/tsconfig/ and point all usage sites to perennial-alias~ UPDATE: Chipper and buildtools config should live in chipper.

**Comment by zepumph** [comment]
Looking at this now.

**Comment by samreid** [comment]
- [ ] check https://github.com/phetsims/website-common/blob/32301078d3eeb8c47b17f2b75507ea1069fc653e/git-template-dir/hooks/pre-commit#L1-L9 with @zepumph

**Comment by zepumph** [comment]
- [ ] https://github.com/phetsims/chipper/commit/81ff4eac80b76455c9c2a4533c95032d661db67b is the right fix, but why didn't this line catch the error? https://github.com/phetsims/perennial/blob/bd47b68ff2afdcf26dacefe2b77a00d49b87e5bb/js/grunt/check.ts#L70

**Comment by zepumph** [comment]
All that is left here:
- [ ] Move tsconfig/buildtools/ back to chipper

**Comment by samreid** [comment]
I moved tsconfig/buildtools/ back to chipper. While I was here I converted copy-history-to-repo from *.js to *.ts and ran it with sage run. Closing.

**Comment by zepumph** [comment]
We still have TODOs, pointing here. Reopening.

**Comment by samreid** [comment]
I addressed the TODO in the commit. buildtools/tsconfig.json was already in chipper (and used), we just needed to remove the leftover one in perennial. Closing.
