### ISSUE TITLE
Factor out usages of child_process spawning

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#373]
In the last month or two, many more copies of spawn() have been hard coded into our processes. This is because `execute` is unwieldy and heavy weight, and it too scary to change. At this time we have 8 copies of `spawn` in chipper and perennial. Let's also look at `exec` and `execSync` is we are so inclined.

**Comment by samreid** [comment]
In my opinion, `execute` is problematic and should be avoided:

```
    // {'reject'|'resolve'} - whether errors should be rejected or resolved.  If errors are resolved, then an object
    //                      - of the form {code:number,stdout:string,stderr:string} is returned. 'resolve' allows usage
    //                      - in Promise.all without exiting on the 1st failure
```

It sounds like we were unaware of `Promise.allSettled`.

```
childProcessShell: cmd !== 'node' && cmd !== 'git' && /^win/.test( process.platform )
```

This option is never exercised.

```
      stderr += data;
      grunt.log.debug( `stderr: ${data}` );
      winston.debug( `stderr: ${data}` );
```

Why do we have 3 channels for the stderr?

Why have an option that radically changes the behavior? Is `ExecuteError` valuable?

In my opinion, it is clearer and more idiomatic to use `spawn` directly. We should learn to use it and become comfortable with it. The main/only thing we should factor out to `spawn` usages is `shell: /^win/.test( process.platform )`

**Comment by zepumph** [comment]
Ok. I believe that this has all been sorted. My favorite parts of this changeset are simplifying the options in execute() to just pass through any and all childProcess options, including stdio: 'inherit' and to have execute support that. Love that! From there, I feel like `typeCheck` and `transpile` cleaned up pretty well. 

`getReposWithWorkingCopyChanges` was a bit more of a wash, but I like having one way of doing things, and feel like manually writing execute() commands made me understand what the "&&" was actually doing for the bash command (I totally didn't understand that the first one could send back a non zero exit code also). 

Anything else you see here?

**Comment by samreid** [comment]
This is very great, nice work. What do you think of aligning the APIs even more and moving the `cwd` from a required top-level parameter into the nested `childProcessOptions`? If we want all call sites to have to pass cwd, then we can keep it in the options but `Require` it. Not necessary but I thought I would get your opinion about it.

**Comment by zepumph** [comment]
I don't think it is worth the API change, and I also don't like promoting the child process options to a required piece of the api, it seems like it breaks encapsulation. 

Thanks!
