### ISSUE TITLE
Use different names for tasks and modules

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#375]
I have been getting pretty confused quite often working in perennial grunt tasks. For example: `lint.ts` lives in perennial. and is a module in js/grunt/ as well as a task in `js/grunt/tasks/`. This means that when I search for lint, I see this in webstorm:

![image](https://github.com/user-attachments/assets/949c4328-fc5e-49be-b286-621bdbaeb940)

Maybe we can keep the tasks name the same, and have a convention for what the module is called:

`lintModule`
`linter` (checker, modulifier, etc)

@samreid is curious if we can reuse the same file.

**Comment by zepumph** [comment]
- [ ] One step to do here is look through all modules at top level of `js/grunt/` and if the only usage is the task, then inline it.

**Comment by samreid** [comment]
The first problematic occurrence in chipper is `generate-a11y-view-html.ts` which calls `generateA11yViewHTML.ts` and has 2x usage sites so cannot be inlined.

I think the names are reasonable here since the camel casing differentiates. My only other idea about how this could be better is to do like python's `if __name__ == '__main__'`. In Node.js I believe it would be something like:

```
if (require.main === module) {
  ...
}
```

We have previously decided against this, but it could solve the proliferation of files problem. But I think we also added other lint rules to prevent from importing from `grunt/tasks`, which we would have to undo/rethink. @zepumph what do you advise?

**Comment by zepumph** [comment]
I totally agree with you about the above. I believe that all that is left here is to audit grunt current grunt tasks for any others that do not need the module, and that can indeed be appropriately inlined without much risk that someone is going to want to use it as a module in the future. Note that this is worthy because many grunt tasks modules were created to keep too much logic out of the top level giant grunt file (very reasonable). This is not longer needed. 

For example, it was nice to not need a module in reopen-issues-from-todos, where it was obvious that the 100 lines of code were just used as a module to keep them out of the perennial gruntfile. (only slightly moot now that it is a script and not a grunt task). 

Are there any more like this?

**Comment by samreid** [comment]
I finished going through the chipper tasks. In perennial, we can likely inline:

- [ ] checkoutMainAll
- [ ] cherryPick
- [ ] createOneOff
- [ ] createSim
- [ ] generateData
- [ ] shaCheck

**Comment by zepumph** [comment]
I think we should inline all the above except:

**Comment by zepumph** [comment]
I see two patterns that I think would be good to align:

Sometimes we export the task promise named `moduleTask`, and somtimes it is just `module`

https://github.com/phetsims/perennial/blob/8ed959fbbba5741f5b5100adca92dd17fc19ad5e/js/grunt/tasks/lint.ts#L18

https://github.com/phetsims/chipper/blob/029ea52/js/grunt/tasks/report-media.ts#L18

Can we determine which way is best. Also, could we just export default instead of naming it?

**Comment by zepumph** [comment]
@samreid and I tried to use `export default` but couldn't get type info to work correctly. So instead we settled on `modulePromise`. One example committed and the rest can be done async.
