### ISSUE TITLE
Convert execute commands from node to tsx

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#379]
From https://github.com/phetsims/chipper/issues/1481. We have 36 occurrences of 'node'. Not all should change to tsx, but some should.

Use `tsxCommand` where appropriate.

**Comment by samreid** [comment]
There were only 2 relevant ones. There will be more in https://github.com/phetsims/chipper/issues/1506.  @zepumph want to review? Close if all is well.

**Comment by samreid** [comment]
By the way, I tested precommit-hook-multi at runtime but did not test Snapshot.js at runtime.

**Comment by zepumph** [comment]
Snapshot has been getting tested for the last week due to ct getting restarted on sparky. I don't see any other trouble here. Thanks!
