### ISSUE TITLE
builds should not overwrite /latest/ redirect rules if version number is <= currently deployed version

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#38]
We just ran into an issue where version 1.0.8 of Function Builder was essentially overwritten by a deployment of 1.0.7.  Our best guess as to the cause of this is that the link for the build request got pasted into Skype and something crawled the chat and hit the link.  The build server code should probably be modified to prevent deployment over top of any existing previous deployment, and the failure should cause an email notification to be sent.

**Comment by jbphet** [comment]
@zepumph was proposing using a POST message.  Assigning to him to elaborate.

**Comment by jbphet** [comment]
On 2nd thought, using a POST is a separate thing.  Assigning to myself for now, and will ping @zepumph about creating an issue about using POST.

**Comment by jbphet** [comment]
@jonathanolson points out that the build server *does* need to support overwriting of existing version for translations.  This may have to be a special case for the English version of the simulation.  Marking for discussion at dev meeting.

**Comment by mattpen** [comment]
@jonathanolson - is this handled in the perennial grunt tasks now?  Or does it need to be added to the build-server?

**Comment by jonathanolson** [comment]
> @jonathanolson - is this handled in the perennial grunt tasks now? Or does it need to be added to the build-server?

I believe JB's recommendation was for the build-server to prevent the deployment.

I can actually imagine that this may be less-than-desirable if we need to publish maintenance release for older phet-io versions.

@mattpen, is it possible to just prevent the part that sets what the "latest" version is on the website? @jbphet, would this be sufficient?

**Comment by jbphet** [comment]
@jonathanolson - when you say "@jbphet, would this be sufficient?", I'm not quite clear on what "this" is.  Can you please clarify?  The specific case that I we are hoping to avoid is when a build request for an older version ends up overwriting a published newer version.  If the chipper 2.0 code prevents this, and notifies the one who made the request via email, we should be good.

**Comment by jonathanolson** [comment]
> The specific case that I we are hoping to avoid is when a build request for an older version ends up overwriting a published newer version.

Every deploy puts the newly deployed things into a versioned directory. So if we deploy 1.2.0 first, it goes under `htdocs/sims/html/${sim}/1.2.0/`. Then a later deployment to 1.1.5 would go to `htdocs/sims/html/${sim}/1.1.5/` and should not overwrite files.

There IS the potential issue where the .htaccess file would change (which defines what `/latest/` goes to), and there is also the issue that it might contact the website and tell it that the (old) version is the newest version (which would be incorrect).

It's the build-server and/or its communication with the website that handles the .htaccess changes AND the version updates in the website, so it's not in chipper code I can change that.

My proposal is that deploying an older version is allowed, but that it should not change the .htaccess or change what version the website thinks is the latest.

**Comment by jbphet** [comment]
@jonathanolson said:

> My proposal is that deploying an older version is allowed, but that it should not change the .htaccess or change what version the website thinks is the latest.

Sounds great.  I probably shouldn't have used the term "overwrite" because you're right - it wasn't actually getting overwritten on the file system.  The publication process was just causing the most recently built version to be the one at the "lastest" link, and it sounds like your proposal solves that problem, so it sounds good to me.

**Comment by jonathanolson** [comment]
That's build-server/website side, so I'm unassigning myself and leaving @mattpen assigned.

**Comment by mattpen** [comment]
I've added checks to the code that rewrites the .htaccess file for the /latest/ directory.  The website is already handling these requirements. I'm planning to test on ox-dev later today.

**Comment by mattpen** [comment]
The changes have been successful for deploys of chains.  I'm going to deploy this on production and close the issue.
