### ISSUE TITLE
gruntSpawn arg forwarding bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#386]
From https://github.com/phetsims/perennial/issues/385. We cannot assume that we can alwasy clip the first three args from `process.argv`.

**Comment by zepumph** [comment]
@samreid had a nice idea to make unit tests for this function. Love it!

**Comment by samreid** [comment]
Create a node unit test that runs `grunt test --hello=true` and `grunt --test=hello` and make sure the args go through (note the second one runs the default task).  Also test `grunt default --test=bye`.

Test all the above cases with `grunt`, `node grunt`, `sage run` and `tsx`.

**Comment by samreid** [comment]
In this issue, I factored out `testGruntOptions` and moved it without history to perennial. Then I added test-exec-sync.js and documentation at the top of perennial-alias/js/test/perennial-tests how to run it. It covers the bases in https://github.com/phetsims/perennial/issues/386#issuecomment-2450859674. Note that sage and tsx don't have "default" so we only have 6 test entry points.  @zepumph can you please review?

**Comment by zepumph** [comment]
@samreid and I discussed the above, and tests were updated. Things are passing, are simpler, and work on windows. Closing
