### ISSUE TITLE
Cloudflare should ignore the build-server deploy status page

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#387]
@samreid and I found this file was getting cached, and so we needed to either use `phet-origin` or add a query parameter to actually see the build-server status. https://phet.colorado.edu/deploy-status/

From https://github.com/phetsims/perennial/issues/385.

@mattpen can you please add this to an exclude list or show me how to?

**Comment by mattpen** [comment]
@zepumph - I added deploy-status to our "Bypass Cache" rules. 

The status has changed from "HIT" to "DYNAMIC", which means it is no longer cached:
```
$ curl -si https://phet.colorado.edu/deploy-status | grep -i cf
cf-cache-status: DYNAMIC
cf-ray: 8db6024199b1e64a-DEN
```

**Comment by zepumph** [comment]
Awesome. I see that too. Thanks for doing this. Closing
