### ISSUE TITLE
Grunt deploy tasks do not exit.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#389]
I had this experience with `grunt rc` on 10/25/24 and `grunt production` on 10/28/24.  The tasks do not exit, and must be manually interrupted (Ctrl-C).

**Comment by pixelzoom** [comment]
Very annoying that `grunt dev` also does not exit.  Especially since it often takes a long time to transfer files, and it's therefore difficult to tell whether it's done or still transferring.   I've resorted to doing `ls -l` on bayes until I see that file sizes are no longer growing.

**Comment by pixelzoom** [comment]
Raising priority.  Since phettest is broken, I'm getting requests to publish dev versions.  And not know when `grunt dev` has completed is causing me more work.

**Comment by pixelzoom** [comment]
If it's going to be awhile before this is fixed, can't you please add something that prints "Done" to the terminal when the task is actually done?

**Comment by samreid** [comment]
I added `Done, OK to type Ctrl-C` for `grunt dev` and confirmed that it is working properly by deploying a dev version of bumper. I'm not sure what part of our tool chain is preventing exit, and not sure how to diagnose. I should probably check in with @zepumph. We could put console.logs after rc and production too for now, but I'm not sure how far away a long term solution is.

**Comment by zepumph** [comment]
Looks like it is a bug with booleanPrompt ONLY when running it with TSX.

Here is a scrap called js.js:

```js
const booleanPrompt = require( '../perennial/js/common/booleanPrompt.js' );

( async () => {
  console.log( await booleanPrompt( `Deploy this?` ) );
  console.log( 'after' );
} )();
```


Here is some console output:

```

 mjkauzmann ~/PHET/git/sandbox
 $ node js.js
Deploy this? [y/N]?y
true
after
*DOES exit*

 mjkauzmann ~/PHET/git/sandbox
 $ sage run js.js
Deploy this? [y/N]?y
true
after
*doesn't exit*

 mjkauzmann ~/PHET/git/sandbox
 $ ../perennial/node_modules/.bin/tsx js.js
Deploy this? [y/N]?y
true
after
*doesn't exit*
```

**Comment by samreid** [comment]
On windows, this is buggy with `tsx` but not with `node`. So this seems like a pitfall of tsx--there is a problem in that layer. We could try the `node --import=tsx` but it is listed as experimental. We don't know whether that uses different plumbing than `tsx`. 

We could put process.exit or console.log(ok to press control c now) at the end of those processes as a workaround.

Deno will likely fix this.

**Comment by samreid** [comment]
I will add process.exit when these tasks complete.

**Comment by samreid** [comment]
I added process.exit and tested by `grunt dev` in bumper. It exited properly without any ctrl-c or anything.

@zepumph what is next for this issue?

**Comment by zepumph** [comment]
I believe this is enough. In the future if there is another usage of booleanPrompt() in another file, it will be very obvious since the program will never exit.
