### ISSUE TITLE
Grunt deploy tasks create "Unversioned Files" in chipper/eslint/cache/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#390]
After running one of the grunt deploy tasks (`rc`, `production`,...) on a release branch, `chipper/eslint/cache/` gets populated, and WebStorm reports them as "Unversioned Files" -- see screenshot below, after `grunt production` for unit-rates.  Then they must be manually deleted.   

Should grunt deploy tasks automatically delete these files?  Or should they be added to ignored directories in WebStorm? Or something else? 

<img width="403" alt="screenshot_3553" src="https://github.com/user-attachments/assets/0556f0e1-5118-4336-8251-c4a5feeec34f">

**Comment by zepumph** [comment]
Duplicate of https://github.com/phetsims/chipper/issues/1508. Please pull and review if this is acceptable.

**Comment by pixelzoom** [comment]
What you described in https://github.com/phetsims/chipper/issues/1508 sounds reasonable.  I don't have time to test-drive, so I'll assume that you did.  Closing.
