### ISSUE TITLE
check for --repo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#40]
perennial and chipper have some identical grunt tasks, specifically checkout-shas and checkout-master.  For perennial, those tasks require a `--repo` option.   Which I habitually forget because I'm used to the chipper tasks.  And I get this downstream error message:

```
% cd perennial
% grunt checkout-shas
Running "checkout-shas" task
Warning: Unable to read "../undefined/dependencies.json" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
%
```

Yet another example of not testing that something required is indeed present.

**Comment by jonathanolson** [comment]
Added checking for that option above.
