### ISSUE TITLE
pre-commit code updates

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#404]
From https://github.com/phetsims/perennial/issues/370

- [x] Move this code to ~perennial-alias~ `chipper/js/grunt/tasks` and use `getOption`
- [x] Rename `hook-pre-commit.ts` to `pre-commit.ts`. And the task took.
- [x] Create a grunt task that runs pre commit hooks for a given repo or repos. Run it via the ts script, not the bash launcher.
- [x] Grunt task to support the "all working copy changes repos" (`--changed`) mode.
- [x] hook-pre-commit.sh calls `sage run grunt/tasks/pre-commit.ts` because the script moves to grunt.
- [x] grunt options can override the defaults from build-local.json. Probably something like `grunt pre-commit --lint=true --report-media=true --check=true --test=true`.
- [x] Remove `--forceTasks` added in https://github.com/phetsims/chipper/issues/1350#issuecomment-2452672149
- [x] Rename `phet-io-api-compare` -> `phet-io-api` Don't forget about build-json key and ping devs.

**Comment by samreid** [comment]
The precommit hook implementation is currently:

```
../perennial-alias/bin/sage run ../chipper/js/scripts/hook-pre-commit.js
```

should we change it to (0.3s faster on average)

```
../perennial-alias/bin/sage run ../perennial-alias/js/grunt/tasks/pre-commit.js
```

or this (stable API, cleaner, but assumes grunt is installed and is 0.3s slower on average)

```
grunt pre-commit
```

There is also a guard:
```
# Only run pre-commit hooks in main, see https://github.com/phetsims/perennial/issues/276
```
But maybe a better guard would be: if grunt is installed and it has a pre-commit task. Or alteratively, if sage exists and the pre-commit task exists.

**Comment by zepumph** [comment]
We hit this over in https://github.com/phetsims/perennial/issues/410, where we need to reinstall all git hooks because we renamed pre-commit.js -> .ts.

So we are adapting things a bit so that the pre-commit file just points to another bash file. This way that entrypoint can be changed without the need to reinstall all git hooks.

**Comment by samreid** [comment]
> Move this code to perennial-alias

Partway through this, I noticed these chipper files are used in this process. I don't believe that perennial can depend on chipper, and I don't believe we should move these behaviors to perennial:

import CacheLayer from '../../../chipper/js/common/CacheLayer.js';
import reportMedia from '../../../chipper/js/grunt/reportMedia.js';
import transpile from '../common/transpile.js';
import getPhetLibs from '../grunt/getPhetLibs.js';
import generatePhetioMacroAPI from '../phet-io/generatePhetioMacroAPI.js';
import phetioCompareAPISets from '../phet-io/phetioCompareAPISets.js';

@zepumph please advise

**Comment by zepumph** [comment]
Alright, I renamed to `unit-test`. Should I rename `check` to `typecheck`? Feel free to close.

**Comment by samreid** [comment]
I recommend renaming `check` to `type-check` (with a hyphen) in (a) the grunt task `grunt type-check` (b) the pre-commit flags `grunt pre-commit --type-check=false`, and (c) in the build-local.json key.  Sound OK?

**Comment by samreid** [comment]
@zepumph and I agreed to proceed as above, but there are 4 occurrences of `typecheck` in our codebase that should be changed to hyphenated or camel cased.

**Comment by samreid** [comment]
I did not see those 4 occurrences of `typecheck`. I visited occurrences of `tsc` and `check` and converted to use `type-check` or `typeCheck` as appropriate. Here is my patch so far:

I cannot rename check.ts => type-check.ts and add check.ts in one commit, so I will probably do that as 2 commits. I'm seeing enough unknown parts that this will need a careful review to see if I missed anything. But on the other hand:

- [x] `bin/sage run ../chipper/js/grunt/tasks/pre-commit.ts --changed --lint --report-media --type-check --test --absolute` is passing. 
- [x] `grunt type-check` is working
- [x] `grunt type-check --all` is working
- [x] aqua npm `test-ctq` is working
- [x] aqua npm `test-ct` is working.

So I will commit locally without pushing, then add tasks/commit.ts, then push everything and see how it goes on CT.

**Comment by samreid** [comment]
I messaged slack:

>  I’m going to push a rename of check to type-check which affects perennial, aqua, chipper. Details in https://github.com/phetsims/perennial/issues/404.  I will be watching CT closely for 28 minutes to see how it goes. CT may need to be restarted since some entry-level task names have changed. Anyways, letting you know in case you want to avoid pulling until getting the all clear.

**Comment by samreid** [comment]
Things are going somewhat well on CT and CTQ. I do not know how to convert this tsc to type-check:

<img width="588" alt="image" src="https://github.com/user-attachments/assets/b3bd1114-93a6-4976-8f6a-8f73a6b6123a">

and there is a multitude of ` has not been built from source file` but @zepumph says he is also working on CT in https://github.com/phetsims/aqua/issues/224 and it is related.

So we agreed to let it keep going.

**Comment by samreid** [comment]
Perhaps a note for devs to change build-local.json `hookPreCommit.type-check` to `check`, but maybe I am the only one using it. In any case, that one does not have alias support.

**Comment by zepumph** [comment]
- [ ] I think a rename from `isTypeCheck` to `shouldTypeCheck` or something about intent seems good.

* In commits above I investigated getting aqua report to build, but made a side issue because it seemed a bit challenging.
* In above commits I looked for vestigial usages of `tsc`, and found some. I didn't do the same for `check`, like in string comments, but likely that would be a good step.

**Comment by samreid** [comment]
Thanks, I caught a few more in my second pass through chipper, aqua and perennial.

**Comment by samreid** [comment]
I also searched phet-info, and everywhere for occurrences of `grunt check`. Anything else for this issue?

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
