### ISSUE TITLE
Enforce js file extension in imports

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#407]
From https://github.com/phetsims/chipper/issues/1498. There is a plugin that we can add a lint rule for:

Two options:
https://github.com/import-js/eslint-plugin-import/blob/67cc79841fc823ad4af2532af2dc6704e4b3b03a/docs/rules/extensions.md
https://github.com/solana-labs/eslint-plugin-require-extensions

@samreid, what do you think?

**Comment by samreid** [comment]
Is the existing bad-text lint rule insufficient?  Do we need something with --fix?

<img width="867" alt="image" src="https://github.com/user-attachments/assets/9375697d-5e84-4dbd-8d41-a7d5653fd3b9">

**Comment by zepumph** [comment]
I experimented with that, but it is a pretty naiive test, as it doesn't support a case like `import winston from 'winston';`. 

I updated it and moved it to the base `bad-text` rule, but we may still want to swap things out to use a plugin if we find another corner case or two in the future.

**Comment by chrisklus** [comment]
There's a few website imports getting caught by this, but it's unclear to me why all imports that don't have a suffix are not breaking, see https://github.com/phetsims/website-meteor/issues/813. Any ideas?

**Comment by zepumph** [comment]
Well that isn't ideal! I think the best thing for now is to turn off this error until we can implement the plugin directly as an actual solution.

**Comment by samreid** [comment]
After careful evaluation, eslint-plugin-import seems too heavyweight and will likely not have the flexibility to handle nuances in our project such as `import playwright from '../../../../perennial/node_modules/playwright';` So I will add a custom lint rule.

**Comment by zepumph** [comment]
Amazing. Thanks for doing this. No notes.

**Comment by zepumph** [comment]
Note that this likely effected https://github.com/phetsims/website-meteor/issues/813.

**Comment by zepumph** [comment]
Should we set this to false?

https://github.com/phetsims/perennial/blob/391ba82c2505daff5f3d2ac5d422c9646d9755de/tsconfig/tsconfig-node.json#L18

**Comment by zepumph** [comment]
Looks like the lint rule doesn't support the dynamic function `import()`. Would you like to add support for that? (not a leading question, feel free to close).

**Comment by samreid** [comment]
Let's keep the rule simpler by only supporting static imports. I'll also set `allowImportingTsExtensions` to false, but can we also set this to false in phet-vite-demo? It may be better to be consistent between our main codebase and phet-vite-demo. phet-vite-demo has this commented out:

```ts
// NOTE: Can also use direct imports if you have the PhET repos checked out:
// import { Node, Display, Text, VBox, Font, AlignBox, AnimatedPanZoomListener } from '../../scenery/js/imports.ts';
// import TextPushButton from '../../sun/js/buttons/TextPushButton.ts';
```

and the rest of the code is like this:

```ts
import { platform } from 'phet-lib/phet-core';
import { Bounds2, Range } from 'phet-lib/dot';
```

So I think we should be consistent here. I'll commit that and request feedback from @zepumph and @jonathanolson

**Comment by samreid** [comment]
@zepumph and I reviewed and agree to close, thanks!
