### ISSUE TITLE
document or delete build-for-server

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#409]
During https://github.com/phetsims/perennial/issues/375 I saw a task `build-for-server` that calls `build`. It is not documented why we need an alias. The build server has this code:

```ts
    if ( buildForServer ) {
      args.push( 'build-for-server' );
    }
    else {
      args.push( 'build' );
    }
```

which also does not explain the need for `build-for-server`.  Can it be documented or deleted?

**Comment by zepumph** [comment]
I couldn't find much about it. Seems to only be applied for chipper 1.0 sims. I would be careful about deleting something in this area, as it could be used exclusively for older versions of chipper.

**Comment by zepumph** [comment]
I see this in a chipper 1.0 release branch. In this case it is bending light 1.1 on chipper@2c6d5338a8b5b3668f6863d26e260fd353542fbb:

```
  grunt.registerTask( 'build-for-server', 'meant for use by build-server only',
    [ 'build', 'generate-thumbnails', 'generate-twitter-card' ]
  );
```

Seems best to not touch it.

**Comment by zepumph** [comment]
Doc pushed.
