### ISSUE TITLE
builds failing with message "Output exceeds 32000 characters" 

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#41]
The build server sent out a failure message early yesterday morn.  The first portion looked like this:

```
Build failed with error: error running command grunt build-for-server --brand=phet --locales=sk: Error: Command failed: /bin/sh -c grunt build-for-server --brand=phet --locales=sk
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
 Sim = function-builder-basics Version = 1.0.1 Locales = sk Shas = 
...
```

I remember a few people having this issue for local builds a week or two ago and asked @jessegreenberg about it.  He referred me to https://github.com/phetsims/chipper/issues/605.

**Comment by jonathanolson** [comment]
@jbphet, any knowledge of if we've run into this recently?

**Comment by jbphet** [comment]
I have seen this a handful of times recently, but it doesn't seem to cause any issues with the build, so I'm going to close it.
