### ISSUE TITLE
Create browser-and-node config

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#418]
From https://github.com/phetsims/chipper/issues/1526#issuecomment-2501854917, we have a collection of es modules that we are using in both sims and Node code:

```
SimVersion
affirm()
phetioCompareAPIs
```

I'm creating a side issue from https://github.com/phetsims/chipper/issues/1526#issuecomment-2501854917. I also want to put this on hold until we complete https://github.com/phetsims/chipper/issues/1483

**Comment by zepumph** [comment]
I was able to confirm that this is what the browser-and-node tsconfig file should be (none of the browser-specific or node-specific config entries should be combined).

```
{
  "extends": "./tsconfig-core.json",
  "include": [
    "../js/browser-and-node/**/*"
  ]
}
```

**Comment by zepumph** [comment]
I believe this is complete, but I'll come back once we complete https://github.com/phetsims/chipper/issues/1483/.

**Comment by zepumph** [comment]
Ok. I don't think there is anything else here. I'd like to check in with @samreid to see what else we may need to do for this one.


- [x] Move repo/test/ to repo/js/test/
- [x] Move SimVersion to browser-and-node/

**Comment by zepumph** [comment]
I'm a liar! We got the tsconfig stuff working well, but we still need to work out lint. For example. We want to make sure that `assert` isn't an available global (I think that works), but furthermore, we probably want to adapt a system that says "Take all the node rules AND the browser rules", instead of leaving both of them out. 

- [ ] Add eslint config to browser-and-node files.

**Comment by samreid** [comment]
@zepumph and I reviewed and agreed we need a `browser-and-node.eslint.config.mjs` in perennial-alias/eslint/config which extends root.eslint.config.mjs and adds bad-sim-text: error and bad-phet-library-text: error. Then we can extend this new config everywhere we have a browser-and-node/ directory.

**Comment by samreid** [comment]
Really great, nice work. Closing.
