### ISSUE TITLE
Add support for --absolute with bin/sage run ../chipper/js/grunt/tasks/pre-commit.ts --changed

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#419]
I noticed that lint errors were hyperlinked but type check problems were not. So we should make sure `grunt pre-commit` supports `--absolute` so we can navigate the errors within the IDE.

**Comment by zepumph** [comment]
When I add `grunt pre-commit` as an external tool in webstorm, it prints `undefined` for `process.env.HOME` when trying to read my build-local.json. Does this happen for you?

**Comment by zepumph** [comment]
Ok sorry. It looks like a bug with webstorm external tools, but I got around it by using sage run instead of grunt. Everything else looks good. Anything else here?

**Comment by samreid** [comment]
That's all for me, thanks.
