### ISSUE TITLE
branch: phetio-latest

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#44]
Branch involved at determining what the latest published sim will be on the phet-io website. Discussion in https://github.com/phetsims/phet-io-wrappers/issues/30#issuecomment-333233629.

**Comment by jonathanolson** [comment]
I see a 'phetio-latest' branch. Is this issue for that branch? (if so please rename issue).

It looks like the code change is in the build-server writePhetioHtaccess (seems different than examining what the latest sim is on the phet-io website, but is part of the deploy process).

Is the description above accurate? And can this be merged to master?

**Comment by zepumph** [comment]
> And can this be merged to master?

That is a question for @mattpen

**Comment by mattpen** [comment]
> And can this be merged to master?

The change hasn't been tested yet.  I'll plan on testing and merging the change if successful when I upgrade node/npm as part of phetsims/chipper#604.

**Comment by mattpen** [comment]
This change will need to be discarded and rewritten as it is too far behind master.

**Comment by samreid** [comment]
@mattpen can I get a status on this?

**Comment by mattpen** [comment]
@samreid 

The changes have been migrated to the `chipper2.0` branch manually in the above commit.  This branch is no longer necessary so I'll remove it.

The changes have not yet been tested, are they blocking progress on phetsims/phet-io-wrappers#30?

**Comment by samreid** [comment]
I was getting closer to a point where I was ready to test that, even though we wouldn't use it in production for another month at least.

**Comment by mattpen** [comment]
The /latest links were tested and deployed to production.

Full testing results here: https://docs.google.com/spreadsheets/d/1IyEzNukabAlhgm3PV6xtSALyffU1wj7VdYwaZRdbed0/edit?usp=sharing
