### ISSUE TITLE
review all issues for possible inclusion in "chipper 2.0" milestone

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#45]
Looks like most (all?) perennial issues should have the "chipper:2.0" label.  Rather than label them all, I'm creating this "blanket" issue.

**Comment by ariel-phet** [comment]
Assigning @mattpen and @jonathanolson to take a brief first pass at open perennial issues and bring up for Thursday meeting

**Comment by jonathanolson** [comment]
I took a pass over and tagged issues I personally thought should be handled. @mattpen can you also check through to see what your opinion is?

**Comment by mattpen** [comment]
I reviewed the remaining issues and tagged any that I thought necessary.

@pixelzoom @ariel-phet  Should we close this issue?

**Comment by pixelzoom** [comment]
Sounds like we've accomplished what @ariel-phet asked for in https://github.com/phetsims/perennial/issues/45#issuecomment-340494264, so closing.
