### ISSUE TITLE
Upgrade to Express 4?

### ISSUE THREAD

**Issue by mattpen** [phetsims/perennial#47]
As I was reviewing the api reference for express, I noticed that the version we are using (3) is now deprecated.  The current supported version is 4 and 5 is in alpha.  After reviewing the [migration guide](https://expressjs.com/en/guide/migrating-4.html) it looks like the update should be relatively straightforward as we are only using one function that was removed.

If we upgrade build-server, it probably makes sense to upgrade rosetta as well.
@jonathanolson @jbphet - Does this sound ok with you? Any concerns?

**Comment by jbphet** [comment]
No concerns here, and I'll log an equivalent ticket for rosetta.

**Comment by mattpen** [comment]
I've upgraded to express 4 in the chipper2.0 branch and tested an rc and production deploy on ox-dev.  The deployments went off without a hitch.  The only thing I needed to change was new code written for #39, so I think its safe to accept this upgrade.
