### ISSUE TITLE
use a common account for transfers of builds to spot

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#50]
(moved to here from (https://github.com/phetsims/chipper/issues/627)

@pixelzoom recently thought that I had published an RC of a sim for which he is the responsible dev due to file permissions.  The following dialog resulted.  Bottom line: We should use something other than my account info for transferring files from the build server to the dev server.

Slack thread:

@pixelzoom  [5:14 PM]
I see that you published function-builder 1.0.9-rc.1 on 11/17, so it has entered an RC phase. What’s going on?

@jbphet [8:54 AM]
I think you meant to ping JO on this (kinda freaked me out, since I didn't recall it at all).

@pixelzoom  [8:55 AM]
drwxrwsr-x 2 jblanco physphet 4096 Nov 17 18:51 1.0.9-rc.1/

@jbphet [8:55 AM]
https://github.com/phetsims/function-builder/commits/1.0

@pixelzoom  [8:56 AM]
hmmm… how did the files on spot end up owned by you?

@jbphet [8:57 AM]
Not sure. I know rosetta uses my account information for some file transfer operations, maybe this is done in other places in the build tools too. If so, probably best to modify that to use a machine account of some kind.

As I think about it, but build server is likely using my account info. I'll put that on my list to investigate today.

**Comment by jbphet** [comment]
I just looked on phet-server, and indeed, my account is being used for transfers to the server. We should set up a common account and use that instead.

**Comment by jbphet** [comment]
@mattpen - I'm assigning this to you since you're working on the build server for Chipper:2.0 and probably know about whatever spot accounts we have for this (or how to get one set up).  Let me know if you'd rather have me follow up on it.

**Comment by mattpen** [comment]
I've updated the devUsername on phet-server to be `phet-admin`.  Builds should now be transferred with this account.  I deployed Chains RC `1.15.1-rc.1` and it successfully transferred with the shared account. Closing.
