### ISSUE TITLE
simInfoArray shouldn't be updated when publishing on the test server (ox-dev)

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#52]
The `simInfoArray` file, which is the file that the build-server writes and the translation utility reads to find out where to access simulation information, appears to be getting updates when publications occur on the test sever (ox-dev).  Here is an example of a commit that demonstrates the problem: https://github.com/phetsims/rosetta/commit/a05493337337db2307912ebed318b48bc35e24df#diff-820b87a198cf12e2c520bf5cc693c3b7.

At some point, this whole approach to how rosetta gets sim information may change (see https://github.com/phetsims/rosetta/issues/148), but for now we need to protect the integrity of this file so that we don't break translation.

**Comment by mattpen** [comment]
@jbphet - the best solution is probably to use the Metadata API instead of passing a json file back and forth via github.  The biggest problem is that currently you can't get unpublished sims in the Metadata API (such as chains and example-sim).  I could implement a new query parameter in the API for rosetta to make this possible though.

**Comment by mattpen** [comment]
I added a temporary patch to prevent commits and push of this file on ox-dev, but I think it would be better to take advantage of our API in the long term.

**Comment by jbphet** [comment]
Yes, I'd love to take advantage of the meta-data API, but the inability to get information about chains and example-sim has been a deal breaker on this.  If you could add a query parameter that would enable the retrieval of this data, that would be awesome, and we could eliminate entirely eliminate simInfoArray from the process.

**Comment by jbphet** [comment]
This issues is related to https://github.com/phetsims/rosetta/issues/148, and if we get to where we have the meta data working, both issues are solved.

**Comment by mattpen** [comment]
@jbphet - the metadata should now be working for this purpose, see details in https://github.com/phetsims/rosetta/issues/171#issuecomment-367417895.

**Comment by jbphet** [comment]
Metadata is now being used for sim info, and seems to be working well.  Closing.
