### ISSUE TITLE
"phetio" is not stripped from phet-io version on dev deploy

### ISSUE THREAD

**Issue by zepumph** [phetsims/perennial#55]
Here is an about dialog from: https://www.colorado.edu/physics/phet/dev/html/chains/1.7.0-dev.16/phetio/wrappers/instance-proxies/instance-proxies.html?link&relativeSimPath

![image](https://user-images.githubusercontent.com/6856943/33695980-8ffd4f08-daac-11e7-843b-526be06cd431.png)

Currently the index wrapper is broken because it expects the version to look like "1.7.0-dev.16" but instead it is "1.7.0-phetiodev.16" 

I'm not sure if this is the right repo, or if it is a unique enough problem for it's own issue. Let me know what I can do to help!

**Comment by zepumph** [comment]
This is blocking https://github.com/phetsims/phet-io-wrappers/issues/38

**Comment by jonathanolson** [comment]
Also, I think the "expected" version would be 1.7.0-dev.16-phetio. Will that cause problems?

**Comment by jonathanolson** [comment]
Should be fixed (to the above) in the 2.0 branch.

**Comment by zepumph** [comment]
Confirmed fixed for https://www.colorado.edu/physics/phet/dev/html/chains/1.11.0-dev.1/phet-io/chains_all_phetio.html?development&phetioStandalone. Closing
