### ISSUE TITLE
New build-server request API proposal

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#56]
Current api:

{
  repos // dependencies.json format
  simName
  version // string, includes rc.X if available, -phetio triggers phet-io build
  locales // array of locales
  option: 'rc' // if provided, signals an RC build
  email // for notifications
  id // ????
  authorizationKey // for security
}

My idealized api:

{
  api: '2.0' // so it can be distinguished
  dependencies // dependencies.json format
  simName
  version // normal string, not including brand (i.e. what is in package.json)
  locales // array of locales
  servers: // subset of [ 'dev', 'production' ]
  brands: // array of brands
  authorizationCode
  translatorId // instead of id (so it's easier to know what it's for)
  email
}

Changes:

- Added `api` field, so we can distinguish different versions of requests (especially for the future).
- `repos` => `dependencies`. `repos` is usually an array of repository names in chipper/perennial/yotta/continuous-testing/etc.
- `option` => `servers` (instead of having the option:'rc' decide this).
- Added `brands`, since we want to support multiple brands at a time.
- `id` => `translatorId`, since it's clearer
- `version` would not include the brand (it would just be what's in package.json). MAY include one-off.

Additionally, this would support doing dev/one-off deploys using the build server.

Thoughts?

**Comment by mattpen** [comment]
> servers: // subset of [ 'dev', 'production' ]

@jonathanolson Would we assume that any request to deploy to the production server for phet brand would trigger a call to the synchronize API on the website (adding the sim to the database and generating an admin page)?

> translatorId // instead of id 

This would require a parallel change in rosetta.  Tagging @jbphet so he is aware.  I'm ok with the change.

**Comment by jonathanolson** [comment]
> Would we assume that any request to deploy to the production server for phet brand would trigger a call to the synchronize API on the website (adding the sim to the database and generating an admin page)?

Correct.

> This would require a parallel change in rosetta. Tagging @jbphet so he is aware. I'm ok with the change.

Yes. @jbphet, would we need to discuss any of the chipper 2.0 changes for rosetta? Is it building sims at all?

**Comment by jonathanolson** [comment]
Perennial deploy has been set up to fire off the new style of request. Pending on @mattpen to hear about implementation.

**Comment by jbphet** [comment]
Yes, rosetta builds new translations whenever they are submitted by translators.  It does this by firing off a request to the build server.  I'm assuming the build server will be backwards compatible, i.e. it will support the old version of requests, correct?  It would be good to upgrade rosetta to the new API though, so please log an issue and point me to whatever I need to know, and I'll do it.

**Comment by jonathanolson** [comment]
api:2.0 should be POST only, and presumably we need to support the original API in POST, as we are in that state of shas right now.

**Comment by mattpen** [comment]
@jonathanolson - In the `brands` object, will phet brand be `'phet'` and phet-io be `'phet-io'`?

**Comment by jonathanolson** [comment]
> @jonathanolson - In the brands object, will phet brand be 'phet' and phet-io be 'phet-io'?

Yes, although other brands (adapted-from-phet, etc.) might be possible to dev-deploy, etc. (but not get sent to production)

**Comment by mattpen** [comment]
I've pushed changes to handle the new API requests, but nothing is tested yet and there is a lot of error checking still missing.

**Comment by mattpen** [comment]
@jonathanolson - The new API should be available now for testing on ox-dev.  I sucessfully ran an RC deploy here: https://www.colorado.edu/physics/phet/dev/html/chains/1.7.0-rc.20/

**Comment by jonathanolson** [comment]
Working well. Is there anywhere we should document this API, or can this be closed?

**Comment by mattpen** [comment]
There is a readme file where it should be documented in the /js/build-server directory.  I'll make sure it's updated as we seem to be in a stable state now.

**Comment by mattpen** [comment]
Documentation was added, closing.
