### ISSUE TITLE
problems with print-shas.sh

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#59]
I was looking at print-shas.sh to help solve https://github.com/phetsims/perennial/issues/58.  But print-shas.sh has problems of its own.  If it encounters a file that's not a directory containing `.git`, it does this:

`24 echo ">>>>>>>>>>>>>>>>>>>>>>>> Missing repo: $sim"`

Two problems:

(1) `$sim` is undefined. It should be `$repo`.

(2) Files like GitHub.iml are incorrectly reported as being "Missing repo"

**Comment by pixelzoom** [comment]
@jonathanolson FYI, since this undoubtedly need to be fixed in perennial "chipper2.0" branch.

**Comment by pixelzoom** [comment]
I'd like to fix this so that I can proceed on #58.  @jonathanolson in addition to master, which branches should I fix?

**Comment by jonathanolson** [comment]
Master is the only branch that would need these updates. There is a chipper 2.0 related branch, but it's only for the build-server code.

**Comment by pixelzoom** [comment]
Slack developer channel:

Chris Malley [12:03 PM] 
Is anyone relying on the current output format of print-shas? `{{REPO}} : {{SHA}}`, e.g. `neuron : a7f11417afa492b88a888f380cea70cd4296c295`. Proposing to remove the “:”, i.e.: `{{REPO}} {{SHA}}`, e.g. `neuron a7f11417afa492b88a888f380cea70cd4296c295`.

Jonathan Olson [12:07 PM] 
I don't believe I'm relying on it anywhere

Sam Reid [12:08 PM] 
Removing the colon seems fine with me

Chris Malley [12:08 PM] 
ok thanks, i’ll proceed

**Comment by pixelzoom** [comment]
Changes to print-shas.sh:

• ignores files and directories that are not git repositories
• for each git repository, prints a line with format "{{repo}} {{sha}}"
