### ISSUE TITLE
redo the migration of chipper/bin/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#62]
chipper/bin/ scripts were copied to perennial/bin by @jonathanolson on 12/4/17.  By copying them instead of moving them, we've lost the git history for all of the scripts.  (The first commit message for every script is the not-very-helpful "Data, fixes, and lint-everything".)

I recommend that this migration be redone in a way that (1) preserves git history, and (2) picks up changes that have been made to perennial/bin/ since 12/4/17.

**Comment by pixelzoom** [comment]
Slack developer channel:

Chris Malley [12:36 PM] 
Any way we can restore git history for perennial/bin/*.sh ?
@jonathanolson I guess that’s a question for you, since you moved the scripts to perennial.

Chris Malley [12:47 PM] 
@jonathanolson Now that I’m making significant changes to perennial/bin/ scripts, I’m a little concerned about having the same set of (now out-of-date) scripts in chipper/bin/. (edited)

Sam Reid [12:48 PM] 
If perennial is already in master (not a 2.0 branch), then perhaps we can delete the chipper scripts right away? (edited)

Chris Malley [12:48 PM] 
Discussed in https://phetsims.slack.com/archives/G6E0RA1T2/p1513801751000431
I think we should delete chipper/bin/.  If something breaks, change it to point to perennial/bin/. 
If chipper/bin/ had been moved (instead of copied) to perennial/bin/, we’d also have git history.

Sam Reid [12:51 PM] 
Do you know a straightforward way to move files from one repo to another and maintain history?  Michael & I tried to do so for phet-io things last year and ran into hassle after hassle.

But it may be simpler for the scripts, strategies like `https://stackoverflow.com/questions/10524578/how-to-move-a-file-from-one-git-repository-to-another-while-preserving-history` may be more likely to work (edited)


Chris Malley [12:52 PM] 
The first commit message of all scripts in perennial/bin/ is 12/4/17 “Data, fixes, and lint-everything”.
We’ve lost history before then.
Perhaps this “move” should be redone ?
I’ve already needed history once (for `pull-all.sh -p`) and had to go to chipper to find it.  When chipper/bin/ is deleted, … ?

Sam Reid [12:55 PM] 
Yes, I think it’s worth at least an hour investigating ways to preserve history when moving something to a new repo. It would be useful for these scripts too.

**Comment by pixelzoom** [comment]
Also recommended to delete chipper/bin/.  We don't want to have duplicate/diverging scripts in master, with people pointing to old versions of scripts that are evolving (e.g. pull-all.sh, print-shas.sh).  If something breaks by chipper/bin/ going away, we should fix it to point to perennial/bin/.

**Comment by samreid** [comment]
I updated my $path to use perennial instead of chipper.

**Comment by jonathanolson** [comment]
I'll look into it.

Additionally, should I look into significantly changed files? (e.g. https://github.com/phetsims/chipper/blob/master/js/grunt/deployDev.js is the "original" for https://github.com/phetsims/perennial/blob/master/js/grunt/dev.js that may be valuable if we are preserving history, even if it is almost completely different).

**Comment by pixelzoom** [comment]
yeah, probably good to preserve any history we can.

**Comment by jonathanolson** [comment]
> Also recommended to make chipper/bin/ go away.

I just checked, and this would definitely break our current deployment (build-server currently relies on chipper/bin/clone-missing-repos.sh). Unless it's a priority to get rid of chipper/bin in master (and @mattpen handles this in build-server master, tests and releases to production), I'd like to just leave them in-place for now.

**Comment by jonathanolson** [comment]
@samreid and @pixelzoom, it looked like you looked into some solutions from https://stackoverflow.com/questions/1365541/how-to-move-files-from-one-git-repo-to-another-not-a-clone-preserving-history, but they wouldn't maintain commit timestamps. Did it look like there are no good solutions, or should I look into options?

**Comment by samreid** [comment]
I tried the patch strategy once and the git filter-branch strategy once (in attempt to maintain history for the phet-io playback wrapper which also needs to migrate) and they both collapsed timestamps.  However, there is a good possibility that I did something wrong and I'd like you to take an independent look.

**Comment by pixelzoom** [comment]
I didn't investigate any solutions, just skimmed what @samreid referenced in Slack.

**Comment by pixelzoom** [comment]
Now that the chipper 2.0 merge has occurred, self-assigned to see where this is at.

**Comment by jonathanolson** [comment]
I haven't yet figured out a great way to do this, but I haven't investigated all options.

**Comment by pixelzoom** [comment]
A couple years after the fact, I'm guessing this is never going to happen.  Should we just close this issue?

**Comment by samreid** [comment]
I vote to close this issue regarding perennial/bin, but future repo-relocates should use a history-preserving strategy.

**Comment by jonathanolson** [comment]
Looks like we have copy-history-to-different-repo for future handling? I'd strongly prefer to just close, unless this is worth a lot of time.
