### ISSUE TITLE
Builds fail if there is no screenshot

### ISSUE THREAD

**Issue by samreid** [phetsims/perennial#64]
While working on https://github.com/phetsims/gravity-force-lab-basics/issues/22 I tried to do `grunt dev --brands=phet,phet-io` and received this error:

```
info: transferring ../gravity-force-lab-basics/build/phet-io remotely to /htdocs/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.8/ on spot.colorado.edu from /Users/samreid/github/perennial

Fatal error: Perennial task failed:
Error: scp -r ../gravity-force-lab-basics/build/phet-io {{redacted}}@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.8/ in . failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/samreid/github/perennial/js/common/execute.js:71:17)
  at emitTwo (events.js:125:13)
  at ChildProcess.emit (events.js:213:7)
  at maybeClose (internal/child_process.js:927:16)
  at Socket.stream.socket.on (internal/child_process.js:348:11)
  at emitOne (events.js:115:13)
  at Socket.emit (events.js:210:7)
  at Pipe._handle.close [as _onclose] (net.js:549:12)

Full Error details:
{
  "cmd": "scp",
  "args": [
    "-r",
    "../gravity-force-lab-basics/build/phet-io",
    "{{redacted}}@spot.colorado.edu:/htdocs/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.8/"
  ],
  "cwd": ".",
  "stdout": "",
  "stderr": "../gravity-force-lab-basics/build/phet-io: No such file or directory\n",
  "code": 1
}
Fatal error: perennial grunt "--repo=gravity-force-lab-basics" "dev" "--brands=phet,phet-io" failed with code 1
```

@jonathanolson or @mattpen any idea what is going wrong here?

**Comment by samreid** [comment]
It looks like the phet-io brand wasn't built at all.

**Comment by samreid** [comment]
I asked on slack: phet-io brand isn’t building for gravity-force-lab-basics.  package.json already had `supportedBrands`.  I tried `brands`.  Didn’t seem to work.  How can I do this correctly?

**Comment by samreid** [comment]
I’m getting this build failure in gravity force lab basics

`> grunt --brands=phet,phet-io`

`...`

`no image file exists: ../gravity-force-lab-basics/assets/gravity-force-lab-basics-screenshot.png. Aborting generateThumbnails`

**Comment by samreid** [comment]
After I added a placeholder screenshot, deployment works successfully.  I think this would be a problem for any sim without a screenshot.

**Comment by samreid** [comment]
This issue should probably be in chipper, but I'll leave it here for now in case it's easy to solve.

**Comment by jonathanolson** [comment]
Should be fixed in the above commit. Also for reference, this is just for the chipper 2.0 branch.

@samreid can you confirm?

**Comment by samreid** [comment]
Would you want to fail the build if it is for production and the screenshot does not exist?  Does this happen elsewhere?

**Comment by jonathanolson** [comment]
Now checking in production deploy.

**Comment by samreid** [comment]
I didn't test this, but the commit seems correct.  We could perhaps test it using chains, but I'm inclined to call it good. (We can test it for live deploys in the near future).
