### ISSUE TITLE
Perennial flag commands

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#65]
It would be good to have commands that are able to:

1. Modify the package.json, for adding support for phet-io brands or other related items, and
2. Regenerate perennial/data files, commit and push.

Common sections that would need to be modified:

- adding or removing supported brands for a runnable
- `accessible` flag
- `runnable` flag
- `simulation` flag
- `automatedTestEnabled` flag

So I'd propose something like

- `grunt add-supported-brand --brand={{BRAND}}`
- `grunt remove-supported-brand --brand={{BRAND}}`
- `grunt set-package-flag --flag={{FLAG}}` (flag is accessible,runnable,simulation,automatedTestEnabled)
- `grunt unset-package-flag --flag={{FLAG}}` (flag is accessible,runnable,simulation,automatedTestEnabled)

Thoughts?

**Comment by samreid** [comment]
It seems reasonable but I'm trying to understand the reason for making these grunt commands--how do you picture they will integrate into our processes?

**Comment by jonathanolson** [comment]
Sorry, I thought we closed this issue. #66 has been implemented instead.
