### ISSUE TITLE
One-off deploy details

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/perennial#69]
Some clarification of what people would hope to achieve with one-off deployments would be helpful. Some thoughts:

- What is allowed in the one-off part of the version? Currently for parsing, it's anything that doesn't contain `-` or `.` (so that parsing is easier).
- Should we allow deploying with working-copy changes (for the sim repo)?
  - PRO: This is great for when you need to repeatedly build/upload a sim to test on a device that can't access the development machine, or for things where you want to make a change without creating a full branch.
  - CON: If we allow working copy changes, then we can't update anything in the repository (package.json version, dependencies.json, etc.). If the user attempts two one-off deployments back-to-back, the version number wouldn't change (since we can't update the version automatically), so does that fail, or does it overwrite? Would we have the user select one-off names like `footest.1`, `footest.2`, etc. so they don't conflict? Since the version proposal includes the `dev.X` or other parts of the version, it feels unclean to not increment the test number.
- If we don't support working-copy changes, do we support detached heads (for the sim repo)?
  - PRO: Would be able to check out arbitrary SHAs and deploy
  - CON: Again we have the issue that we can't commit and push, so we can't update the package.json version, dependencies.json, etc.
- If we don't support detached heads, presumably we always support one-off deploys off of arbitrary branches. If so, how do we handle versioning for a one-off deploy:
  - If we still include the `dev.X` (or other test types like `rc`) in the one-off version:
    - If we don't increment the test number on deploys, we'd run into the same "version doesn't change with deploys" issue above.
    - If we do increment the test number on deploys, but don't change it on other branches (maybe we just branched off of master), then we'll run into the out-of-order looking deploys where we deploy 1.0.0-dev.3-sonification on a branch, but then dev deploy 1.0.0-dev.2 on master. That sounds less than ideal.
    - If we want to try to update the version on master also (to avoid the out-of-order bit), then we'll run into cases where the version on our branch is totally unrelated to master (and we don't want to update it).
  - We may not want to commit/push dependencies.json. Imagine I dev-deploy off of master (all repos), then one-off deploy where a common repository is switched to an experimental branch, I wouldn't want to check in that dependencies.json (it wouldn't be helpful, and the usual expectation would be that the latest dependencies.json is from the latest working normal deployment).

I don't see a great way of moving forward, particularly without knowing what people would want for one-off deployments. I'm currently leaning towards a more "perennial hands-off" approach that is like our old dev deployments, where it:

- Takes whatever is already in the `build/` directory (so you can custom build things with arbitrary command-line flags, like `--mangle:false`, or could be hand-edited if we really need).
- We decide on a minimalistic version (dev directory), where the user can decide to version multiple consecutive deployments how they want. Completely stripping off the `dev.X` part of the version (test type and number) may solve some problems.
- Have it error out if you try to deploy things to an already-existing directory (don't overwrite). Still don't want to overwrite things accidentally.

Thoughts?

**Comment by pixelzoom** [comment]
Self assigning to give feedback about "what people want from one-off deploys", as request on Slack.

**Comment by pixelzoom** [comment]
I've never had a need to do a one-off deploy, I've always accomplished that with a dev version.  So I don't have any concrete experience to inform my feedback.  That said...  

Any token that doesn't contain a separator seems fine for the one-off part of the version identifier.

If it were me that were responsible for a one-off, I would never deploying anything that isn't pushed, it's just a bad idea. You can't identify the source code used to build it, and it therefore can't be reproduced.  So my vote would be for requiring all working copy changes to be pushed, and using named branches (not detached heads) -- just like dev/rc/production processes.

I'm not sure how we handle versioning for a one-off.  (So caveat: these thoughts are very mature, very brainstormy.)  It were me, I'd prefer to do my one-off in its own branch, where the branch name and the one-off name are identical.  Any dependency repository that needed to be branched for my one-off would be named something like `{{SIM_REPO}}.{{ONE_OFF_NAME}}`, e.g. `equality-explorer.princetonStudy`.  My one-off branch would have it's own `major.minor.dev` version lineage. Deployed versions end up in a directory structure like `equality-explorer/princetonStudy/1.0.0`.

**Comment by jonathanolson** [comment]
> I'd prefer to do my one-off in its own branch, where the branch name and the one-off name are identical.

If we only allow branches (so we can push), this would also be my preference.

>  Any dependency repository that needed to be branched for my one-off would be named something like {{SIM_REPO}}.{{ONE_OFF_NAME}}, e.g. equality-explorer.princetonStudy. My one-off branch would have it's own major.minor.dev version lineage.

I like the general idea of this. I'd also consider `{{SIM_REPO}}-{{ONE_OFF_NAME}}`, since common code branches for sims are already `{{SIM_REPO}}-{{BRANCH_NAME}}` (and if we have one-off-name==branch-name, it would follow a pattern). This gets more difficult because now we're using `-` again as a different type of separator.

> Deployed versions end up in a directory structure like equality-explorer/princetonStudy/1.0.0.

Additionally, if we treat the one-off as part of the version, I was considering having it be at the front, e.g. `princetonStudy-1.0.0` so that it's clear the `1.0.0` part is separate from the mainline. Then it would be in a folder (following our conventions) of `princetonStudy-1.0.0` (instead if it appearing to take the place of the brand in the build).

**Comment by samreid** [comment]
I prefer everything committed, no detached head allowed.

**Comment by jonathanolson** [comment]
Version: 1.2.0-sonification.3
Sim branch: 1.2-sonification
Common code branches: molecule-shapes-1.2-sonification
Deploys to directory: molecule-shapes/1.2-sonification.3 (the version)

**Comment by jonathanolson** [comment]
One-off version deployed as part of unit tests (it picks a random one-off branch name): https://www.colorado.edu/physics/phet/dev/html/bumper/12.1.0-oneoffqc4kk44osco.1/

Reported full success to create the branch and to deploy.

**Comment by jonathanolson** [comment]
Implemented and documented.
