### ISSUE TITLE
bump version id after running lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#76]
I ran `grunt dev --repo=equality-explorer --brands=phet`, only to have it fail due to a lint error in scenery-phet `ThermometerNode` (which was fixed in master, but not in my working copy).  Now I have to manually revert the version number.

Recommended to bump the version number _after_ lint (and other things that depend on working copy?) have been run.  For example, I suspect that having an unused string might result in the same issue.

**Comment by jonathanolson** [comment]
Definitely can be done, but will increase the deployment time (it will build the sim twice). Any objections? (tagging for dev meeting in case it isn't handled before then)

**Comment by jessegreenberg** [comment]
This would be nice, I think it is worth the increase in deployment time.

**Comment by pixelzoom** [comment]
Hmmm... I'm not sure it's worth the time required to build twice.  Maybe just run `lint-all`?

**Comment by jonathanolson** [comment]
Running lint-all beforehand sounds like a good compromise to me.

**Comment by pixelzoom** [comment]
Running `grunt lint` before `git push` would be an even better compromise :)

**Comment by jonathanolson** [comment]
It should be possible to lint during the initial checks (before anything is pushed/etc.) Any objections?

**Comment by samreid** [comment]
I configured IDEA to run `grunt lint-everything` on commit.  You can do so by adding an external tool, and wiring up through the commit dialog.  This isn't as good as a pre-commit task, but it seems better than nothing!

**Comment by jonathanolson** [comment]
Implemented above.
