### ISSUE TITLE
problems with use of chipperVersion

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#78]
Multiple problems with how perennial is using `chipperVersion`:

(1) Perennial currently relies on chipper version ids `'2.0.0'` and `'0.0.0'` to decide which vintage of chipper it's dealing with (call them chipper2 vs chipper0).  These literals are not encapsulated; they appear in 5 `if` expressions and 1 `assert` message, spread across 3 .js files.   And they are using string comparison, not an abstraction of version id.

(2) 3 of the 4 `if ( chipperVersion === '2.0.0' )` expressions assume that false means it was `'0.0.0'`.  If the only 2 legal values are '2.0.0' and '0.0.0', then there should at the very least be an assertion to verify that.  Not an assumption that results in the unconditional execution of an `else`. 

(3) If someone changes chipper version id to (e.g.) "2.0.1", the build process will break. For 3 of the `if` expressions, the build tools will think it's dealing with chipper0.  For 1 of the `if` expressions (build.js), an Error will be thrown.    We should probably only be looking at the major version number, verifying that it's either '2' or '0', and then identifying the chipper vintage.  Major number should be obtained via SimVersion, not via string parsing.

(4) `if ( chipperVersion === '0.0.0' )` has no documentation to indicate that chipper0 had this version id.  This only makes sense if you have experience with chipper0 and were around during the chipper2 development process. 

2/5/18 Slack discussion in developer channel:  

```
Jonathan Olson [10:03 AM]
So perennial code I have written uses that to identify how to build (or what the build dirs will look like)

Chris Malley [10:04 AM]
Does perennial currently rely on “2.0.0” or just the major number?

Jonathan Olson [10:06 AM]
Currently relies on the whole string, but that can presumably change if we start actually versioning it internally for compatibility changes

Chris Malley [10:07 AM]
So if I were to change chipper version id to “2.0.1”, it would break everything?

Matt Pennington [10:08 AM]
Yes, perennial currently does not support chipper 2.0.1

Chris Malley [10:09 AM]
I see 4 occurences of `if ( chipperVersion === '2.0.0' )` and 1 of `if ( chipperVersion === '0.0.0')`. (edited)
That would not pass code review, imo.

Jonathan Olson [10:13 AM]
True, but we haven’t discussed the format that version would have, or how we would handle it

Chris Malley [10:13 AM]
I recall reviewing and closing the issue related to version id schema.
Or are you saying that doesn’t apply to chipper? (edited)

Jonathan Olson [10:14 AM]
We discussed sim versions

Chris Malley [10:14 AM]
Regardless of format (and especially because of format) it should be encapsualted.

Jonathan Olson [10:15 AM]
We will never RC/dev chipper itself, etc.

Chris Malley [10:15 AM]
So why is the format not still applicable?
I see no need for a different schema.
We developers are in effect always using the “production” version of chipper.

Jonathan Olson [10:16 AM]
SimVersion would be renamed RepoVersion and used?
And is that something we ever need to do with other repositories?
Do we want to wait until a dev meeting to hash it out?

Chris Malley [10:18 AM]
First step would be to replace the multiple string tests on `chipperVersion` with a function call that determines which vintage of chipper we’re dealing with, for the purposes of perennial.
That function could use (and document) the current string tests.  Documentation is currently lacking.  E.g. you may know that “0.0.0” was “chipper 1", but it’s not obvious to a general reader.
Then that function could be modified to use SimVersion (or RepoVersion if you prefer), and presumably look at the major number only.
As is, you have 5 related string tests and 1 assertion message spread across 3 .js files.
```

**Comment by samreid** [comment]
* It seems perennial should just operate based on the MAJOR or MAJOR.MINOR versions.
* If we generalize SimVersion.js, then Version.js or ProjectVersion.js may be a good name

In the absence of further information, it seems reasonable that chipper would use the same version strategies we use for sims (even though I don't envision a chipper "RC" or the likes in the near future).

**Comment by jonathanolson** [comment]
I agree this should be cleaned up, although I'm not sure yet if reusing SimVersion for other repositories is the correct choice. I don't know yet if this would only be used for chipper, or if we'll want to use it for other common repositories in the future.

I'd generally opt for creating ChipperVersion (which would have its own logic and feature detection/handling), even if it would duplicate few lines for parsing/etc.

Objections?

**Comment by pixelzoom** [comment]
Using ChipperVersion seems like a fine compromise.  And if it's properly encapsulated, will be easy to change (if necessary) in the future.

**Comment by jonathanolson** [comment]
@mattpen, devDeploy documentation doesn't have matching parameter names, so documentation will need to be updated there once I'm done with the changes.

**Comment by jonathanolson** [comment]
Implemented in the above commit. Presumably build-server will want to improve its usages of version checks (as noted in the first comment).

**Comment by mattpen** [comment]
The build-server documentation and usage have been updated.  Closing.
