### ISSUE TITLE
Problems with deployed build directory for deploy-rc from chipper 1.0

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/perennial#79]
I just deployed https://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.4.0-rc.2/, which has a chipper sha that was prior to chipper 2.0 work. Every built translation is under this directory, and the twitter card and screenshot images are also missing. It surprised me because the directory looks so different from https://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.4.0-rc.1/.

rc.1 was deployed prior to merging chipper 2.0 work with master. rc.2 was deployed after merging chipper 2.0 work with master, but is using the same chipper SHA as rc.1.

@jonathanolson and/or @mattpen is this a problem? Can I proceed with deploying the sim with its current SHAs?

**Comment by mattpen** [comment]
@jessegreenberg - The translations should not have been transferred to spot for an rc deploy.  I'll look into what went wrong there.

The image files were not generated by the build task on phet-server, so I'm not sure what happened there.  When you build it locally, do they show up?

**Comment by jessegreenberg** [comment]
They do not appear locally. But I don't remember generated images ever showing up in local builds.

**Comment by jessegreenberg** [comment]
Here is everything under local build:

![capture](https://user-images.githubusercontent.com/6396244/35934280-538e92aa-0bfa-11e8-86a9-506f366936b6.PNG)

**Comment by mattpen** [comment]
This was fixed in 917d3d364462f97b877caaf32cebcab1df219da7 and f04791411965e907ed6c8af1c42560a9ca69f732.
