### ISSUE TITLE
non-standard shebang in log.sh

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/perennial#80]
Since bash is universally installed in the same location, the standard shebang for bash scripts is:

`#!/bin/bash`

And that appears in all bash scripts in perennial/bin -- except log.sh, which has:

`#!/usr/bin/env bash`

A `/usr/bin/env` shebang is typically used for scripts to be executed by a program that will be in $PATH, but whose location may vary.  Python is a good example -- depending on the system, it may be installed in /bin, /usr/bin, /usr/local/bin/, ...

So I'm going to change log.sh to use the standard bash shebang.

**Comment by pixelzoom** [comment]
@samreid FYI, since you were the author.  Feel free to close.

**Comment by samreid** [comment]
Thanks! Closing.
