### ISSUE TITLE
API should have a version number to make backwards compatibility easier

### ISSUE THREAD

**Issue by jbphet** [phetsims/perennial#9]
The API for the build server, which is essentially a URL, should be modified to include a version number.  This will make it easier to make changes to the build server's behavior without introducing incompatibilities with previous chipper versions, which are used to make maintenance releases of simulations.  For background on the motivation for this, see https://github.com/phetsims/perennial/issues/8 and https://github.com/phetsims/rosetta/issues/101.

**Comment by jbphet** [comment]
My thinking on this is to keep it simple and just have a monotonically increasing number as the value, so there would be a parameter in the URL with something like ```version=2```.  I did a quick poll on this thought on the dev Skype channel, and @samreid supported this proposal.

**Comment by mattpen** [comment]
This should be implemented before we change the API. This will probably not occur as part of Chipper 2.0.

**Comment by jbphet** [comment]
The API has been enhanced to have this, and rosetta is using it, as are the build tools.  Closing.
